unocss/unocss

packages/core/src/generator/index.ts
test/__snapshots__/shortcuts.test.ts.snap
test/shortcuts.test.ts

Nested static variables are supported.

feat(core): nested shortcuts

---

packages/preset-uno/src/rules/index.ts
packages/preset-uno/src/rules/position.ts
test/__snapshots__/preset-uno.test.ts.snap
test/preset-uno.test.ts

feat(preset-uno): add box-sizing rules

feat(preset-uno): add box-sizing rules

---

packages/preset-uno/src/rules/transform.ts
test/__snapshots__/preset-uno.test.ts.snap
test/preset-uno.test.ts

Minor adjustment  [Supplementary transform style attribute]

feat(preset-uno): Supplementary transform style attribute

---

packages/preset-uno/src/variants/index.ts
test/__snapshots__/preset-uno.test.ts.snap
test/preset-uno.test.ts

close https://github.com/antfu/unocss/issues/37

fix(preset-uno): negative space utilities

---

packages/preset-uno/src/rules/behaviors.ts
packages/preset-uno/src/rules/index.ts
packages/preset-uno/src/rules/static.ts
test/__snapshots__/preset-uno.test.ts.snap
test/preset-uno.test.ts

1. Placeholder Color \ Placeholder Opacity
2. Screen Readers Access

feat(preset-uno): behaviors utilities

---

packages/preset-attributify/README.md

chore: typo

---

packages/preset-uno/src/rules/index.ts

If I got it right, this would close #84
My first pull request ever, hope everything is alright?!

fix(preset-uno): add screenReadersAccess to rules

---

.gitignore
README.md
packages/runtime/README.md
packages/runtime/package.json
packages/runtime/play/index.html
packages/runtime/src/attributify.ts
packages/runtime/src/core.ts
packages/runtime/src/factory/index.ts
packages/runtime/src/index.ts
packages/runtime/tsconfig.json
packages/runtime/tsup.config.ts
pnpm-lock.yaml

feat: introduce new runtime package for CSS-in-JS

---

packages/preset-uno/src/rules/static.ts

feat(preset-uno): fixes typo in statics

---

packages/cli/README.md
packages/cli/src/index.ts

@antfu Does that look good to you? Am still a little unsure to reluctant directly to main, thus the PR. 🙂

feat(cli): reload config on changes, closes #115

---

packages/preset-uno/src/rules/index.ts
packages/preset-uno/src/rules/static.ts
test/__snapshots__/preset-uno.test.ts.snap
test/preset-uno.test.ts

feat(preset-uno): isolate utilities

---

packages/preset-uno/src/rules/color.ts
packages/preset-uno/src/rules/index.ts
test/__snapshots__/cli.test.ts.snap
test/__snapshots__/preset-uno.test.ts.snap
test/preset-uno.test.ts

feat(preset-uno): fill colors utilities

---

packages/preset-uno/src/rules/position.ts
test/__snapshots__/cli.test.ts.snap
test/__snapshots__/preset-uno.test.ts.snap
test/preset-uno.test.ts

fix(preset-uno): add object center rules

---

README.md

docs: fix Attributify Mode link

---

packages/preset-uno/src/rules/position.ts

feat(preset-uno): add missing position sticky and static

---

packages/preset-uno/src/rules/index.ts
packages/preset-uno/src/rules/typography.ts
packages/preset-uno/src/theme/font.ts
packages/preset-uno/src/theme/index.ts
test/__snapshots__/preset-uno.test.ts.snap
test/preset-uno.test.ts

Used the same ratio as letter-spacing.

feat(preset-uno): word-spacing utilities

---

README.md

Because it's as simple as Vite ✨

docs: add Nuxt in installation step

---

packages/preset-uno/src/rules/grid.ts
test/__snapshots__/preset-uno.test.ts.snap

fix(preset-uno): row and col-span overwrite row- and col-start

---

packages/preset-mini/src/rules/transform.ts
test/__snapshots__/preset-uno.test.ts.snap
test/preset-uno.test.ts

feat(preset-mini): transform gpu override

---

packages/runtime/src/index.ts

Adds 2 api for runtime:
- inspect: filter elements to be mutated
- toggleObserver: pause/resume runtime

feat(runtime): add api to adjust runtime behavior

---

package.json
pnpm-lock.yaml

deps: update `vitest`, current version not working on windows

---

packages/runtime/src/index.ts

https://github.com/antfu/unocss/pull/238#discussion_r764589363

docs(runtime): add jsdocs

---

README.md

Hints for `vite + svelte` and `sveltekit` class support

docs: add `vite + svelte` and `sveltekit`

---

packages/plugins-common/context.ts
packages/preset-mini/src/rules/question-mark.ts
test/fixtures/vite-svelte/svelte.config.js

fix(preset-mini): `question-mark` rule should use `userConfig.envMode`

---

packages/preset-mini/src/variants/breakpoints.ts
test/__snapshots__/preset-uno.test.ts.snap

fix(preset-mini): breakpoints order + `lt-<bp>` regex

---

packages/preset-mini/src/rules/border.ts
test/__snapshots__/preset-mini.test.ts.snap
test/preset-mini-targets.ts

fix(preset-mini): regression border-<direction> missing

---

packages/preset-wind/src/index.ts
packages/preset-wind/src/variants.ts
packages/preset-wind/src/variants/dark.ts
packages/preset-wind/src/variants/index.ts
test/__snapshots__/preset-uno.test.ts.snap
test/preset-uno.test.ts

Add `.dark`, `.light`, `@dark`, and `@light`

feat(preset-wind): color scheme variant

---

packages/preset-mini/src/rules/color.ts
test/__snapshots__/preset-uno.test.ts.snap
test/preset-uno.test.ts

fix(preset-mini): match dash-separated color name

---

packages/core/src/types.ts

fix: improve types for regex match array

---

packages/preset-mini/src/rules/position.ts
test/__snapshots__/preset-attributify.test.ts.snap
test/__snapshots__/preset-mini.test.ts.snap
test/preset-mini-targets.ts

feat(preset-mini): prefix position- and pos-

---

packages/preset-mini/src/rules/ring.ts
packages/preset-mini/src/rules/size.ts
packages/preset-mini/src/rules/svg.ts
packages/preset-mini/src/rules/typography.ts
packages/preset-wind/src/rules/columns.ts

feat(preset-mini,preset-wind): refactor simple return

---

packages/preset-mini/src/rules/position.ts
test/__snapshots__/preset-mini.test.ts.snap

- remove `justify-items-auto` and `place-items-auto`
- add `self-baseline`

fix(preset-mini): fix position rules

---

packages/preset-mini/src/rules/border.ts
test/__snapshots__/preset-mini.test.ts.snap

refactor(preset-mini): prioritize border with sides

---

packages/preset-wind/src/rules/behaviors.ts

overscroll only with auto, contain and none

fix(preset-wind): remove overflow values

---

packages/preset-mini/src/rules/position.ts
test/__snapshots__/preset-mini.test.ts.snap

refactor(preset-mini): prioritize inset and inset with sides

---

packages/preset-mini/src/rules/transition.ts
test/__snapshots__/preset-attributify.test.ts.snap
test/__snapshots__/preset-mini.test.ts.snap

No using `all` as default value
https://tailwindcss.com/docs/transition-property

fix(preset-mini): update transition handling

---

packages/preset-mini/src/rules/ring.ts
packages/preset-mini/src/theme/font.ts
packages/preset-mini/src/theme/misc.ts
test/__snapshots__/preset-mini.test.ts.snap

- ring: https://github.com/tailwindlabs/tailwindcss/blob/51b3c0a458517b00f0f88094b56e2c17ebedfdd0/src/corePlugins.js#L1904-L1909
- box shadows: https://github.com/tailwindlabs/tailwindcss/blob/51b3c0a458517b00f0f88094b56e2c17ebedfdd0/stubs/defaultConfig.stub.js#L204-L213

feat(preset-mini): align shadow values with tailwind

---

packages/core/src/config.ts
packages/core/src/generator/index.ts
packages/core/src/types.ts
packages/preset-attributify/src/extractor.ts
packages/preset-attributify/src/index.ts
packages/preset-attributify/src/variants/attributify.ts
packages/preset-mini/src/index.ts
packages/preset-mini/src/variants/dark.ts
packages/preset-mini/src/variants/default.ts
packages/preset-mini/src/variants/pseudo.ts
packages/preset-wind/src/index.ts
packages/preset-wind/src/variants/index.ts
test/__snapshots__/preset-prefixes.test.ts.snap
test/preset-attributify.test.ts
test/preset-prefixes.test.ts

fix: revert using merged options from generator

---

packages/preset-mini/src/rules/behaviors.ts
test/__snapshots__/preset-mini.test.ts.snap
test/preset-mini-targets.ts

https://tailwindcss.com/docs/will-change

feat(preset-mini): `will-change` properties

---

packages/preset-mini/src/index.ts
packages/preset-mini/src/utils/utilities.ts

feat(preset-mini): export `parseColor` utility

---

packages/preset-icons/README.md

with this ``npm i -D @unocss/preset-icons @iconify/json`` we can use any icon in iconify.
I think if anyone wants use any icon available in iconify they should have an option.

docs(preset-icons): note about @iconify/json

---

packages/runtime/src/index.ts

Maybe add option to insert between head & body?

fix(runtime): insert style element at the beginning of html

---

packages/core/src/generator/index.ts
packages/preset-mini/src/rules/default.ts
packages/preset-mini/src/rules/variables.ts
packages/preset-wind/src/rules/default.ts
test/__snapshots__/preset-mini.test.ts.snap
test/preset-mini-targets.ts

See https://tailwindcss.com/docs/adding-custom-styles#arbitrary-properties

feat(preset-mini): add rule for using arbitrary css property

---

packages/vite/src/modes/svelte-scoped.ts

fix(svelte-scoped): try to prepend to existing style element

---

packages/core/src/generator/index.ts
packages/preset-attributify/src/variants/attributify.ts
test/__snapshots__/preset-attributify.test.ts.snap
test/preset-attributify.test.ts

fix(preset-attributify): fix support for property syntax

---

packages/preset-mini/src/utils/handlers/handlers.ts
test/__snapshots__/preset-mini.test.ts.snap
test/preset-mini-targets.ts

- skip replacing escaped underscore
- skip replacing unescaped underscore in url()

feat(preset-mini): update `handler.bracket`

---

packages/reset/tailwind.css

https://github.com/tailwindlabs/tailwindcss/blob/1eb4127de233e9323c793878d492a4c3c30c2b3b/src/css/preflight.css
Should we update/remove this rule?
https://github.com/antfu/unocss/blob/3861968ea7eab6190b2930d4f29c3cc95b02f382/packages/reset/tailwind.css#L15-L18

feat(reset): update tailwind preflight

---

packages/preset-mini/src/rules/ring.ts
test/__snapshots__/preset-mini.test.ts.snap
test/preset-mini-targets.ts

- fix shadow overriding ring variables
- add `ring-width/size-x`

fix(preset-mini): fix ring utilities

---

packages/preset-mini/src/rules/typography.ts
packages/preset-mini/src/rules/variables.ts
test/__snapshots__/preset-mini.test.ts.snap

- leading/lh
- tracking
- word-spacing

refactor(preset-mini): move more cssvar from variables to each rule

---

packages/preset-wind/src/rules/animation.ts
test/__snapshots__/preset-wind.test.ts.snap
test/preset-wind-targets.ts

- `animate-x` allows bracket & variable
- `animate-duration-x` now must use the `duration-` part (similar to transition)
- add `animate-ease-x` for `animation-timing-function` (similar to transition)

feat(preset-wind)!: rework animation utilities

---

packages/runtime/src/index.ts

Breaking on `extractAll` that got additional await.

feat(runtime)!: wait for `updateStyle()` to complete

---

packages/preset-mini/src/utils/utilities.ts
test/preset-uno.test.ts

fix(preset-mini): ignore excessive color parsing

---

README.md

docs: extend theme colors example

---

packages/preset-mini/src/utils/handlers/handlers.ts

rpx is a common unit for miniprogram

feat(preset-mini): support rpx unit

---

packages/core/src/generator/index.ts

Will be using this for keyframe individual style generator.

feat(core): extract token parser to separate method

---

packages/preset-mini/src/variants/pseudo.ts
test/__snapshots__/preset-mini.test.ts.snap
test/preset-mini-targets.ts

Reverse of `next-x`
https://github.com/antfu/unocss/blob/304bd6918b3c8507cb0188f2bbf2323e3dd33103/packages/preset-mini/src/variants/combinators.ts#L7

feat(preset-mini): add `previous-x` variant

---

packages/core/src/generator/index.ts
packages/core/src/types.ts
test/__snapshots__/order.test.ts.snap
test/order.test.ts

feat(core): add ability to prioritize variant sorting

---

packages/preset-uno/src/variants/mix.ts
test/__snapshots__/preset-uno.test.ts.snap

- use `colorToString` helper
- check for proper number on `shift`

fix(preset-uno): update mix variant

---

packages/core/src/generator/index.ts
test/__snapshots__/shortcuts.test.ts.snap
test/shortcuts.test.ts

Addresses #583.
However, imho, the overall shortcut code feels getting more complicated and the feature is not even sorting the rules, only getting the max of the sort values.

feat(core): honor sort key on shortcut

---

packages/preset-mini/src/rules/typography.ts
packages/preset-mini/src/utils/handlers/handlers.ts
packages/preset-mini/src/utils/utilities.ts
test/__snapshots__/preset-mini.test.ts.snap
test/preset-mini-targets.ts

Closes #202; ~introduces #226~.

feat(preset-mini): support text-[types:x]

---

packages/preset-mini/src/rules/border.ts
packages/preset-mini/src/utils/colors.ts
packages/preset-mini/src/utils/utilities.ts
packages/preset-wind/src/variants/placeholder.ts

- extract `hasParseableColor` as utility
- undefined checks
- types & comments

refactor(preset-mini,preset-wind): misc. refactors

---

packages/preset-mini/src/rules/ring.ts
packages/preset-mini/src/rules/shadow.ts
test/__snapshots__/cli.test.ts.snap
test/__snapshots__/preset-mini.test.ts.snap
test/__snapshots__/preset-uno.test.ts.snap

- fix ring overriding shadow when used together 
[Playground](https://unocss.antfu.me/?html=DwEwlgbgUABAxgGwIYGcUF4BEAjA5gWgHcALMAFwFN59tk4BrGABzPwEYAGGY-FOAJwoUAdjBRMkcCvgCe%2BAByZYSBAixN2XALYAPTTH4B7AK7CQFEPgS4YlHaynDK-JQD5YMKKEjxkaLCjESCCGhPg6CAZgwriYroHBoTAAZFExwAD04BDu3hC%2BqBiYCSFhEXEloeEImdm52QX%2BmPzRBADMcS0x%2BG21kO5eWf1QQA&config=&options=)

fix(preset-mini): fix ring utility

---

packages/preset-wind/src/rules/default.ts
packages/preset-wind/src/rules/static.ts
test/__snapshots__/preset-attributify.test.ts.snap
test/__snapshots__/preset-mini.test.ts.snap
test/__snapshots__/preset-wind.test.ts.snap
test/preset-attributify.test.ts
test/preset-mini-targets.ts
test/preset-mini.test.ts
test/preset-wind-targets.ts
test/preset-wind.test.ts

Override content utility in `preset-wind` only

feat(preset-wind): allow `content-x` for bracket & variable

---

packages/transformer-directives/package.json
packages/transformer-variant-group/package.json
pnpm-lock.yaml

Move `@unocss/core` to `dependencies`, align with other packages.

fix: peer deps not found

---

packages/transformer-directives/src/index.ts
test/__snapshots__/transformer-directives.test.ts.snap
test/assets/apply.css
test/transformer-directives.test.ts

fix(transformer-directives): fix declaration sorting

---

packages/transformer-directives/src/index.ts
test/transformer-directives.test.ts

- This will **not** transform nested class syntax, only parse and transform `@apply` directive.

feat(directives): parse nested class

---

packages/cli/src/index.ts

support generate the outFile path directory

feat(cli): generate the outFile path directory

---

packages/autocomplete/src/parse.ts
packages/autocomplete/src/types.ts
packages/preset-mini/src/autocomplete.ts
test/autocomplete-parse.test.ts
test/autocomplete.test.ts

`DEFAULT` is not supported since it requires nested groups.

feat(autocomplete): support nested theme object interpolation

---

playground/src/logics/uno.ts

allows arbitrary module imports in playground config editor

feat(playground): arbitrary module import

---

packages/transformer-directives/src/index.ts
test/transformer-directives.test.ts

fix(directive): transform parent children's selector

---

packages/vite/src/modes/shadow-dom.ts

@antfu I don't know if this may have any impact on the result, maybe we need to investigate further, please check the screenshots in the linked issue 
closes #739

fix(shadow-dom): escape css backslashes

---

packages/preset-attributify/src/extractor.ts
packages/preset-attributify/src/variants/attributify.ts
test/__snapshots__/preset-attributify.test.ts.snap
test/preset-attributify.test.ts

Not sure if it's a bug or not.

fix(attributify): allow important-only utils

---

playground/src/logics/uno.ts

docs(playground): fix genrate css delay

---

README.md

docs: add community preset unocss-preset-scrollbar

---

package.json
packages/vite/README.md
packages/vite/build.config.ts
packages/vite/package.json
packages/vite/src/client.ts
packages/vite/src/devtool.ts
packages/vite/src/index.ts
pnpm-lock.yaml

#796 
Just add the following lines to your main entry
```ts
import 'uno.css'
import 'virtual:unocss-devtools'
```
---
- https://windicss.org/integrations/vite.html#design-in-devtools
- https://github.com/windicss/vite-plugin-windicss/blob/main/packages/vite-plugin-windicss/src/devtools.ts

feat(vite): Design in DevTools

---

packages/preset-mini/src/variants/misc.ts
test/__snapshots__/preset-attributify.test.ts.snap
test/__snapshots__/preset-mini.test.ts.snap
test/assets/preset-mini-targets.ts
test/preset-attributify.test.ts

feat(preset-mini): support `important:` variant

---

packages/reset/tailwind.css

https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme

fix(reset): `color-schema` -> `color-scheme`

---

packages/vite/src/modes/global/dev.ts
packages/vite/src/transformers.ts

fix(vite): update @apply when config changed

---

packages/preset-attributify/README.md

Add an example on how to extend JSX/TSX for SolidJS

docs(attributify): add `SolidJS` snippet

---

packages/preset-mini/src/rules/static.ts
packages/preset-wind/src/rules/default.ts
packages/preset-wind/src/rules/static.ts
test/__snapshots__/preset-mini.test.ts.snap
test/assets/preset-mini-targets.ts

Some caveat that content-x has different behaviour in each preset.

chore(presets)!: move `content-x` from preset-wind to preset-mini

---

packages/plugins-common/utils.ts
packages/vite/src/modes/global/build.ts

https://github.com/unocss/unocss/pull/881#issuecomment-1111654927

fix(vite): only resolve unocss

---

packages/preset-icons/README.md

update `InlineCollection` type links and changed link for the vue 3 example on `@iconify/tools`

docs(preset-icons): adjust `@iconify` links

---

packages/preset-wind/src/rules/behaviors.ts
test/__snapshots__/preset-wind.test.ts.snap
test/assets/preset-wind-targets.ts

feat(preset-wind): support more list style types

---

packages/preset-typography/README.md

@ydcjeff is this ok? we're reviewing all packages... sorry to ping you directly here

docs(preset-typography): license

---

packages/vite/src/modes/global/dev.ts

fix: revert unocss/unocss#837

---

interactive/components/TheNav.vue

it will better understand the role of icons

chore: add title for TheNav icon

---

packages/vscode/package.json
packages/vscode/src/annonation.ts
packages/vscode/src/index.ts

feat(vscode): add underline config

---

packages/core/src/types.ts

missing generic type in `ConfigBase`

fix: missing generic type

---

packages/preset-mini/src/rules/static.ts

https://developer.mozilla.org/en-US/docs/Web/CSS/white-space

feat(preset-mini): add break-spaces to white-space

---

examples/vite-watch-mode/.gitignore
examples/vite-watch-mode/.npmrc
examples/vite-watch-mode/package.json
examples/vite-watch-mode/src/App.tsx
examples/vite-watch-mode/src/index.css
examples/vite-watch-mode/src/main.tsx
examples/vite-watch-mode/src/vite-env.d.ts
examples/vite-watch-mode/tsconfig.json
examples/vite-watch-mode/vite.config.ts
packages/vite/src/modes/global/build.ts

remove this code to support the build watch pattern
``` ts
vfsLayerMap.clear()
```

feat(vite): support  build watch mode

---

packages/vite/src/modes/global/build.ts

1. You will only receive a warning if you did not import uno.css when you first compiled it
2. Receive duplicate warnings when there are multiple formats

fix(vite): incorrect warning

---

packages/preset-attributify/README.md

Added Svelte and SvelteKit TS support guide

---

package.json
packages/autocomplete/package.json
packages/config/package.json
packages/core/package.json
packages/extractor-pug/package.json
packages/inspector/package.json
packages/nuxt/package.json
packages/preset-attributify/package.json
packages/preset-icons/package.json
packages/preset-mini/package.json
packages/preset-tagify/package.json
packages/preset-typography/package.json
packages/preset-uno/package.json
packages/preset-web-fonts/package.json
packages/preset-wind/package.json
packages/runtime/package.json
packages/scope/package.json
packages/transformer-compile-class/package.json
packages/transformer-directives/package.json
packages/transformer-variant-group/package.json
packages/unocss/package.json
packages/vite/package.json
packages/webpack/package.json
pnpm-lock.yaml
test/__snapshots__/cli.test.ts.snap
test/cli.test.ts

antfu/eslint-config#98
Fix the failed test since [2257fd6](https://github.com/unocss/unocss/commit/2257fd6fb31c950ceba02f46f7c4677bfc711d5b).

fix: prioritize require

---

packages/preset-mini/src/theme/types.ts
packages/preset-wind/src/rules/animation.ts
packages/preset-wind/src/theme.ts

This pr will change `animation-iteration-count` value to 1 by default.
It could be configured  https://github.com/unocss/unocss/issues/315#issuecomment-1135475014
close #1069

fix(preset-wind): set animate count 1 by default

---

packages/preset-mini/src/utils/handlers/handlers.ts
test/__snapshots__/preset-mini.test.ts.snap
test/assets/preset-mini-targets.ts

Reference: https://drafts.csswg.org/css-contain-3/#container-lengths

feat(preset-mini): add container query units

---

packages/vscode/src/contextLoader.ts

I don't think I have anything to say...

fix(vscode): fix configExists logic

---

packages/transformer-compile-class/src/index.ts

Add layer option for generated rules

feat(transformer-compile-class): add layer option

---

packages/preset-tagify/README.md

Fix small typo in presetTagify docs

chore: fix presetTagify typo

---

packages/vscode/src/annotation.ts
packages/vscode/src/index.ts

chore: fix typo

---

scripts/copy-files.ts

Hello, my first contribution to unocss is just a minor typo fix in `scripts/copy-files.ts`. 
Thank you!

fix: typo in scripts/copy-files.ts

---

packages/vscode/README.md

https://code.visualstudio.com/docs/getstarted/settings#_settingsjson

docs: fix invalid vscode's setting file name

---

packages/preset-wind/src/rules/background.ts
test/__snapshots__/preset-attributify.test.ts.snap
test/__snapshots__/preset-wind.test.ts.snap

I make a new PR from the previous and also update snapshots.

fix(preset-wind): fix background gradient stop order

---

packages/transformer-directives/src/index.ts
test/transformer-directives.test.ts

feat(directives): allow escape char in class name

---

packages/preset-mini/src/utils/variants.ts
test/__snapshots__/preset-wind.test.ts.snap
test/assets/preset-wind-targets.ts

fix(preset-mini): update missing parent rule

---

packages/preset-mini/src/rules/size.ts
test/__snapshots__/autocomplete.test.ts.snap
test/autocomplete.test.ts

Has a templete error for `size`, fixed it and adjust others.

fix(preset-mini): adjust autocomplete for size

---

README.md
packages/preset-mini/README.md

docs(preset-mini): theme usage docs

---

packages/vscode/src/index.ts

fix(vscode): hit context cache and avoid loading config file twice

---

packages/webpack/README.md

when I try to follow the documentation, it won't work!   this code is important.

docs:update packages/webpack/README.md

---

packages/preset-mini/src/rules/transition.ts
test/__snapshots__/preset-mini.test.ts.snap
test/assets/preset-mini-targets.ts

feat(preset-mini): add bracket support for transition-property

---

packages/core/src/generator/index.ts
test/__snapshots__/order.test.ts.snap
test/order.test.ts

fix: move pseudo elements with parentheses

---

packages/preset-web-fonts/README.md
packages/preset-web-fonts/src/providers/bunny.ts
packages/preset-web-fonts/src/types.ts

I just swiftly whipped this up, and it's working well on my end so far.
Heading to bed now and will check this once more tomorrow. 
@antfu, if you see anything to be adjusted, would appreciate a comment 💪🏼

feat(web-fonts): add `bunny` web-fonts provider

---

packages/preset-mini/src/rules/default.ts
packages/preset-mini/src/rules/static.ts
packages/preset-wind/src/rules/default.ts
test/__snapshots__/preset-mini.test.ts.snap
test/assets/preset-mini-targets.ts

feat(preset-mini): content visibility rules

---

packages/preset-mini/src/rules/layout.ts

[Reference](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow#syntax)

feat(preset-mini): add more overflowValues

---

interactive/components/ColorsTable.vue
packages/autocomplete/README.md
packages/preset-attributify/README.md
packages/transformer-directives/README.md

Howdy!
I was reviewing the docs for this lovely little library, and caught a few little spelling mistakes and such. Figured I might as well batch 'em up and send over a PR to fix!

docs: typo

---

packages/core/src/utils/variantGroup.ts
test/variant-group.test.ts

fix(core): update variant group regex

---

package.json
pnpm-lock.yaml

chore: upgrade vite 3.0.9

---

packages/preset-mini/src/_utils/handlers/handlers.ts
test/__snapshots__/preset-mini.test.ts.snap
test/__snapshots__/preset-wind.test.ts.snap
test/handler.test.ts

fix(preset-mini): fix escaped underscore replacements in h.bracket

---

README.md

Hello! 
Thanks for UnoCSS which is a fabulous tool ❤️ 
I just added my modest presets in the README, which I hope will be useful to some people!

docs: add some community presets

---

playground/src/components/Editor.vue

Just open the link below for more details👇
https://jam.dev/c/965392e2-5e57-45ce-ae0c-11940a6a894e

feat(playground): add reset option

---

packages/core/src/types.ts
packages/shared-integration/src/context.ts
packages/vscode/src/annotation.ts

fix(vscode): improve trigger reload config

---

packages/preset-mini/src/_rules/shadow.ts
packages/preset-mini/src/_utils/utilities.ts
test/__snapshots__/preset-mini.test.ts.snap
test/assets/preset-mini-targets.ts

feat(preset-mini): parse `shadow` with bracket

---

packages/shared-integration/src/layers.ts

resolves https://github.com/unocss/unocss/issues/1536
context: https://github.com/nuxt/framework/issues/7372

fix: allow matching virtual id with query parameters

---

package.json
pnpm-lock.yaml

chore: IDEA eslint compatibility

---

README.md

Maybe this list is better maintained as a Wiki page?

docs: add unocss-preset-daisy

---

README.md

docs: added Anu in community frameworks

---

interactive/components/details/Base.vue
interactive/components/details/Rule.vue

[issue#1619](https://github.com/unocss/unocss/issues/1619)

feat(interactive): static className copy

---

packages/preset-wind/README.md

Match docs to implementation at https://github.com/unocss/unocss/blob/main/packages/preset-mini/src/_variants/breakpoints.ts

docs(preset-wind): fix greater than breakpoint

---

packages/vscode/src/autocomplete.ts

add sass,scss,less,stylus language

feat(vscode): add sass,scss,less,stylus language

---

playground/src/components/Editor.vue
playground/src/logics/url.ts

Because of this comment. https://github.com/unocss/unocss/issues/1646#issuecomment-1261094530

feat(playground): add share button

---

packages/preset-mini/src/_rules/static.ts
test/__snapshots__/preset-mini.test.ts.snap
test/assets/preset-mini-targets.ts

See [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/word-break)

feat(preset-mini): add break-keep utility

---

packages/preset-mini/src/_theme/types.ts
packages/preset-mini/src/_variants/default.ts
packages/preset-mini/src/_variants/index.ts
packages/preset-mini/src/_variants/supports.ts
packages/preset-wind/src/theme.ts
test/__snapshots__/preset-mini.test.ts.snap
test/__snapshots__/preset-wind.test.ts.snap
test/assets/preset-mini-targets.ts
test/assets/preset-wind-targets.ts

Add standalone `supports-x` variant (See [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/@supports))

feat(preset-mini,preset-wind): add @supports variant

---

packages/cli/src/index.ts

fix(cli): load config twice

---

.eslintignore
.gitignore
package.json
packages/preset-icons/src/cdn.ts
pnpm-lock.yaml
scripts/icon-collections.ts

Use script to write json about collections after install.

feat(preset-icons): load collections

---

examples/vue-cli4/vue.config.js
packages/webpack/README.md

Linked issue: #1728 #1729 
A solution of replace content hash code of webpack4

chore(webpack): improve webpack4 usecase

---

README.md

add preset `unocss-preset-primitives` for styling primitives component
- headlessui
- radix-ui
- and you can customize it

docs: add community preset

---

packages/transformer-directives/src/apply.ts
packages/transformer-directives/src/index.ts
packages/transformer-directives/src/screen.ts
packages/transformer-directives/src/theme.ts

Deconstruct the function to make it easier to read. If you don't like it, please close pr.
This PR change: 
- deconstruct logic

chore(transformer-directives): deconstruct index.ts

---

packages/core/src/extractors/split.ts
packages/preset-mini/src/_theme/types.ts
packages/preset-mini/src/_variants/aria.ts
packages/preset-mini/src/_variants/data.ts
packages/preset-mini/src/_variants/default.ts
packages/preset-mini/src/_variants/index.ts
packages/preset-wind/src/theme.ts
test/__snapshots__/preset-mini.test.ts.snap
test/__snapshots__/preset-wind.test.ts.snap
test/assets/preset-mini-targets.ts
test/assets/preset-wind-targets.ts
test/preset-wind.test.ts

Addresses #1793 with slight syntax change to align with tailwind

feat(preset-mini,preset-wind): add aria-x and data-x support

---

packages/vscode/src/autocomplete.ts

fix(autocomplete): add astro language id

---

test/__snapshots__/preset-mini.test.ts.snap
test/assets/preset-mini-targets.ts

I think we should keep the test cases correct.

test: correct test cases

---

packages/unocss/src/preset-attributify.ts
packages/unocss/src/preset-icons.ts
packages/unocss/src/preset-mini.ts
packages/unocss/src/preset-tagify.ts
packages/unocss/src/preset-typography.ts
packages/unocss/src/preset-uno.ts
packages/unocss/src/preset-web-fonts.ts
packages/unocss/src/preset-wind.ts

Missing export default, but its type contains export default, refer https://github.com/unocss/unocss/pull/1484

fix(unocss): missing export default

---

packages/vscode/README.md

fix: https://github.com/unocss/unocss/issues/1865

doc(vscode): update readme

---

packages/transformer-attributify-jsx/src/index.ts
test/transformer-attributify-jsx.test.ts

fix(transformer-attributify-jsx): skip  curlybrace expression

---

packages/vite/src/modes/global/build.ts

fix(vite): avoid applying css transform on bundle generation

---

packages/core/src/utils/variantGroup.ts
test/transformer-variant-group.test.ts

fix(core): don't treat arrow functions as variant groups

---

packages/vite/src/modes/global/build.ts

fix(vite): generate on corresponding  chunk

---

interactive/components/Search.vue

Clear button cannot be clicked.
https://github.com/unocss/unocss/pull/1996 Problems caused by incomplete consideration.
``` ts
// interactive/components/Search.vue
function clear() {
router.push('/')
nextTick().then(() => inputEl?.focus())
}
```

chore(interactive): fix clear event does not take effect

---

packages/core/src/utils/variantGroup.ts
test/variant-group.test.ts

fix(core): support expand `@` for variant group

---

packages/core/src/utils/variantGroup.ts
test/variant-group.test.ts

fix(core): group body match question mark

---

packages/preset-icons/browser.d.ts

fix: https://github.com/unocss/unocss/issues/1956
before
after

fix(icons): browser dts

---

packages/preset-attributify/src/extractor.ts

Fixes #2055
It's a regression caused by #1921. Unfortunately, I can not reproduce the issue in tests.

fix(nuxt): fix the regression caused by #1921

---

packages/reset/tailwind.css

https://github.com/tailwindlabs/tailwindcss/pull/9174

feat(reset): honor the hidden attribute on elements in tailwind preflight

---

packages/preset-mini/src/_rules/transition.ts
test/__snapshots__/preset-attributify.test.ts.snap
test/__snapshots__/preset-mini.test.ts.snap
test/__snapshots__/preset-wind.test.ts.snap
test/__snapshots__/transformer-directives.test.ts.snap

Follows https://github.com/tailwindlabs/tailwindcss/pull/10385

feat(preset-mini): include outline-color in color properties

---

packages/preset-mini/src/_utils/handlers/handlers.ts
test/handler.test.ts

fix(preset-mini): fix calc handler replacement

---

packages/preset-attributify/src/extractor.ts

fix(preset-attributify): try to break out of unmatched regex

---

packages/preset-wind/src/variants/misc.ts
test/__snapshots__/prefix.test.ts.snap
test/prefix.test.ts
test/svelte-scoped.test.ts

Fixes #2148
Fixes #1246
For output reference: https://play.tailwindcss.com/8hCO0cn404

fix(preset-wind): apply space/divide properly (#2150

---

packages/shared-common/src/index.ts

fix(vscode): don't crash on unmatched values

---

examples/vite-react/src/main.tsx

https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-client-rendering-apis

docs: update vite-react example to react 18 api (#2214

---

packages/nuxt/src/index.ts

fix(nuxt): should work when `autoImports` disabled

---

packages/core/src/extractors/index.ts
packages/core/src/extractors/split.ts
packages/shared-common/src/index.ts
test/__snapshots__/preset-mini.test.ts.snap
test/assets/preset-mini-targets.ts

feat(preset-mini): support quoted arbitrary values

---

packages/core/src/config.ts
packages/core/src/types.ts
test/__snapshots__/variant-handler.test.ts.snap
test/variant-handler.test.ts

feat(core): add variant.match() order

---

packages/postcss/src/index.ts
test/__snapshots__/postcss.test.ts.snap
test/postcss.test.ts

chore: fix postcss tests

---

packages/preset-attributify/src/extractor.ts
test/__snapshots__/preset-attributify.test.ts.snap
test/preset-attributify.test.ts

fix(preset-attributify): remove s flag from element regex

---

packages/nuxt/src/index.ts

fix(nuxt): configFile option ignored

---

examples/vue-cli5/src/main.js

fix(examples): vue2.7 demo

---

packages/transformer-attributify-jsx/src/index.ts
test/transformer-attributify-jsx.test.ts

fix(transformer-attributify-jsx): improve element regex

---

packages/inspector/client/components/TitleBar.vue
playground/src/auto-imports.d.ts
playground/src/components.d.ts
playground/src/components/Editor.vue
playground/src/components/HeaderBar.vue
playground/src/components/panel/PanelConfig.vue
playground/src/components/panel/PanelCustomCss.vue
playground/src/components/panel/PanelHtml.vue
playground/src/components/panel/PanelOutputCss.vue
playground/src/composables/constants.ts
playground/src/composables/panel.ts
playground/src/composables/prettier.ts
playground/src/composables/uno.ts
playground/src/composables/url.ts

close #2181
You can simply preview it.

feat(playground): add custom css panel

---

packages/vite/src/modes/svelte-scoped/transform.ts
test/__snapshots__/svelte-scoped.test.ts.snap
test/svelte-scoped.test.ts

feat(vite): attributify support for svelte-scoped mode

---

README.md

Adds my preset `unocss-preset-radix` to the README.

docs: add `unocss-preset-radix` to Community Presets

---

packages/transformer-attributify-jsx/src/index.ts
test/transformer-attributify-jsx.test.ts

fix(transformer-attributify-jsx): properly extract non-valued attributes

---

.github/workflows/ci.yml
packages/cli/src/index.ts
packages/cli/src/watcher.ts
test/cli.test.ts

test: properly close cli watcher in test

---

packages/transformer-attributify-jsx/src/index.ts
test/transformer-attributify-jsx.test.ts

fix(transformer-attributify-jsx): improve attribute capturing

---

packages/preset-wind/src/rules/divide.ts
packages/preset-wind/src/rules/spacing.ts
test/__snapshots__/postcss.test.ts.snap
test/__snapshots__/preset-wind.test.ts.snap

fix(preset-wind): use 0px multiple on space-x and divide-x rules

---

docs/guide/config-file.md
docs/guide/extracting.md
docs/guide/index.md
docs/integrations/astro.md
docs/integrations/vite.md
docs/presets/tagify.md
docs/transformers/compile-class.md
docs/transformers/directives.md

This is for the new doc site (#2392 ). I skimmed through all markdown files and updated some typos and wordings.

chore: typos and wordings

---

docs/index.md

Added links and link texts, also use hover icon on icons feature.

docs: enhance feature cards

---

packages/vscode/package.json
packages/vscode/src/autocomplete.ts

feat(vscode): support configuration of languageIds via vscode settings

---

packages/reset/scripts/copy.ts

chore: build error in windows

---

docs/.vitepress/theme/style.css

docs: fix code block style

---

docs/.vitepress/contributors.ts

Updated using twitter account...
/cc @sibbng

docs: update sibbng's card

---

packages/core/src/extractors/split.ts
test/pos.test.ts

fix(vscode): fix colon highlighting

---

packages/preset-wind/src/rules/background.ts

fix(preset-wind): Solved linear-gradient not defaulting to percentage

---

docs/.vitepress/config.ts
docs/.vitepress/theme/overrides.css
docs/package.json
pnpm-lock.yaml

This PR reverts changes in #2470

docs: add offline search

---

docs/package.json
pnpm-lock.yaml

This PR updates VP to fix https://github.com/vuejs/vitepress/issues/2222

docs: update VP to 69

---

docs/presets/community.md

docs: add a community transformer

---

packages/nuxt/src/index.ts
packages/nuxt/src/types.ts

fix #2555
This PR aims to add Vite 'mode' config to the Nuxt package.

feat(nuxt): add mode config

---

packages/core/src/utils/variantGroup.ts
test/__snapshots__/transformer-variant-group.test.ts.snap
test/assets/variant-group.vue
test/transformer-variant-group.test.ts

Fixes #2582 
Not sure if there are caveats to this solution, but it solves the problem.

fix(transformer-variant-group): breakpoint alias

---

packages/preset-mini/src/_rules/position.ts

close #2609  Thanks @shishkin.

feat(preset-mini): add `justify-stretch` rule

---

packages/core/src/extractors/split.ts

fix(core): don't splite code with `*`

---

docs/presets/icons.md

docs(preset-icons): update iconify links

---

docs/tools/autocomplete.md

modify wrong suggestions in Example 1

docs: fix typo

---

docs/guide/why.md
docs/presets/attributify.md
docs/presets/icons.md
docs/presets/uno.md

Hope you don't mind a few small documentation fixes. I ran into these while learning how awesome this tool is :slightly_smiling_face:
Some of the commits will have justifications in the commit bodies.
I'm assuming that this will be squash-merged (if it's merged), but let me know if you need me to clean up this PR's history :slightly_smiling_face:

docs: fix typos and grammar

---

packages/preset-mini/src/_rules/variables.ts
packages/preset-mini/src/_utils/handlers/handlers.ts
test/assets/preset-mini-targets.ts
test/preset-mini.test.ts

fix(preset-mini): update cssProperty & `cssvar` util regex

---

examples/nuxt3/package.json
packages/nuxt/src/index.ts
packages/nuxt/src/types.ts

close #2786
I don't know if I am missing some types, if yes can you guide me.

feat(nuxt): add `unocss:config` hook

---

packages/preset-web-fonts/src/providers/bunny.ts

fix(preset-web-fonts): fix creation of import URL for `bunny`

---

packages/preset-attributify/src/extractor.ts

fix(attributify): add `stroke-opacity` to default ignore attrs

---

packages/vite/src/modes/global/build.ts

fix(vite): map vfsLayers to unocss layers

---

packages/inspector/client/composables/usePrettify.ts

see https://github.com/vueuse/vueuse/commit/4d7577ee

chore: fix types

---

packages/preset-mini/src/_rules/typography.ts
packages/preset-mini/src/_theme/default.ts
packages/preset-mini/src/_theme/font.ts
packages/preset-mini/src/_theme/types.ts
test/assets/output/preset-mini-font-weight-theme.css
test/preset-mini.test.ts

feat(preset-mini): support fontWeight theme config

---

packages/nuxt/src/index.ts

fix(nuxt): do not inject `uno.css` on `dist-chunk` mode

---

docs/.vitepress/config.ts
docs/integrations/jetbrains.md
docs/integrations/vscode.md
docs/integrations/webstorm.md

Add webstorm plugin for unocss
Close https://github.com/unocss/unocss/issues/1166

docs: add jetbrains ide plugin doc

---

docs/config/shortcuts.md
docs/config/variants.md
docs/integrations/vite.md
docs/presets/attributify.md
packages/core/src/utils/escape.ts

Use semi single quote instead full single quote.

docs: use semi single quote

---

packages/preset-icons/build.config.ts

Fix type error after updating unbuild

chore(preset-icons): update unbuild config

---

packages/vscode/src/index.ts

Resolved #2993, #3000, #3001. This is a bug I introduced in #2979. I mistakenly removed the code that initializes `contextLoader`.
And now, the `contextLoader` will not be created repeatedly. Only if the config is not found in the current working directory (`cwd`) -- it implies unocss is not installed -- a registration will be attempted.

fix(vscode): repeat registration on reload

---

docs/presets/community.md

docs: add grid areas community preset

docs: add grid areas community preset

---

playground/src/composables/uno.ts

fix(playground): type error

---

packages/inspector/client/components/TitleBar.vue
playground/src/auto-imports.d.ts
playground/src/components/HeaderBar.vue
playground/src/components/panel/PanelConfig.vue
playground/src/components/panel/PanelCustomCss.vue
playground/src/components/panel/PanelHtml.vue
playground/src/components/panel/PanelOutputCss.vue
playground/src/composables/constants.ts
playground/src/composables/prettier.ts
playground/src/composables/uno.ts
playground/src/composables/url.ts

feat(playground): transfrom custom css

---

packages/postcss/src/apply.ts
test/__snapshots__/postcss.test.ts.snap
test/postcss.test.ts

fix: #3023
The change of snapshot seems to be correct

fix(postcss): incorrect order of breakpoints

---

packages/preset-mini/src/_rules/position.ts
packages/preset-mini/src/_theme/default.ts
packages/preset-mini/src/_theme/misc.ts
packages/preset-mini/src/_theme/types.ts
test/preset-mini.test.ts

feat(preset-mini): align with theme for zIndex

---

docs/guide/why.md

Fixed English grammar and a few typos

docs: fix grammar and typos

---

packages/astro/src/index.ts

fix: https://github.com/unocss/unocss/issues/2987#issuecomment-1708376281

fix(astro): HMR not work in windows

---

docs/presets/community.md

I'd like to introduce this to the community, even though the package is still in beta. 🚀 I hope this is allowed here.

docs: add una-ui framework and preset to community section

---

docs/integrations/cli.md

https://github.com/unocss/unocss/blob/42a57089a6b2686854bbdea4e1ff647070bdfe3e/packages/cli/src/cli-start.ts#L24

docs(cli): supplementary `--write-transformed` option

---

docs/guide/why.md

Just a few small improvements/corrections to the "Why" section of the docs.

docs: improve "why" section

---

packages/vscode/package.json
packages/vscode/src/index.ts

fix(vscode): Changing configuration in auto roots mode creates duplicate instances

---

packages/transformer-attributify-jsx/src/index.ts
test/transformer-attributify-jsx.test.ts

fix(attributify-jsx): prevent special characters

---

docs/integrations/runtime.md

docs: clarify runtime options

---

docs/presets/wind.md

docs: clarify compatibility with tailwind & windi css

---

packages/webpack/src/index.ts

fix(webpack): escape backslash in css

---

packages/preset-wind/src/rules/spacing.ts
packages/preset-wind/src/variants/misc.ts
test/__snapshots__/postcss.test.ts.snap
test/assets/output/preset-mini-targets.css
test/assets/output/preset-wind-targets.css
test/assets/preset-mini-targets.ts
test/assets/preset-wind-targets.ts

fix(preset-wind): update regex to use space rule & variant strictly

---

docs/config/rules.md

docs: clarify dynamic rule sorting

---

packages/vscode/src/index.ts

The original uno.root did not have the ability to monitor file changes and updates. Now combined with the logic of rootRegisterAuto, you will have this ability, and there is no need to distinguish between different branches to maintain two sets of code.

refactor(vscode): merge rootRegisterAuto and rootRegisterManual into rootRegister

---

packages/vscode/src/index.ts

fix(vscode): root equal empty array

---

packages/transformer-directives/src/apply.ts
playground/src/auto-imports.d.ts
test/transformer-directives.test.ts

fix(directives): resolve scoped css

---

.gitignore
packages/shared-integration/src/context.ts

fix(vscode): path resolve on filesystem config

---

packages/preset-mini/src/_utils/utilities.ts
test/layer.test.ts

fix: shadow does not take into account custom color

---

.github/workflows/ci.yml
packages/nuxt/src/index.ts
packages/nuxt/src/options.ts
packages/nuxt/src/types.ts

feat(nuxt): inject uno.css adjustable

---

packages/preset-mini/src/_utils/handlers/handlers.ts
playground/src/auto-imports.d.ts
test/assets/output/preset-mini-targets.css
test/assets/preset-mini-targets.ts

feat(preset-mini): support css variable defaultValue

---

packages/preset-mini/src/_rules/behaviors.ts
test/assets/output/preset-mini-targets.css
test/assets/preset-mini-targets.ts

this adds `appearance-auto` to be compatible with TailwindCSS v3.4.0

feat(preset-mini): add `appearance-auto` utility

---

docs/.vitepress/config.ts
docs/config/theme.md
docs/guide/packages.md
docs/presets/legacy-compat.md
docs/presets/mini.md
packages/preset-legacy-compat/README.md
packages/preset-legacy-compat/build.config.ts
packages/preset-legacy-compat/package.json
packages/preset-legacy-compat/src/comma-color.ts
packages/preset-legacy-compat/src/index.ts
packages/preset-legacy-compat/test/comma-color.test.ts
pnpm-lock.yaml

Trying to resolve #3478, resolve #3221
TODO:

feat: introduce legacy-compat preset

---

packages/preset-mini/src/_rules/position.ts

fix(preset-mini): missing place-items

---

packages/vite/src/modes/global/build.ts
packages/vite/src/modes/global/dev.ts

I don't think this needs any more explanation but the current warning doesn't quite sound right.

chore(vite): improve wording

---

docs/integrations/cli.md

docs(cli): add info for cli with pnpm, closes https://github.com/unocss/unocss/issues/3545

docs(cli): add info for cli with pnpm (#3545)

---

docs/presets/wind.md

docs:  _blank target for interactive docs link

---

packages/shared-integration/src/layers.ts

fix: capture group of RESOLVED_ID_RE

---

packages/preset-uno/src/variants/mix.ts

make the format consistent with other parts.

chore(preset-uno): make code style consistent

---

packages/shared-integration/src/layers.ts
packages/vite/src/modes/global/build.ts
packages/webpack/src/index.ts

fix(webpack): escape special chars in robust way

---

docs/integrations/vscode.md

We already support the automatic detection of monorepo, so there is no need for users to configure it additionally.

docs(vscode): update

---

packages/preset-attributify/src/extractor.ts
test/__snapshots__/preset-attributify.test.ts.snap
test/preset-attributify.test.ts

fix(preset-attributify): fix parsing error for inline arrow functions

---

packages/shared-integration/src/transformers.ts

fix(transform-variant-group): Sourcemap warning with Nuxt

---

packages/vite/src/modes/vue-scoped.ts

fix(vue-scoped): Scope only takes effect for vue files

---

packages/preset-mini/src/_theme/misc.ts
test/assets/output/preset-mini-targets.css
test/assets/output/transformer-directives-apply.css

Change `DEFAULT` ringWidth from `1` => `3`
Resolves #3672

feat(preset-mini)!: ringWidth default changed to `3px` to align with Tailwind

---

packages/eslint-config/package.json
packages/preset-icons/package.json
packages/preset-uno/package.json
packages/vite/package.json

Part of https://github.com/unocss/unocss/issues/3675

fix(packages): add types versions

---

packages/nuxt/package.json
packages/scope/package.json

Part of https://github.com/unocss/unocss/issues/3675

fix(scope): fix export types & main entry

---

packages/vscode/package.json

fix(vscode): The information displayed by hover and autocomplete is inconsistent

---

packages/autocomplete/src/create.ts
packages/autocomplete/src/types.ts
packages/autocomplete/src/utils.ts
packages/vscode/src/autocomplete.ts
test/autocomplete-utils.test.ts
test/autocomplete.test.ts

fix(autocomplete): disable autocomplete for attributify props when not using

---

packages/postcss/src/apply.ts

fix(postcss): fix #3699

---

packages/postcss/src/apply.ts
packages/preset-mini/src/_variants/pseudo.ts
test/__snapshots__/order.test.ts.snap
test/assets/output/preset-mini-targets.css

fix(preset-mini): `marker` pesudo element

---

packages/postcss/src/apply.ts
packages/shared-integration/src/defaults.ts
packages/vscode/package.json
test/pos.test.ts

fix(shared-integration): defaultIdeMatchInclude

---

packages/preset-mini/src/_rules/question-mark.ts

fix(preset-mini): remove LF in question mark rule

---

packages/preset-mini/src/_rules/transform.ts
test/assets/output/preset-mini-targets.css

fix(preset-mini): transform-cpu

---

packages/webpack/src/index.ts

fix(webpack): sourceMap

---

docs/integrations/postcss.md
examples/vite-svelte-postcss/postcss.config.cjs
examples/vite-svelte-postcss/postcss.config.js
examples/vite-vue3-postcss/postcss.config.cjs
examples/vite-vue3-postcss/postcss.config.js

fix(docs): update docs/examples related to `@unocss/postcss`

---

package.json
packages/preset-legacy-compat/src/comma-color.ts
pnpm-lock.yaml
test/preset-legacy-compat.test.ts
tsconfig.json

fix(preset-legacy-compat): update the split color string regex

---

packages/preset-mini/src/_variants/pseudo.ts
packages/preset-wind/src/postprocessors/important.ts
test/assets/output/preset-mini-targets.css
test/assets/output/preset-wind-important-string.css

fix(preset-mini): align with `selection`

---

packages/cli/src/index.ts

fix(cli): extractors not working

---

packages/preset-mini/src/_utils/utilities.ts

fix(preset-mini): directionSize size cause error when size is undefined

---

packages/vite/src/modes/global/build.ts

fix(vite): unocss:global:build:bundle no CSS placeholder

---

packages/transformer-directives/src/apply.ts
test/transformer-directives.test.ts

feat(transformer-directives): add removeComments

---

packages/cli/test/__snapshots__/cli.test.ts.snap
packages/cli/test/cli.test.ts
packages/preset-mini/src/_utils/utilities.ts

feat(preset-mini): add rawColorComment

---

packages/vite/src/modes/shadow-dom.ts

fix(vite): unocss:shadow-dom sourcemap

---

.gitignore
docs/presets/web-fonts.md
examples/vite-vue3/index.html
examples/vite-vue3/package.json
examples/vite-vue3/src/App.vue
examples/vite-vue3/uno.config.ts
examples/vite-vue3/vite.config.ts
packages/preset-web-fonts/build.config.ts
packages/preset-web-fonts/package.json
packages/preset-web-fonts/src/local.ts
packages/preset-web-fonts/src/preset.ts
packages/preset-web-fonts/src/types.ts
packages/shared-common/src/index.ts
packages/shared-common/src/replace-async.ts
pnpm-lock.yaml
test/assets/output/preset-web-fonts-local.css
test/pos.test.ts
test/preset-web-fonts.test.ts
tsconfig.json

fix #3646
alternative to #3723, thanks to the existing work by @onmax & @userquin

feat(web-fonts): ability to serve fonts from local

---

packages/preset-icons/src/types.ts

Support https://github.com/iconify/iconify/pull/317. Useful in Slidev.

feat: support multiple node resolve path

---

CONTRIBUTING.md

From https://github.com/unocss/unocss/issues/4046#issuecomment-2267080872

docs: improve contributing guide

---

packages/core/src/config.ts
packages/core/src/utils/basic.ts
packages/core/test/config.test.ts

Closes https://github.com/unocss/unocss/issues/4067

fix(core): fix config content pipline merging

---

packages/rule-utils/src/themeFn.ts
test/transformer-directives.test.ts

feat(rule-utils): parse `DEFAULT` key of theme

---

interactive/app.vue
playground/index.html

https://www.google.com/search?q=site%3Aunocss.dev%2Fplay
https://www.google.com/search?q=site%3Aunocss.dev%2Finteractive

chore: block search indexing for Playground and Interactive docs

---

packages/preset-mini/src/_variants/data.ts
test/assets/output/preset-mini-targets.css
test/assets/preset-mini-targets.ts

fix(preset-mini): data attributes with named groups

---

packages/webpack/src/unplugin.ts

fix(webpack): resolve config before processing

---

packages/core/src/generator/index.ts
packages/core/src/types.ts
packages/vite/src/modes/global/build.ts
test/fixtures/vite/uno.config.ts

feat(vite): apply transformers to preflights during build

---

packages/nuxt/src/index.ts

fix(nuxt): fix nuxt layers regression

---

packages/nuxt/src/index.ts

I hope this makes it a little bit more readable and the config is now loaded once instead of twice.

refactor(nuxt): config loader cleanup

---

test/assets/output/preset-web-fonts-local.css

This PR simply updates the snapshots to fix tests failing.
e.g. https://github.com/vitejs/vite-ecosystem-ci/actions/runs/11359196722/job/31594926626
Some of the other PRs are failing with the same snapshot mismatch.

chore: update snapshot

---

packages/core/src/config.ts
packages/core/test/config.test.ts

fix(core): don't set default value when merge content

---

packages/core/test/__snapshots__/order.test.ts.snap
packages/preset-mini/src/_variants/pseudo.ts
test/assets/output/preset-mini-targets.css

fix(preset-mini): delete the space before `marker`

---

pnpm-lock.yaml
pnpm-workspace.yaml

Thanks @xsjcTony , related to https://github.com/zyyv/vue-flow-layout/issues/1

chore: bump `vue-flow-layout` version

---

packages/core/src/utils/variant-group.ts
test/transformer-variant-group.test.ts

fix(transfomer-variant-group): ignore regex start with `/`

---

packages/preset-web-fonts/src/index.ts
test/assets/output/preset-web-fonts-local.css

chore(preset-web-fonts): update fetch useragent

---

docs/.vitepress/contributors.ts

This PR removes X and adds my new bluesky link.
/cc @antfu do you want me to remove your X link here?

docs: update userquin social links

---

docs/presets/community.md

[Tailwind Motion](https://rombo.co/tailwind/) by [RomboHQ](https://rombo.co/tailwind/) is an MIT licensed and open-source animation Tailwind plugin that has a ton of features via a declarative syntax. You can build highly complex animations with simple class bases and presets.
This preset is a full 100% port of that codebase.
Based off other existing animation presets, this one appears to offer the best animation options for developers as of now.

docs: update community.md with new animation library

---

packages/preset-wind/build.config.ts
packages/preset-wind/package.json
packages/preset-wind/rules.d.ts
packages/preset-wind/shortcuts.d.ts
packages/preset-wind/src/rules.ts
packages/preset-wind/theme.d.ts
packages/preset-wind/variants.d.ts

PR for this https://github.com/unocss/unocss/issues/4266

feat: export submodules of preset-wind seperately

---

packages/inspector/client/components/CodeMirror.vue
packages/inspector/client/theme.ts

docs(playground): tooltip style

---

packages/postcss/src/apply.ts
test/__snapshots__/postcss.test.ts.snap
test/postcss.test.ts

Addresses case of #4269. Not sure if more areas change the order

fix(postcss): keep rule order

---

packages/postcss/src/apply.ts
test/__snapshots__/postcss.test.ts.snap
test/postcss.test.ts

Avoid root.nodes to contain child nodes of type root

fix(postcss): don't add root node to root

---

examples/qwik/package.json
examples/remix/package.json
examples/sveltekit-preprocess/package.json
examples/sveltekit-scoped/package.json
examples/sveltekit/package.json
examples/vite-elm/package.json
examples/vite-lightningcss/package.json
examples/vite-lit/package.json
examples/vite-preact/package.json
examples/vite-pug/package.json
examples/vite-react/package.json
examples/vite-solid/package.json
examples/vite-svelte-postcss/package.json
examples/vite-svelte/package.json
examples/vite-vue3-postcss/package.json
examples/vite-vue3/package.json
examples/vite-watch-mode/package.json
packages/astro/package.json
packages/unocss/package.json
packages/vite/package.json
pnpm-lock.yaml
pnpm-workspace.yaml

- Upgrade Vite to v6
- Add Vite 6 to peer deps

feat: support Vite 6

---

packages/core/src/config.ts
packages/core/src/generator/index.ts
packages/core/src/types.ts
packages/core/test/presets.test.ts
packages/shared-integration/src/context.ts
packages/svelte-scoped/src/_vite/index.ts
packages/transformer-directives/src/icon.ts
playground/src/composables/uno.ts

feat(core)!: support async presets. `resolvePreset` and `resolvePresets` now returns promise

---

packages/core/test/__snapshots__/order.test.ts.snap
packages/preset-mini/src/_variants/default.ts
packages/preset-mini/src/_variants/pseudo.test.ts
packages/preset-mini/src/_variants/pseudo.ts
packages/preset-wind/src/postprocessors/important.ts
test/assets/output/preset-mini-targets.css
test/assets/output/preset-wind-important-string.css

close #4283
Before this, the error handling method was related to #4221 #3771

fix(preset-mini): spread mutiple pseudo-elements for correct variant handling

---

packages/autocomplete/src/create.ts
packages/core/src/config.ts
packages/core/src/generator/index.ts
packages/core/src/types.ts

This PR is against the `pf` branch for #4252

perf(core): simplify internal map structure

---

packages/preset-legacy-compat/src/index.ts
test/preset-legacy-compat.test.ts

feat(preset-legacy-compat): add `legacyColorSpace` option

---

packages/webpack/src/unplugin.ts

fix(rspack): optimize unplugin rspack plugin.__vfsModules id not includes __virtualModulePrefix #4297

fix(rspack): optimize unplugin rspack plugin.__vfsModules id not includes __virtualModulePrefix

---

docs/presets/legacy-compat.md

docs(preset-legacy-compat): add `legacyColorSpace` option

---

packages/preset-typography/src/index.ts
packages/preset-typography/src/preflights/default.ts
packages/preset-typography/src/preflights/index.ts
test/preset-typography.test.ts

feat(preset-typography): support element modifiers

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
docs/.vitepress/config.ts

docs: fix broken CONTRIBUTING link in issue templates

---

packages-presets/preset-typography/package.json
packages-presets/preset-typography/src/index.ts
packages-presets/rule-utils/src/colors.ts
pnpm-lock.yaml
test/preset-typography.test.ts

feat(preset-typography): compatible with theme colors with alpha placeholder

---

docs/presets/icons.md
playground/src/composables/constants.ts

docs: icon accessibility

---

packages-presets/preset-wind4/build.config.ts
packages-presets/preset-wind4/postprocess.d.ts
packages-presets/preset-wind4/src/index.ts
packages-presets/preset-wind4/src/postprocess/varPrefix.ts

fix postprocessors for variable prefix.
Related to #4439

fix(preset-wind4): fix postprocessors for variable prefix

---

packages-presets/preset-wind4/src/rules/background.ts
packages-presets/preset-wind4/src/rules/border.ts
packages-presets/preset-wind4/src/theme/types.ts
packages-presets/preset-wind4/src/utils/utilities.ts
test/assets/output/preset-wind4-targets.css

fix(preset-wind4): fix theme color resolved key

---

package.json

FYI: https://github.com/pnpm/pnpm/releases/tag/v10.0.0

chore: allow deps run scripts on pnpm install

---

packages-engine/core/src/utils/variant-group.ts
packages-engine/core/test/variant-group.test.ts

fix(transformer-variant-group): correctly match square brackets

---

pnpm-lock.yaml
pnpm-workspace.yaml

fix: upgrade & unpin `unconfig`

---

docs/extractors/arbitrary-variants.md
docs/extractors/mdc.md
docs/extractors/pug.md
docs/extractors/svelte.md
docs/guide/style-reset.md
docs/integrations/astro.md
docs/integrations/cli.md
docs/integrations/eslint.md
docs/integrations/next.md
docs/integrations/nuxt.md
docs/integrations/postcss.md
docs/integrations/svelte-scoped.md
docs/integrations/vite.md
docs/integrations/webpack.md
docs/presets/attributify.md
docs/presets/icons.md
docs/presets/legacy-compat.md
docs/presets/mini.md
docs/presets/rem-to-px.md
docs/presets/tagify.md
docs/presets/typography.md
docs/presets/web-fonts.md
docs/presets/wind3.md
docs/presets/wind4.md
docs/tools/core.md
docs/transformers/attributify-jsx.md
docs/transformers/compile-class.md
docs/transformers/directives.md
docs/transformers/variant-group.md

[Bun](https://bun.sh/) is a fast JavaScript all-in-one toolkit.
It's useful for many users to use `bun` command.
Therefore, I added the `bun` scripts to code-groups.

docs: add `bun` package manage to code-groups

---

playground/src/auto-imports.d.ts
playground/src/components.d.ts
playground/src/components/SelectLayers.vue
playground/src/components/panel/PanelCustomCss.vue
playground/src/components/panel/PanelOutputCss.vue
playground/src/composables/prettier.ts
playground/src/main.ts

feat(playground): output css panel filter by layers

---

packages-presets/preset-wind4/src/rules/color.ts

Support `scheme` in rules
close #4490

perf(preset-wind4): optimize scheme rule

---

packages-integrations/inspector/src/index.ts

fix(inspector): inspector base with vite base

---

packages-presets/preset-wind4/src/index.ts
packages-presets/preset-wind4/src/preflights/theme.ts
test/assets/output/preset-wind4-theme.css
test/preset-wind4.test.ts

feat(preset-wind4): add `processThemeVars` option

---

packages-integrations/eslint-plugin/src/rules/order.test.ts
packages-integrations/eslint-plugin/src/rules/order.ts

close #3027 
Thanks for @Nirlah #3143

feat(eslint-plugin): support ordering jsx binding

---

packages-integrations/inspector/src/index.ts

fix(inspector): fix log path

---

packages-presets/preset-wind4/src/rules/ring.ts
packages-presets/preset-wind4/src/rules/shadow.ts
test/assets/output/preset-wind4-targets.css

fix(preset-wind4): `presetWind4` ring rules

---

packages-integrations/vscode/tsup.config.ts

chore(vscode): enable tsup `shims` option

---

packages-presets/preset-wind4/src/rules/border.ts
test/assets/output/preset-wind4-targets.css

fix(preset-wind4): provide rule context in border rules

---

docs/integrations/vite.md

This updates the shown example code to match how the Vite config file in a newly created SvelteKit project looks like.

docs: update SvelteKit integration vite config example

---

packages-presets/preset-wind4/src/utils/utilities.ts
test/assets/output/preset-wind4-targets.css
test/preset-wind4.test.ts

fix(preset-wind4): abandon using JSON.stringify for initial-value

---

packages-presets/preset-wind4/src/rules/behaviors.ts
test/assets/output/preset-wind4-targets.css
test/assets/preset-wind4-targets.ts

fix(preset-wind4): add support for arbitrary values in will-change

---

packages-presets/preset-mini/src/_utils/utilities.ts
packages-presets/preset-wind4/src/utils/utilities.ts

fix(preset-mini, preset-wind4): compatible `colorResolver` matches `undefined`

---

docs/presets/wind4.md

docs: describe `presetWind4`

---

packages-presets/preset-wind4/src/utils/utilities.ts
test/assets/output/preset-wind4-targets.css
test/preset-wind4.test.ts

fix(preset-wind4): patch theme default key

---

packages-integrations/inspector/client/auto-imports.d.ts
packages-presets/preset-mini/src/_variants/aria.ts
packages-presets/preset-mini/src/_variants/data.ts
packages-presets/preset-wind4/src/variants/aria.ts
packages-presets/preset-wind4/src/variants/data.ts
playground/src/auto-imports.d.ts
test/__snapshots__/postcss.test.ts.snap
test/assets/output/preset-wind-targets.css
test/assets/output/preset-wind4-targets.css
test/assets/preset-wind-targets.ts
test/assets/preset-wind4-targets.ts
test/preset-mini.test.ts

fix(preset-mini, preset-wind4): mutiplePass for `aria` & `data`

---

packages-presets/preset-wind4/src/preflights/theme.ts
packages-presets/preset-wind4/src/utils/utilities.ts
test/preset-wind4.test.ts

close #4573
Now get values ​​by key from the `theme` will be smarter, unocss will try its best to get the value.

feat(preset-wind4): smarter theme parser

---

packages-presets/preset-wind4/src/rules/typography.ts
test/assets/output/preset-wind4-targets.css
test/assets/preset-wind4-targets.ts

feat(preset-wind4): compatible text-shadow with Tailwind4

---

packages-presets/transformer-directives/src/apply.ts
test/transformer-directives.test.ts

fix(transformer-directives): mangled @apply chained breakpoints

---

packages-presets/preset-wind4/src/rules/flex.ts
test/assets/output/preset-mini-targets.css
test/assets/output/preset-wind4-targets.css
test/assets/preset-mini-targets.ts
test/preset-wind4.test.ts

fix(preset-mini, preset-wind4): add flex basis fraction parse

---

packages-presets/transformer-directives/src/transform.ts
test/transformer-directives.test.ts

close #4639, close #4641, related #4626

fix(transformer-directives): safely remove empty blocks

---

packages-presets/transformer-directives/src/apply.ts

close: #4588, related to #4605

fix(transformer-directives): patch `presetWind4` parse error with `@apply` (2)

---

packages-integrations/webpack/src/unplugin.ts
pnpm-lock.yaml
pnpm-workspace.yaml

Should solve https://github.com/unocss/unocss/issues/4660

fix(unplugin): update to 2.3.4 and fix vfs iterable

---

packages-presets/preset-wind4/src/rules/static.ts
test/assets/output/preset-wind4-targets.css
test/assets/preset-wind4-targets.ts

feat(preset-wind4): add collapse visibility

---

packages-presets/preset-wind4/src/rules/grid.ts
test/assets/output/preset-wind4-targets.css
test/assets/preset-wind4-targets.ts

feat: add numbers & css variables for col and row grid utils

---

packages-presets/preset-wind4/src/rules/shadow.ts
packages-presets/preset-wind4/src/theme/misc.ts
test/assets/output/preset-wind4-targets.css
test/assets/preset-wind4-targets.ts

- add the missing `inset-shadow-none`
- align the `text-shadow`s
- fix inset and normal shadows used together

fix(preset-wind4): align shadows with tailwind

---

packages-presets/preset-wind4/src/rules/ring.ts
test/assets/output/preset-wind4-targets.css

fix(preset-wind4): fix `ring` offset size rule

---

docs/presets/wind4.md
packages-engine/core/src/config.ts
packages-engine/core/src/types.ts
packages-presets/preset-web-fonts/src/preset.ts
packages-presets/preset-web-fonts/src/types.ts
test/__snapshots__/preset-web-fonts.test.ts.snap
test/preset-web-fonts.test.ts

feat(preset-web-fonts): automatically detects presets and uses the correct key

---

packages-presets/preset-wind4/src/rules/background.ts
test/assets/output/preset-wind4-targets.css
test/assets/preset-wind4-targets.ts

[tw4](https://play.tailwindcss.com/txGmXepqaT)
[unocss](https://unocss.dev/play/#html=DwEwlgbgBAxgNgQwM5ILwCIAWBaATAFigCMBzbOMAOwFMEAnbARgAYoAzOgewFtsAHAK50%2BcatgCszVgBdO-KgGsJU9AD5gAenARVAKFCRYiFBiRgAXmIJQuAyiGohsbAXDjEydBOATuOPeUolfCl2Ll4QgFIoWWcBGEwzBGwAdhV1LUg9A2h4ZDR0M0s8Qlt7Rzi3D2wvHzhsAG0EaQB9SUiWlPFIgF0wgKQFAE88UIgwZKI4ATEQmTkqcBI5AE5Q2LXItU1tbO0jfNMLK1LOOwcnFyrSGu8J%2BqbW3G6W597%2B3gB3TDBpahi5OYqDBsGt5qluttMjp9Ps8iZCscSjYzuVLq53DcYJxKGAYB9sFMZtgAGzrOSDEZzAHKLYZXawwzwgpFE4o84VK6YsjY3EgxgADlY-l4izAy1JYwm2DFEskNNlcjJzChDJyBwRrORZQulW52F5eK01BgdFoZkoJAJ404omkqSlyQo3DEAGZydgbXaHSr6VkgA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owDq2yALHAL5zpQQhwDkArlggBjKlV4AoVAA9IsFBgCG-ADbw0mHPkLAiACgQS45SjRhUAXHADaFarQZZmegJQBdEkbgR%2BMML4AVCFwxABlFAE9UKEs4GCh%2BVE9WFwkgA&css=PQKgBA6gTglgLg …

fix(preset-wind4): update conic gradient syntax

---

docs/integrations/svelte-scoped.md
examples/sveltekit-scoped/src/lib/ClsxDemo.svelte
examples/sveltekit-scoped/src/routes/+page.svelte
packages-integrations/svelte-scoped/package.json
packages-integrations/svelte-scoped/src/_preprocess/transformClasses/findClasses.test.ts
packages-integrations/svelte-scoped/src/_preprocess/transformClasses/findClasses.ts
packages-integrations/svelte-scoped/src/_preprocess/transformClasses/processClasses.ts
packages-integrations/svelte-scoped/src/_preprocess/transformClasses/processClsx.test.ts
packages-integrations/svelte-scoped/src/_preprocess/transformClasses/processClsx.ts
packages-integrations/svelte-scoped/test/cases/clsx/Input.svelte
packages-integrations/svelte-scoped/test/cases/clsx/OutputDev.svelte
packages-integrations/svelte-scoped/test/cases/clsx/OutputProd.svelte
pnpm-lock.yaml
pnpm-workspace.yaml

feat(svelte-scoped): handle clsx like classes

---

packages-presets/preset-wind4/src/utils/utilities.ts
test/preset-wind4.test.ts

fix(preset-wind4): improve regex accuracy

---

packages-deprecated/preset-uno/package.json
packages-deprecated/preset-wind/package.json
packages-presets/preset-wind3/package.json
packages-presets/preset-wind4/package.json

chore: update repository.url

---

packages-presets/transformer-directives/src/functions.ts
test/transformer-directives.test.ts

feat(transformer-directives): support default value for theme function

---

packages-presets/preset-mini/src/_variants/aria.ts
packages-presets/preset-mini/src/_variants/data.ts
packages-presets/preset-mini/src/_variants/default.ts
test/assets/output/preset-mini-targets.css
test/preset-mini.test.ts
test/preset-wind4.test.ts

feat(preset-mini): nested tagged variants

---

packages-integrations/vscode/src/utils.ts

fix(vscode): fix custom theme colors display

---

docs/presets/wind3.md

`source code` in https://unocss.dev/presets/wind3#rules is broken.

docs: fix broken link

---

packages-presets/preset-wind4/src/rules/background.ts
test/assets/output/preset-wind4-targets.css
test/assets/preset-wind4-targets.ts

Resolves #4802 
Hi! I'm not sure if I'm doing it right, so feel free to correct me.

feat(presetWind4): support `bg-size-[<value>]`

---

docs/integrations/eslint.md

docs(eslint): add doc for @unocss/order rule options

---

packages-presets/preset-wind4/src/preflights/reset.ts
test/assets/output/preset-wind4-reset.css

Synchronize updates from https://github.com/tailwindlabs/tailwindcss/blob/main/packages/tailwindcss/preflight.css

feat(preset-wind4): update reset css in preset-wind4

---

playground/src/auto-imports.d.ts
playground/vite-plugin-import-map.ts
playground/vite.config.ts
pnpm-lock.yaml

fix: #4850 
preview: https://deploy-preview-4874--unocss.netlify.app/play/

fix(playground): add import map plugin

---

packages-presets/preset-wind4/src/variants/negative.ts
test/assets/output/preset-wind4-targets.css

fix: #4851 
[preview](https://deploy-preview-4881--unocss.netlify.app/play/#html=DwBwBAxgNghgznAvAIjhGUCmBaAHtgRgAYixs0Md9jSKs9tCSy6rGaxXsBPJ089PV4cuvPi0E4xIyeIGU5XPsgB8ACwCWwAPQgVQA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAHU8aACyUAvnCxQIIOAHIuuCBLp0DSJBgAekWOmwBDLgBt4mHPiIlgpABTIqFBu9ABccADaVKiRBhJcdDB6ALQhrhgG5IhwUq7QEQa0aAZwGgC6spVUdAAW0DAJMHQRQaiGCUmpdQ1NBoUwtjAprqRwgzbD0E64pBhw9QBuGFBhE8ODTq5ZVBqyIgotUTFyokoqqv4AlLLC8owsbJw8fPzXt6cKktKBJ6h0Ei2GAiAEYAHQAJg%2BqAkaFwhVqrDALQA9Cj6CAwXUUTt2mUblRqhorkggA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA …

fix(preset-wind4): negative variant for `scale` rule

---

.github/workflows/release.yml

Related to https://github.com/e18e/ecosystem-issues/issues/201

ci: use trusted publish

---

package.json
pnpm-workspace.yaml

https://pnpm.io/catalogs#cleanupunusedcatalogs

chore: add `cleanupUnusedCatalogs` config

---

.github/workflows/release.yml

Reverts unocss/unocss#4883 (Temporarily) 
Waiting for npm repository setup, waiting for sxzz's script.

Revert "ci: use trusted publish"

---

packages-presets/transformer-directives/src/apply.ts

fix(transformer-directive): replace `$$` selector with `nomerge` utils
