unocss/unocss

- packages/preset-uno/src/rules/question-mark.ts
This PR allow use question mark as attribute via `where` when using it on framework components: for example, on `vue` will fail if using `?` as attribute.
> feat(preset-uno): add `where` to question mark

- packages/preset-uno/README.md
Passing parameters is not support
> chore: typo

- packages/preset-uno/src/rules/flex.ts
I saw it on WindiCSS documentation. Useful for attributify mode:
```html
<div flex="inline col"></div>
```
> feat: add flex-inline rule

- packages/preset-icons/README.md
This PR updates some wording and the link to the type configuration is wrong, it has been moved to its own  module.
> docs(preset-icons): update configuration entry

- packages/preset-uno/src/utils/handlers/shorthand.ts
- packages/preset-uno/src/variants/index.ts
- test/__snapshots__/preset-uno.test.ts.snap
- test/preset-uno.test.ts
I find some problems. when i use default ruels about `zIndex`,  i can't use `z-0` and `-z-1`, and i think this is a bug. but now i resolve it.
> fix(preset-uno): fix zIndex can't set negative number and 0

- packages/preset-uno/src/rules/grid.ts
- test/__snapshots__/cli.test.ts.snap
- test/__snapshots__/preset-uno.test.ts.snap
> fix(preset-uno): remove extra spaces on grid rules

- packages/preset-attributify/src/extractor.ts
- test/__snapshots__/preset-attributify.test.ts.snap
- test/preset-attributify.test.ts
I changed the regex in `extractor.ts` to support attributes that end with: `%`. 
All tests passed both before and after I updated the snapshot.
I also tested against the default unocss playground, my own html files that I use to test my own custom rules and validated the regex on regex101.com.
> feat(preset-attributify): support attributes that end with %

- packages/preset-uno/src/variants/pseudo.ts
- test/__snapshots__/preset-uno.test.ts.snap
- test/preset-uno.test.ts
I want to add `.peer` support (see [tailwind's doc](https://tailwindcss.com/docs/just-in-time-mode#sibling-selector-variants) and [source](https://github.com/tailwindlabs/tailwindcss/blob/v3.0.0-alpha.2/src/corePlugins.js#L108)). However I couldn't figure out how to add the test, so the code is only based on copy-paste from the `Group` section.
> feat(preset-uno): add peer variant support

- packages/runtime/src/index.ts
With mutation observer attached to `html`, update on the the style container `el` will recursively re-trigger the MO.
> fix(runtime): recursive updateStyle

- packages/core/src/generator/index.ts
- packages/core/src/types.ts
- packages/core/src/utils/helpers.ts
- packages/preset-uno/src/rules/transform.ts
- packages/preset-uno/src/variants/misc.ts
- test/__snapshots__/preset-attributify.test.ts.snap
- test/__snapshots__/preset-uno.test.ts.snap
Another solution of #197, /cc @chu121su12
Instead of allowing match multiple rules (which will make the overriding impossible and hard to resolve when there are conflicts), this PR allow rules to return an array of css object to multiple css selectors.
```ts
rules: [
[/^scale-(\d+)$/, ([, d]) => {
return [
{ transform: 'var(--scale)' },
{ --scale: d }
]
}
]
```
Which make it generates 
```css
.scale-100 {
transform: var(--scale);
}
.scale-100 {
--scale: 100
}
```
And [Rules Merging](https://github.com/antfu/unocss#rules-merging) could merge the duplicated parts.
> feat: allow a rule to return multiple css items, close #197

- packages/preset-mini/src/utils/handlers/handlers.ts
- test/__snapshots__/preset-uno.test.ts.snap
- test/preset-uno.test.ts
Adresses #209 (part 2), as I read, for the numberless px unit. Originally I want to add all possible units to do 
```
prop: `1${unit}`
```
But I will leave this up to @antfu to decide.
>  feat(preset-mini): numberless unit (px)

- packages/preset-wind/src/rules/background.ts
- bg-cover mean `background-size:cover`
More info:
- [background-size | MDN](https://developer.mozilla.org/zh-CN/docs/Web/CSS/background-size)
- [background-size | windicss](https://windicss.org/utilities/backgrounds.html#background-size)
> fix(preset-wind): bg-cover should be background-size

- packages/preset-mini/src/rules/typography.ts
- test/__snapshots__/preset-uno.test.ts.snap
- test/preset-uno.test.ts
- Ignore `line-height` when not themed (should be breaking if one's expecting line-height of 1 is set on this rule)
- Allow matching wildcard. Due to rule order, color will be matched first, so the default rule for unknown `text-[value]` is `color: value`
Related: #202
> feat(preset-mini): new text-[sizes] behaviour

- packages/preset-mini/src/rules/typography.ts
Rule to reliably target `font-size` alone
Alternative of #224
> feat(preset-mini): text-size for font-size-var

- packages/preset-wind/src/rules/animation.ts
- playground/src/defaults.ts
- test/__snapshots__/preset-uno.test.ts.snap
- test/preset-uno.test.ts
Added missing tailwind `pulse` and `bounce`, `tw-pulse` and `tw-bounce` respectively, `spin` and `ping` was already there.
closes #241
> feat(preset-wind): add `tailwind` missing animations

- README.md
- test/fixtures/sveltekit/package.json
- test/fixtures/sveltekit/svelte.config.js
- test/fixtures/vite-svelte/package.json
- test/fixtures/vite-svelte/src/App.svelte
- test/fixtures/vite-svelte/vite.config.js
There is some typo on the name, it is `extractorSvelte` not `svelteExtractor`.
This PR only updates the `fixtures` and the installation section on root `README.md`.
/cc @dominikg
> docs: svelte extractor fixtures and docs

- packages/cli/src/index.ts
@userquin Suggested solution instead of your PR https://github.com/antfu/unocss/pull/273.
With this, we can omit relying on `reset` at all.
> fix(cli): dimmed colors on white bg

- packages/plugins-common/constants.ts
- packages/plugins-common/context.ts
- packages/preset-mini/src/variants/default.ts
- packages/preset-mini/src/variants/pseudo.ts
- packages/vite/src/index.ts
- packages/vite/src/modes/shadow-dom.ts
- packages/vite/src/types.ts
- test/fixtures/vite-lit/.gitignore
- test/fixtures/vite-lit/.npmrc
- test/fixtures/vite-lit/index.html
- test/fixtures/vite-lit/package.json
- test/fixtures/vite-lit/src/my-another-element.ts
- test/fixtures/vite-lit/src/my-collision-element.ts
- test/fixtures/vite-lit/src/my-element.ts
- test/fixtures/vite-lit/src/vite-env.d.ts
- test/fixtures/vite-lit/tsconfig.json
- test/fixtures/vite-lit/vite.config.ts
we need to add some documentation, the plugin just replace the `@unocss-import` with the generated css
supersedes #222 (`shadow-dom` part)
closes #169
> feat: add `shadow-dom` support

- packages/preset-mini/src/variants/default.ts
- packages/preset-mini/src/variants/pseudo.ts
- test/__snapshots__/preset-mini.test.ts.snap
- test/preset-mini-targets.ts
Added support for `:is()`, `:where()`, and `:has()` pseudo.
https://caniuse.com/?search=has
https://github.com/antfu/unocss/pull/268#discussion_r770535131
`:has()` has additional syntax with its relative selector, but using `part` syntax, I think this could be worked out.
https://github.com/antfu/unocss/pull/281#issuecomment-997423810
> feat(preset-mini): pseudo class functions

- packages/preset-mini/src/rules/flex.ts
- test/__snapshots__/preset-attributify.test.ts.snap
- test/__snapshots__/preset-mini.test.ts.snap
- test/preset-mini-targets.ts
When flex was originally implemented, it was particularly inconvenient, The basis attribute often needs to be customized，Can't do the existing functions，So I am here to ！
> The picture above is the current problem
**The following is after I added new features**
**This is specifically compatible with other width types (such as the fit-content in the figure above)**
Can also support x/x writing
> feat(preset-mini): add new flex feature

- packages/core/src/config.ts
- packages/core/src/generator/index.ts
- packages/core/src/types.ts
- packages/core/src/utils/basic.ts
- packages/preset-attributify/src/extractor.ts
- packages/preset-attributify/src/index.ts
- packages/preset-attributify/src/types.ts
- packages/preset-attributify/src/variants/attributify.ts
- packages/preset-mini/src/index.ts
- packages/preset-mini/src/rules/border.ts
- packages/preset-mini/src/rules/ring.ts
- packages/preset-mini/src/rules/static.ts
- packages/preset-mini/src/variants/breakpoints.ts
- packages/preset-mini/src/variants/dark.ts
- packages/preset-mini/src/variants/default.ts
- packages/preset-mini/src/variants/pseudo.ts
- packages/preset-wind/src/index.ts
- packages/preset-wind/src/variants/dark.ts
- test/preset-attributify.test.ts
PR is for #303.
Two commits. The first one refactor core to merge presets options and prepare it as part of `context` variable in callback. This in consequece also need refactors on the related presets.
The second commit is an example use on border and ring, due to heavy use of css variable on them.
The drawback with this feature is most static rules that use css variable will get converted to regex with exact match to get the prefix option in the callback.
> feat!: change second arguement of variants to context

- packages/preset-mini/src/rules/grid.ts
- test/__snapshots__/preset-mini.test.ts.snap
- test/preset-mini-targets.ts
Closes #324.
Reorder & update rules; update test.
> fix(preset-mini)!: grid's bracket syntax now use `_` instead of `,` as separator

- packages/core/src/utils/basic.ts
- packages/preset-mini/src/index.ts
- packages/preset-mini/src/rules/border.ts
- packages/preset-mini/src/rules/ring.ts
- packages/preset-mini/src/rules/static.ts
- packages/preset-wind/src/index.ts
Reverts 2nd commit of #321:
https://github.com/antfu/unocss/pull/321/commits/da64b953d8d30630fa1f7318d1b8620a51f2760a
> fix(preset-mini)!: revert initial support for css variable prefix

- packages/preset-mini/src/rules/shadow.ts
- packages/preset-mini/src/theme/misc.ts
- test/__snapshots__/cli.test.ts.snap
- test/__snapshots__/preset-mini.test.ts.snap
- test/preset-mini-targets.ts
Turned out you can do css `inset` also as variable.
The `inner` keyword is preserved for compatiblity.
https://deploy-preview-340--ecstatic-mestorf-2e8afd.netlify.app/?html=DwEwlgbgBARg5gWgO4AswBcCmUsA90IwA2AhgMYDWUKCAZgK5FFS1Ga4tu4JkD2zAK3oBndGFoBPHpgB2WAE5QMmALbDpczIrgkADggAsAPgBQUKKEhR9ARgNRhKEiF5IEuIkYACwAPTgIU3NLaFt7R2dXd2YIlzcwGWFMdG8-ANM0yCMgA
> feat(preset-mini): shadow-inset rule

- packages/core/src/generator/index.ts
- packages/core/src/types.ts
- test/__snapshots__/order.test.ts.snap
- test/order.test.ts
Addresses https://github.com/antfu/unocss/issues/70 for the feature, not for the preset.
> feat(core): variant ordering

- packages/preset-mini/src/utils/variants.ts
- packages/preset-mini/src/variants/dark.ts
- packages/preset-mini/src/variants/prints.ts
- packages/preset-wind/src/variants/dark.ts
I'm adding variants to match those that are in tailwind, and parent with @media has 2 more uses: portrait/landscape and motion reduce.
> refactor(preset-mini): add variantParentMatcher utility

- packages/preset-mini/src/variants/default.ts
- packages/preset-mini/src/variants/misc.ts
- packages/preset-wind/src/variants/default.ts
- packages/preset-wind/src/variants/index.ts
- packages/preset-wind/src/variants/misc.ts
The rules are in `preset-wind` but the variant is in `preset-mini`.
> refactor(preset-wind): move space & divide variant into wind

- packages/preset-wind/src/rules/background.ts
- packages/preset-wind/src/rules/behaviors.ts
- packages/preset-wind/src/rules/default.ts
- test/__snapshots__/preset-wind.test.ts.snap
- test/preset-wind-targets.ts
`decoration-slice` and `decoration-clone` are removed in favor of `box-decoration-slice` and `box-decoration-clone`
https://tailwindcss.com/docs/upgrade-guide#decoration-clone-slice
> refactor(preset-wind): reorder background rules

- packages/inspector/client/components/CodeMirror.vue
- packages/inspector/client/components/ModuleInfo.vue
- packages/inspector/node/index.ts
- packages/vite/src/modes/global/dev.ts
- test/fixtures/vite-solid/vite.config.ts
@antfu This PR also fix a problem with the inspector, if you want to include it on a separate PR just request me.
Now the inspector works on all fixtures: `svelte`, `sveltekit`, `react`, `preact`, and `solid`, for `lit` I need to review it (`vite-plugin-inspect` is working).
closes #254
closes #369
> fix(mode): use vite `base` on `global` mode

- packages/preset-mini/src/rules/size.ts
- test/__snapshots__/preset-mini.test.ts.snap
- test/preset-mini-targets.ts
[Follows tailwind keywords.](https://tailwindcss.com/docs/aspect-ratio)
Should the keyword moved to `preset-wind`?
> feat(preset-mini): add aspect ratio rule keywords

- packages/preset-mini/src/rules/align.ts
- packages/preset-mini/src/rules/behaviors.ts
- packages/preset-mini/src/rules/decoration.ts
- packages/preset-mini/src/rules/layout.ts
- packages/preset-mini/src/rules/static.ts
- test/__snapshots__/preset-mini.test.ts.snap
- test/preset-mini-targets.ts
- add `sub` & `super` to vertical align
- add `hidden` to outline
- add `auto` to will-change
- add `overline` decoration
- update `text-decoration` to `text-decoration-line`
- add `clip` to overflow values
- change/fix `break-words` from `break-word`
> feat(preset-mini): add/update missing rules

- packages/preset-mini/src/rules/size.ts
- packages/preset-mini/src/theme/size.ts
- move `min` & `max` from theme to rule. Theme is still prioritized, so overriding the theme will still have effect.
- add `[size]-fit` for `fit-content`
- refactor aspect ratio
> refactor(preset-mini): update size & aspect ratio

- packages/preset-wind/src/rules/behaviors.ts
- packages/preset-wind/src/rules/default.ts
- packages/preset-wind/src/rules/scrolls.ts
- packages/preset-wind/src/rules/spacing.ts
- packages/preset-wind/src/rules/static.ts
- test/__snapshots__/preset-wind.test.ts.snap
- test/preset-wind-targets.ts
- merge accent opacity and accent colors exports
- merge caret opacity and caret colors exports
- change/fix `snap-both` from `snap-base`
- split `space-[xy]-reverse` rule
- add `isolation-auto`
- add support for expanded object position keywords
> feat(preset-wind): add/update missing rules

- README.md
- packages/vite/README.md
- packages/vite/src/index.ts
- packages/vite/src/modes/svelte-scoped.ts
- packages/vite/src/types.ts
This works for building css scoped svelte components. It is an almost direct copy of the vue scoped mode.
> feat(svelte-scoped): scoped css mode for svelte

- packages/core/src/generator/index.ts
- packages/core/src/utils/helpers.ts
- packages/preset-mini/src/rules/transform.ts
- test/__snapshots__/postprocess.test.ts.snap
- test/__snapshots__/preset-attributify.test.ts.snap
- test/__snapshots__/preset-mini.test.ts.snap
- test/__snapshots__/shortcuts.test.ts.snap
- test/shortcuts.test.ts
Please read #411 and #421 first.
In short, to align with v3 tailwind.
Previously:
```css
.scale-2 {
/* base transform styles */
transform: var() /* combined vars. */;
}
.scale-2 {
--un-scale: 2;
}
```
now:
```css
.scale-2 {
/* base transform styles */
--un-transform: var() /* combined vars. */;
}
.scale-2 {
--un-scale: 2;
transform: var(--un-transform);
}
```
> feat(preset-mini)!: update transform rule

- packages/preset-mini/src/rules/typography.ts
- test/__snapshots__/preset-mini.test.ts.snap
- test/preset-mini-targets.ts
Related: #223, #218. 
Since font-size can now be targetted via `text-size-x`, the old behavior prioritizing theme for `text-x` can be restored.
> refactor(preset-mini): text-size prioritize theme

- packages/preset-wind/src/rules/filters.ts
- packages/preset-wind/src/rules/scrolls.ts
- packages/preset-wind/src/rules/touch-actions.ts
- packages/preset-wind/src/rules/typography.ts
- test/__snapshots__/preset-wind.test.ts.snap
update from `CONTROL_BYPASS_PSEUDO_CLASS` to use `CONTROL_SHORTCUT_NO_MERGE`
- filter
- backdrop-filter
- scroll-snap-type
- touch-action
- font-variant-numeric
> refactor(preset-wind)!: update rules to use `CONTROL_SHORTCUT_NO_MERGE`

- packages/preset-mini/src/rules/transform.ts
- test/__snapshots__/preset-mini.test.ts.snap
- test/preset-mini-targets.ts
If this should be on `preset-wind`, I propose moving `preserve-3d` and `preserve-flat` too.
> feat(preset-mini): add perspective utilities

- packages/preset-mini/src/rules/typography.ts
- packages/preset-mini/src/theme/font.ts
- packages/preset-mini/src/theme/types.ts
- test/__snapshots__/preset-mini.test.ts.snap
- test/preset-mini-targets.ts
The logic for #450, but for `text-shadow`; also without inset processing.
> feat(preset-mini): add text-shadow shadow color & opacity

- packages/preset-mini/src/rules/shadow.ts
- packages/preset-mini/src/theme/misc.ts
- test/__snapshots__/cli.test.ts.snap
- test/__snapshots__/preset-mini.test.ts.snap
- test/preset-mini-targets.ts
This PR aligns the shadow color behavior to tailwind: colored shadow get full opacity by default. Tw's shadow actually parses the shadow theme and uses SHORTCUT_NO_MERGE-like rule, which is not the case with this implementation.
Without parsing, the usable colors are limited to only hex colors, due to shadow colors dependant on rgb array.
See alternative PR #450 with simple parsing support.
> feat(preset-mini): add colored shadow opacity

- packages/preset-mini/src/rules/ring.ts
- packages/preset-mini/src/rules/shadow.ts
- packages/preset-mini/src/theme/misc.ts
- packages/preset-mini/src/theme/types.ts
- test/__snapshots__/cli.test.ts.snap
- test/__snapshots__/preset-mini.test.ts.snap
- test/preset-mini-targets.ts
Since #452 & #453 is using the same logic, I'll retry #450 here.
- The inset shadow css variable that was previously auto-generated are now kept.
- The color value must use **NO** space. Ex:
```css
'sm': '0 1px 2px 0 rgba(0,0,0,0.05)',
'hex': '0 1px 2px 0 #2228',
```
> refactor(preset-mini): update colored shadow rule

- packages/core/src/generator/index.ts
- packages/core/src/types.ts
- test/__snapshots__/selector-no-merge.test.ts.snap
- test/selector-no-merge.test.ts
See https://www.w3.org/TR/selectors-3/#grouping
Mostly for safely using prefixed pseudo element (via variant).
> feat(core): `noMerge` rule meta

- packages/preset-mini/src/variants/pseudo.ts
Was removed in https://github.com/antfu/unocss/pull/422 and https://github.com/antfu/unocss/pull/429
> refactor(preset-mini): remove `CONTROL_BYPASS_PSEUDO_CLASS`

- packages/preset-mini/src/rules/color.ts
- packages/preset-mini/src/rules/shadow.ts
- packages/preset-wind/src/rules/filters.ts
- packages/preset-wind/src/rules/placeholder.ts
- packages/preset-wind/src/variants/placeholder.ts
This PR removes all `handler.cssvar` in all `x-opacity` rules because any other opacity rules don't have it. Also the `x-opacity` modifier is aleady producing css variable.
The standalone `opacity-x` is not modified and still have `cssvar` support.
Alternatively, we should add `cssvar` to all other rules that don't have it.
> refactor(preset-mini,preset-wind)!: remove cssvar in color opacity modifier

- packages/inspector/client/auto-imports.d.ts
- packages/inspector/client/components/CodeMirror.vue
- packages/inspector/client/components/ModuleTreeNode.vue
- packages/inspector/client/main.css
- playground/src/auto-imports.d.ts
- playground/src/components/Editor.vue
- playground/src/main.css
This PR fixes:
- code mirror scrolls on playground editor visible: right now the horizontal scrolls are on the overflow
- on inspector now the `ModuleTreeNode` will use `ws-nowrap` instead `truncate`: see screenshots bellow opening the inspector when running the playground
- scrolls colors and bottom right corner background color on inspector and playground
- vertical split panes divider will now have left 0 and horizontal ones top 0 to allow use the scroll with mouse: on inspector and on playgorund
closes #493 
Inspector using `ws-nowrap`: 
Inspector using `truncate` (since the text is truncated then the width of the div will be the container one and so the horizontal scroll will disappear):
> feat(inspector + playground): all scrolls visible + colors

- packages/preset-mini/src/rules/transform.ts
Alternatively, assign both skew x & y on `skew-n` without direction.
> fix(preset-mini): remove `skew` without direction

- packages/preset-mini/src/rules/variables.ts
- packages/preset-mini/src/utils/handlers/handlers.ts
- packages/preset-wind/src/rules/variables.ts
- test/__snapshots__/preset-mini.test.ts.snap
- test/preset-mini-targets.ts
- test/preset-uno.test.ts
Addresses #534. Since this is unavoidable with the built-in extractor, escape the variable name instead.
> fix(preset-mini,preset-wind): escape css custom properties

- packages/preset-mini/src/variants/pseudo.ts
- test/__snapshots__/preset-mini.test.ts.snap
- test/preset-mini-targets.ts
Use case for this is for parent-hover to nested tables' row.
See rationale here https://github.com/tailwindlabs/tailwindcss/pull/271
> feat(preset-mini): add parent-x as group-x with direct descendant

- packages/core/src/generator/index.ts
- packages/core/src/types.ts
- packages/preset-mini/src/variants/default.ts
- packages/preset-mini/src/variants/misc.ts
- test/__snapshots__/preset-mini.test.ts.snap
- test/preset-mini-targets.ts
Just like parent, this allows layer to be applied by variant.
With this we can simplify the `x-none` rules integrating it to its parent thus reducing rule count.
> feat(core): add option to override layer from variant

- packages/runtime/src/index.ts
Two uses:
- to make the default extraction (`extractAll`) preventable
- to be able to config the runtime from one place. ex:
```js
window.__unocss = { runtime: {
ready({ extract }) {
fetch(...)
.then(r => r.text)
.then(t => extract(t))
```
instead of 
```html
<script src="./uno.global.js"></script>
<script>
const { extract } = window.__unocss_runtime;
fetch(...)
.then(r => r.text)
.then(t => extract(t))
</script>
> feat(runtime): fire a callback when the runtime is ready

- packages/preset-mini/src/rules/decoration.ts
- test/__snapshots__/preset-mini.test.ts.snap
- test/preset-mini-targets.ts
Alternatively, add this static rule:
```ts
['decoration-overline', { 'text-decoration-line': 'overline' }],
```
> refactor(preset-mini): merge decoration rules

- packages/preset-mini/src/rules/position.ts
- packages/preset-mini/src/rules/transition.ts
- packages/preset-wind/src/rules/animation.ts
- packages/preset-wind/src/rules/filters.ts
- test/__snapshots__/preset-mini.test.ts.snap
- test/__snapshots__/preset-wind.test.ts.snap
With addition of layer variant (#571), some of the workaround to prioritize rule order can be removed.
preset-mini:
- merge `z-auto`
- merge `transition-property-none` & `property-none`
preset-wind:
- merge `animate-fill-mode-none` (`animate-none` will still hold the precedence due to rule order)
- merge `animate-direction-normal`
- merge `filter-x-none` & `backdrop-x-none`
> refactor(preset-mini,preset-wind): merge rules

- packages/preset-mini/src/rules/static.ts
Besides this being handy, it allows `presetAttributify` users to work around `<div hidden>` colliding with https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden
> feat(preset-mini): use cssvar for `display-*` utilities

- packages/core/src/types.ts
- packages/preset-mini/src/rules/border.ts
- packages/preset-mini/src/rules/shadow.ts
- packages/preset-mini/src/rules/typography.ts
- packages/preset-mini/src/utils/colors.ts
- packages/preset-mini/src/utils/utilities.ts
- packages/preset-wind/src/rules/background.ts
- packages/preset-wind/src/rules/filters.ts
- test/__snapshots__/preset-attributify.test.ts.snap
- test/__snapshots__/preset-mini.test.ts.snap
- test/__snapshots__/preset-uno.test.ts.snap
- test/__snapshots__/preset-wind.test.ts.snap
- test/color.test.ts
- test/preset-uno.test.ts
- update color parsers
- `ParsedColorValue` no longer return color's alpha, only parsed opacity
- color/opacity shorthand (`c-red-100/10`) no longer generate opacity variable
- parse shadows' color theme value
- with the new parser, the shadow color values are no longer limited to unspaced rgb as per #459
- add custom color test case
> feat(preset-mini,preset-wind): replace hex color parser

- packages/preset-uno/src/index.ts
- packages/preset-uno/src/variants/mix.ts
- packages/preset-wind/src/index.ts
- packages/preset-wind/src/shortcuts.ts
- packages/preset-wind/src/variants/default.ts
- packages/preset-wind/src/variants/index.ts
- test/__snapshots__/preset-uno.test.ts.snap
- test/preset-uno.test.ts
Alternative for https://github.com/antfu/unocss/pull/570 by adding to preset-uno instead
It's breaking now since `presetUno` is no longer alias for `presetWind`. See https://github.com/antfu/unocss/pull/225#issuecomment-990499591
> feat(preset-uno): sass mix color function

- packages/core/src/generator/index.ts
- packages/core/src/types.ts
- packages/preset-mini/src/variants/pseudo.ts
- test/__snapshots__/order.test.ts.snap
- test/__snapshots__/preset-mini.test.ts.snap
- test/order.test.ts
- test/preset-mini-targets.ts
Building on top of #586, this PR prioritizes active pseudo (2nd commit: https://github.com/unocss/unocss/commit/00f5fe3660732dae389a89a1f130ba86d370e35e) so it is applied after `hover`. However, I'm not to sure how to best addresss this issue, since this introduces a non-default sort (see also #70). Maybe add a standalone dummy variant in preset-wind/uno to set the sort?
Something like:
```ts
export const activePseudoSortMarker: VariantFunction = (input: string) => {
const match = input.match(^/active[:-]/)
if (match) {
return {
matcher: input, // do nothing
selector: s => s, // do nothing
sort: 1, // <--- only set this
}
}
}
```
This PR would close #583.
> feat(preset-mini): prioritize `active` pseudo

- packages/preset-mini/src/rules/size.ts
- packages/preset-mini/src/theme/default.ts
- packages/preset-mini/src/theme/misc.ts
- packages/preset-mini/src/theme/types.ts
- test/__snapshots__/preset-mini.test.ts.snap
- test/preset-mini-targets.ts
> feat(preset-mini): add `h-screen-<breakpoint>` rule

- packages/runtime/src/cdn/full.ts
Currently included presets are 
- attributify
- uno
- typography
I tried adding web-fonts but the file size jumped way high. Let me know if it should be added anyway
> feat(runtime): add `full` runtime

- packages/preset-mini/src/variants/default.ts
- packages/preset-mini/src/variants/misc.ts
- test/__snapshots__/preset-mini.test.ts.snap
- test/__snapshots__/scope.test.ts.snap
- test/preset-mini-targets.ts
- test/scope.test.ts
Compared to the combinators, this variant includes the `$$` control and automatically set the match as class.
> feat(preset-mini): add generic scope class variant

- packages/preset-mini/src/utils/colors.ts
- packages/preset-mini/src/utils/utilities.ts
- test/color.test.ts
This PR makes `parseHexColor` (consequently, `parseCssColor`) requires the `#` prefix for hex colors.
> fix(preset-mini): strict hex color string

- packages/preset-mini/src/utils/colors.ts
- test/__snapshots__/preset-uno.test.ts.snap
- test/color.test.ts
- test/preset-uno.test.ts
This PR adds support to use 1 value with the default color functions. Currently when using the css-approved color functions, only color with 3 components are accepted. Supporting 1 component allows possible use of single `var(x)` for the color value; *although* the component value is not validated.
Closes #623.
> feat(preset-mini): support 1-value color

- packages/preset-wind/build.config.ts
- tsconfig.json
This PR fix the build problem on windows
> fix: add missing `preset-wind` to typescript config file

- packages/unocss/src/index.ts
Looks like presetWind accidentally wasn't exported in unocss package
> fix: add presetWind to unocss package

- packages/transformer-directives/src/index.ts
- Provide transformer directives enforce option.
- Set default enforce to `undefined`, that user can apply their own css preprocessor.
> feat(directives)!: transformer enforce options

- packages/preset-mini/src/variants/breakpoints.ts
- test/__snapshots__/preset-mini.test.ts.snap
- Fix `lt:${breakpoint}` and `at:${breakpoint}` to close #707
- [windicss/tools#increaseWithUnit](https://github.com/windicss/windicss/blob/4ec1027483bf9e3c7e6bf4f3397912b8f7aec243/src/utils/tools.ts#L342-L360)
> fix(preset-mini): breakpoint in max-width issue

- packages/preset-wind/build.config.ts
Released `unbuild 0.7.0` a few days ago.
Related to https://github.com/unocss/unocss/pull/659, just check the errors on windows on that PR.
/cc @hannoeru I can now build the project again on Windows :raised_hands:
> fix: windows problem building `preset-wind`

- playground/vite.config.ts
Rollup could not parsing file path in windows.
`PS D:\projects\GitHub\unocss\playground> nr build
> playground@0.0.0 build D:\projects\GitHub\unocss\playground
> vite build
vite v2.8.6 building for production...
✓ 393 modules transformed.
rendering chunks (13)...[vite:build-html] The "fileName" or "name" properties of emitted files must be strings that are neither absolute nor relative paths, received "../../../../../D:\projects\GitHub\unocss\playground\index.html".
error during build:
Error: The "fileName" or "name" properties of emitted files must be strings that are neither absolute nor relative paths, received "../../../../../D:\projects\GitHub\unocss\playground\index.html".
at error (D:\projects\GitHub\unocss\node_modules\.pnpm\rollup@2.70.1\node_modules\rollup\dist\shared\rollup.js:1 …
> fix: input file path(windows)

- packages/vscode/src/index.ts
If `unocss.root` is a relative path, it doesn't work.
> fix(vscode): resolve root config path

- packages/preset-attributify/src/extractor.ts
- test/__snapshots__/preset-attributify.test.ts.snap
- test/preset-attributify.test.ts
Modified based on #746  PR
Can identify `!attributify`
eg `!flex`
> fix(attributify): allow important-only utils

- README.md
```ts
// Module '"unocss"' has no exported member 'escape'
import { escape as e } from 'unocss' 
```
it should be `import { escapeSelector as e } from 'unocss'` ?
> docs: change escape to escapeSelector

- packages/preset-icons/src/utils.ts
Since deno std node polyfill added `stdout` support in https://deno.land/std@0.131.0/node/process.ts#L480, the `isNode` will be `true` when import this preset from esm.sh. But the polyfill also added deno version in `process.versions` in https://deno.land/std@0.131.0/node/_process/process.ts#L99, so we can hack it with `!process.versions.deno`
> fix(preset-icons): support deno std node polyfill

- README.md
- packages/core/src/generator/index.ts
- test/__snapshots__/preset-attributify.test.ts.snap
- test/preset-attributify.test.ts
we can use `toEscapedSelector` directly  to ensure that [Full Controlled Rules](https://github.com/userquin/unocss#full-controlled-rules) is compatible with [Attributify Mode](https://github.com/antfu/unocss/tree/main/packages/preset-attributify/), avoiding others to implement the toEscapedSelector function again
> chore(core): export toEscapedSelector

- packages/runtime/src/index.ts
Current observer doesn't catch `addedNodes`, so it doesn't work when nodes are added, I have no idea why.
> fix(runtime): fix observer with childList mutation

- packages/runtime/README.md
- packages/runtime/play/index.html
- packages/runtime/src/index.ts
Add a `un-cloak` attribute to hide an element until it's styles are ready.
Note: dynamic injected elements will still suffer from FOUC, haven't figured out a way to prevent this.
> feat(runtime): un-cloak to prevent FOUC

- packages/core/src/generator/index.ts
- test/__snapshots__/layer.test.ts.snap
- test/__snapshots__/shortcuts.test.ts.snap
- test/shortcuts.test.ts
fix [full-controlled-rules](https://github.com/unocss/unocss#full-controlled-rules) works with shortcut, like animate
but i failed in https://github.com/unocss/unocss/blob/main/test/__snapshots__/layer.test.ts.snap
```diff
// Vitest Snapshot v1
exports[`layers > static 1`] = `
"/* layer: shortcuts */
.abc{name:bar1;name:bar2;name:4;}
/* layer: a */
.a{name:bar1;}
/* layer: b */
.b{name:bar2;}
/* layer: c */
.c5{name:5;}
/* layer: d */
/* RAW 4 */
+ /* RAW 3 */
/* layer: s */
.abcd{name:bar1;name:bar2;name:2;}"
`;
```
I am not sure if this comment(/* RAW 3 */) has to be removed,
> fix(shortcuts): full-controlled-rules works with shortcuts

- packages/preset-mini/src/rules/spacing.ts
- test/__snapshots__/preset-mini.test.ts.snap
- test/autocomplete.test.ts
- test/preset-mini-targets.ts
The padding and margin spacing are [written here](https://github.com/unocss/unocss/blob/main/packages/preset-mini/src/rules/spacing.ts), but  the `+` is used in the second capture group of the rule,it can never be empty
This means that [the DEFAULT in spacing](https://github.com/unocss/unocss/blob/main/packages/preset-mini/src/theme/misc.ts#L18) cannot be matched
I replaced the `+` with the `*`
before:
after:
> fix(spacing): fix DEFAULT spacing mismatch

- packages/core/src/generator/index.ts
- packages/preset-mini/src/rules/size.ts
- packages/preset-mini/src/utils/utilities.ts
- packages/preset-mini/src/variants/breakpoints.ts
- packages/preset-wind/src/rules/container.ts
- test/transformer-directives.test.ts
- tsconfig.json
This PR fix the breakpoints from user config theme:
- ~~`generator`: add resolve breakpoints utilities~~ => moved to `src/utils/utilities` on `preset-mini` 
- `preset-mini`: size and breakpoints
- `preset-wind`: container
- test: transformer-directive.test.ts (check last test `custom breakpoints` with custom generator)
- add `@unocss/preset-typography` to root `tsconfig.json`
**This PR doesn't solve the order problem, maybe we should document it or try to fix it later.**
closes #778
> fix: user config theme breakpoints order

- packages/inspector/client/components/CodeMirror.vue
Before:
Occasionally, some matched rules not highlight
> fix(playground):adjust matched time interval

- packages/core/src/utils/variantGroup.ts
- packages/inspector/client/components/CodeMirror.vue
- packages/inspector/client/composables/codemirror.ts
- playground/src/components/Editor.vue
- playground/src/logics/url.ts
- test/variant-group.test.ts
- added support for the tilde syntax in attributify mode to variant groups 
before: 
after:
- playground: show transformed code
- reactified CodeMirror options to allow toggling read-only mode
> feat(variantGroup): support tilde syntax

- packages/vite/src/transformers.ts
With this PR, you should be able to use variant groups in index.html. But apparently, you would still have to explicitly include `.html` files in your unocss config. perhaps `.html` files should be included by default?
> feat(variantGroup): transform index.html

- packages/cli/bin/unocss.cjs
- packages/cli/bin/unocss.mjs
- packages/cli/package.json
This is a proposal. I think by now it's safe to use ESM, since the latest LTS version is 16+ anyway.
> refactor(cli): migrate bin to ESM

- packages/cli/build.config.ts
Forgot to remove the now unneeded `unbuild` config lines.
> refactor(cli): no need to emit CJS dist files

- packages/preset-attributify/src/jsx.ts
Solves #867.
Although it works perfectly with SolidJS, it might not work with other frameworks (the change doesn't seem to be breaking though). Definitely needs a review.
> fix(attributify): add support for boolean attributes

- packages/vite/src/modes/global/build.ts
- packages/vite/src/types.ts
in development mode, __uno.css can be processed by `vite:css`, but not in production
add `usePostcss` flag to make it works, so we can use `postcss` to process the generated css
```ts
// vite.config.ts
Unocss({
usePostcss: true
}),
```
> feat(vite): support unocss can be processed by vite:css

- packages/preset-mini/src/variants/default.ts
- packages/preset-mini/src/variants/pseudo.ts
- test/__snapshots__/preset-mini.test.ts.snap
- test/assets/preset-mini-targets.ts
- test/autocomplete.test.ts
- test/preset-uno.test.ts
Fix `first-line-x` and `first-letter-x` pseudo elements shadowed by `first-x` pseudo class utility, 
Note that combining pseudo class & pseudo elements now allows multiple pseudo elements. Using `before:before:m2` thus generate `.m2::before::before`
Closes #885
> fix(preset-mini): fix first-line-x and first-letter-x pseudo

- README.md
Instead using just `Vite` refer it by its package name `@unocss/vite`
> docs: update `Vite` entry

- interactive/app.vue
> docs: fix display width

- interactive/app.vue
- interactive/components/DarkToggle.vue
- interactive/components/Search.vue
- interactive/components/TheNav.vue
- interactive/public/robots.txt
- interactive/scripts/prepare.ts
This PR fixes some a11y and SEO problems:
- added `robots.txt`
- fix buttons without text
- fix links without description
- fix wrong nested html elements
- added lang and description to html
- focus search input on load: also focus it once clear buttons clicked
Before merging this PR, please check the following change to `prepare.ts` module: we cannot copy symliks on Windows, so I've added `dereference: true` to all `fs.copy` options but only for Windows, I've configured this option as `undefined` for non Windows environments.
Before applying this PR:
and on local with changes applied:
> feat(interactive): add a11y and SEO improvements

- LICENSE
- README.md
- packages/autocomplete/README.md
- packages/cli/LICENSE
- packages/cli/README.md
- packages/core/README.md
- packages/extractor-pug/README.md
- packages/inspector/README.md
- packages/nuxt/README.md
- packages/preset-attributify/README.md
- packages/preset-icons/README.md
- packages/preset-mini/README.md
- packages/preset-typography/LICENSE
- packages/preset-uno/README.md
- packages/preset-web-fonts/README.md
- packages/preset-wind/README.md
- packages/runtime/README.md
- packages/transformer-directives/LICENSE
- packages/transformer-variant-group/README.md
- packages/vite/README.md
- packages/vscode/README.md
- packages/webpack/README.md
This PR includes: 
- updates all licences to use a common layout:
```txt
MIT License &copy; 20XY-PRESENT [name/gh_username](https://github.com/gh_username)
```
- updates all `LICENSE` files to include `-PRESENT` as the year suffix
- added webpack license on package README
> docs: update all readme licenses and licenses

- packages/webpack/src/index.ts
Used in webpack, the slash seems alwas **to right**, but **entries**'s slash key alway **to left**, so **layer**'s value always null here
https://github.com/unocss/unocss/blob/0f24d04eca3e45aac75f8a2c5d4ac980824a7803/packages/webpack/src/index.ts#L104-L116
> chore(webpack): convert to left slash

- packages/reset/tailwind.css
I just noticed there's new flex reset here. Should the `.dark` block be removed in the tailwind reset?
> feat(reset): update from tailwind reset

- packages/core/src/utils/escape.ts
- test/__snapshots__/preset-mini.test.ts.snap
- test/__snapshots__/preset-wind.test.ts.snap
This PR updates the escape char of `,` to be `\,` instead of `\2c `. I suggest this change because using uno with svelte scoping breaks. Svelte removes unused styles (if scoped), and does not recognise the `\2c ` as the same class in the markup.
I tested the browser support (using online test grids) for the example of `grid-cols-[repeat(6,1fr)]`
**Desktop** (https://github.com/alexanderniebuhr/lambda-test/blob/main/TES100201621651772638589250.pdf)
- Chrome >59 ✅ 
- Firefox >58 ✅ 
- IE 11 ❌ 
- Safari >12 ✅ 
**Mobile** (https://github.com/alexanderniebuhr/lambda-test/blob/main/TES100201621651774781769360.pdf)
- iPhones
- multiple Android Phones
Everything seems to work, except IE. But the browser does not support grid, so I expect that. However IE should work with supported rules with `,` …
> fix: escape `,` properly

- examples/vue-cli/vue.config.js
- packages/shared-integration/src/layers.ts
- packages/webpack/src/index.ts
webpack hmr not works because of the css placeholder text is not changed, this pr added the content hash value to prepend the layer placeholder.
because the webpack source code string escapes the double quotes, hash content regx needs add `\\` to match the code
In webpack v5, need set `cache: false`, I don't know if there is any other better way, a small problem is that sometimes you need to typing `Ctrl + S` twice
> feat: support webpack hmr

- packages/vscode/README.md
- packages/vscode/src/index.ts
Since I'm using the wonderful [iles](https://iles.pages.dev/) static site generator and unocss vscode extension did not support loading from the `iles.config.ts` (or js) file, this PR solves it since the format for the vite configuration is the same as other config files (a `vite` property).
For the extension to work correctly, I did have to explicitly defines the presets to use, without it, it did not find utilities, maybe the default preset is not applied 🤔
> feat(vscode): support loading from iles.config file

- packages/vite/src/modes/global/build.ts
[unocss:global:build:generate] [unocss] does not found CSS placeholder in the generated chunks,
this is likely an internal bug of unocss vite plugin
If I don't import uno.css, I get this error during the build phase.
> fix(vite): emit better warning in build

- playground/src/logics/config.ts
- playground/unocss.config.client.ts
- playground/unocss.config.ts
I thought it was intentional, but found that the `presetIcons` was missing
-----------------------
And: 
In my local, i don't understand why some properties are missing in the browser, although they are correct when I debug
> docs(playground): missing icon preset

- packages/unocss/src/vite.ts
This provides proper typing of the `extendTheme` option while using a preset, for example.
> fix(vite): infer Theme type from plugin config

- packages/core/src/config.ts
The main reason is if someone wants to build a UI library / presets on top of unocss we can define the classes that will always be generated
Close #968
> feat(core): merge safelist presets from config

- playground/src/components.d.ts
- playground/src/components/Editor.vue
- playground/src/components/Preview.vue
- playground/src/main.css
1. Fixed responsive view height in mobile.
2. Calculating `<TitleBar>` height by splitpanes' height instead of `window` height. Calculating it by `window` was causing wrong height in mobile/vertical layout. Also added min-height property to the panes. Because min height of Titlebars was not updating after resizing wrapper.
3. Added another row and moved options to that row.
4. Removed a white small box on the bottom right corner.
> doc(playground): improve mobile layout

- packages/preset-attributify/src/extractor.ts
- test/preset-attributify.test.ts
Fixes #804 
I tried using Vitest's timeout feature (passing timeout as the third argument), but it didn't work for some reason.
> perf(preset-attributify): skip extracting if there is no any valid element

- packages/core/src/generator/index.ts
- test/__snapshots__/order.test.ts.snap
- test/__snapshots__/preset-mini.test.ts.snap
- test/order.test.ts
BREAKING CHANGE
Fixes #70
Fixes #814
With these changes generated CSS will match Tailwind's behaviour.
To compare: [Unocss Playground](https://unocss.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCIQIE4GsBcA5tgPYCuADgLQAWJEAptkaZVQGYkxlJUDuYAC40wAO3wAjQlQlwyDKgDYADMvQA%2BAFChIsRCgzFy1Oo2ZG2nbrwHCx%2BLHknTsDEEtUagA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWydAAW0DCxMHSh-qj6sfFJ1bX1enkwVjCJTqRwfZYD0Pa4pBhwNQBuGFDBowN99k5mqGrqAJRIQA&options=N4IgzgLgTglgxhEAuaBXApgGhNAhgOzADMB7KAW2SNwBsx0BfIA) - [Tailwind Playground](https://play.tailwindcss.com/W5qseOFQWy)
Only difference is `group-hover:dark:group-focus-within:bg-red-600`. Tailwind moving …
> fix(core): improve multiple variant sorting

- packages/core/src/types.ts
Is it intended, that preflight has no access to the `Theme` object? In that case, it would be better to just remove the `theme` in the passed-in param.
> fix(core): add missing `Theme` for `Preflight`

- packages/preset-wind/src/variants/default.ts
- packages/preset-wind/src/variants/media.ts
- test/__snapshots__/preset-wind.test.ts.snap
- test/assets/preset-wind-targets.ts
In https://github.com/tailwindlabs/tailwindcss/pull/8410, the `contrast-x` were explicitly set to be defined before `dark` variant. This PR opted--only in test--to use `layer-x` to move css the definition around.
> feat(preset-wind): add `contrast-more/less` variants

- packages/preset-mini/src/utils/handlers/handlers.ts
- packages/preset-wind/src/rules/background.ts
- test/__snapshots__/preset-wind.test.ts.snap
- test/assets/preset-wind-targets.ts
Add support for free-hand background-positions
> feat(preset-wind): update `bg-position`

- packages/preset-mini/src/variants/pseudo.ts
- test/__snapshots__/preset-mini.test.ts.snap
- test/assets/preset-mini-targets.ts
- test/preset-uno.test.ts
This variant is only available with colon `:` since using dash `-` conflict with the existing backdrop-filter rules.
Reference: https://developer.mozilla.org/en-US/docs/Web/CSS/::backdrop
> feat(preset-mini): add `backdrop:x` variant for `::backdrop` pseudo element

- packages/transformer-directives/src/index.ts
- test/transformer-directives.test.ts
> fix(directives): `theme()` breaks `@apply`

- packages/preset-mini/src/variants/misc.ts
- test/__snapshots__/preset-mini.test.ts.snap
- test/assets/preset-mini-targets.ts
- test/assets/preset-wind-targets.ts
- test/preset-mini.test.ts
Closes #1055
Even with the existing guard, the negative variant will still cause problem in other utility ([ex.: color](https://uno.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCIBGBzAtAdwAswAXAUykNwDMBXOOdAPgCgopRJZEUNq4yADyhIADghhlcg3ABZmbdh3DR4yNOlwwA9nG0AnXJji0psgAznm5gIzAA9CtZLlXNbyx59ZELgBsltYATA5OiqGQrBEQTEA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWydAAW0DCxMHSh-qj6sfFJ1bX1enkwVjCJTqRwfZYD0Pa4pBhwNQBuGFDBowN99k5mqGqyIgqN4ZFyokoqPgCUssLyjCxsnDx8-OeXRwqS0n6HqHQS6xihAEYAHQAJheqAkaFweSqrDAjQA9Aj6CAgdUEZsWmoLuUkNikEA&options=N4IgzgLgTglgxhEAuaBXApgXyA))
> fix(preset-mini): fix negative variant not accepting string theme

- packages/preset-mini/src/rules/border.ts
- packages/preset-mini/src/utils/colors.ts
- packages/preset-mini/src/utils/utilities.ts
- packages/preset-wind/src/rules/background.ts
- test/__snapshots__/preset-uno.test.ts.snap
- test/preset-uno.test.ts
This PR moves the colors' `%alpha` processing to single place.
> fix(preset-mini): refactor `colorToString`

- packages/preset-wind/src/rules/background.ts
- test/__snapshots__/preset-attributify.test.ts.snap
- test/__snapshots__/preset-wind.test.ts.snap
This PR align gradient css with tailwind, with changes:
- Extract `gradient-to` to separate property instead of inlining with `gradient-stops`
- If the incoming color is parseable, use it to set `gradient-to` but with 0 opacity.
> feat(preset-wind): refactor bg-gradient

- packages/autocomplete/src/utils.ts
- packages/vscode/src/annonation.ts
- packages/vscode/src/autocomplete.ts
- packages/vscode/src/utils.ts
- test/autocomplete-utils.test.ts
> feat(vscode): support intelligent prompt for css file

- packages/core/src/config.ts
- packages/preset-icons/src/index.ts
- packages/preset-typography/src/index.ts
- packages/preset-web-fonts/src/index.ts
Sometimes, some css have to be spliced between the internal layers. Having some space between layers may make it easier to insert another.
Alternatively it becomes ~layer naming creativity~ either carefully naming layer or overriding the order in `layers` option.
Another breaking change which is for users expecting the old layer order.
> feat(core,presets)!: add slack around layers order value

- packages/vite/src/modes/global/build.ts
> fix(vite): use outDir as key of cssPlugin to prevent parallel issue, fix #1065

- packages/core/src/generator/index.ts
- test/generate-async.test.ts
This PR reorders the logic in the `UnoGenerator.generate()` so that tokens and preflights are awaited at the same time. Originally it await the tokens first then await the preflights.
> feat(core): resolve tokens and preflights together

- packages/preset-wind/src/rules/static.ts
- test/__snapshots__/preset-wind.test.ts.snap
- test/assets/preset-wind-targets.ts
Closes #1086
Based on [`bg-x` code](https://github.com/unocss/unocss/blob/c8cd80596987bddc660e907a08ef87ee0f5c97a1/packages/preset-wind/src/rules/background.ts#L65-L66)
> feat(preset-wind): support bracket values for `object-x`

- packages/vscode/README.md
VS Code doesn't respect the `style` attribute of the icon, making it (horribly) huge. Let's set a height for it.
> chore(vscode): specify `height` for the banner icon

- packages/core/src/generator/index.ts
- packages/core/src/types.ts
- packages/core/src/utils/object.ts
- packages/preset-wind/src/rules/animation.ts
- test/__snapshots__/layer.test.ts.snap
- test/__snapshots__/order.test.ts.snap
- test/__snapshots__/preset-attributify.test.ts.snap
- test/__snapshots__/preset-mini.test.ts.snap
- test/__snapshots__/preset-wind.test.ts.snap
- test/__snapshots__/selector-no-merge.test.ts.snap
- test/__snapshots__/shortcuts.test.ts.snap
- test/order.test.ts
Closes #1092.
This PR expanded support for rule to [return string](https://github.com/unocss/unocss#full-controlled-rules) inside an array.
The (somewhat) breaking change is that string-returned value will now be sorted among the same token.
> feat(core)!: support string in rule that returns array

- packages/preset-mini/src/rules/static.ts
- test/__snapshots__/preset-attributify.test.ts.snap
- test/__snapshots__/preset-mini.test.ts.snap
- test/__snapshots__/preset-wind.test.ts.snap
- test/assets/preset-mini-targets.ts
- test/preset-attributify.test.ts
- test/preset-mini.test.ts
- test/preset-wind.test.ts
With this PR, `content-foo` is no longer works in favor of `content-[foo]`
Reasoning:
- It implicitly conflicts with `content-start`, `content-between` which are for `align-content`
- It might conflicts with suffix variants, like `content-!`
- It supported an arbitrary value after it, which would be a bit too arbitrary.
> fix(preset-mini)!: require bracket for `content-`

- examples/vite-lit/src/my-element.ts
- packages/vite/src/modes/shadow-dom.ts
> feat(shadow-dom): add `preflights` and `safelist`

- packages/shared-integration/src/layers.ts
- packages/vite/src/modes/global/build.ts
- packages/vite/src/modes/global/dev.ts
- packages/webpack/src/index.ts
Fix sometime vite will return a 404 for `/__uno.css` upon start.
Idk why, but it seems like vite's analysis process will resolve `/__uno.css` before `uno.css`.
This pr makes `/__uno.css` available even if `uno.css` haven't been resolved.
HMR on webpack is not strictly tested, it only works in nuxt sometimes.
> fix: make resolve & load order insensitive

- packages/autocomplete/src/create.ts
- packages/autocomplete/src/types.ts
- packages/core/src/types.ts
- packages/shared-integration/src/context.ts
- packages/vscode/package.json
- packages/vscode/src/annonation.ts
- packages/vscode/src/autocomplete.ts
- packages/vscode/src/contextLoader.ts
- packages/vscode/src/index.ts
- packages/vscode/src/utils.ts
- The VSCode extension now can load multiple config files according to file's path.
- Config files will be searched from file's directory to the workspace directory or what's being specified in `unocss.root`.
- Every config file will only be loaded once, every file will be searched against loaded configs first.
- The config file living in CWD will be loaded upon extension start.
- ~~Files meeting `code.includes(INCLUDE_COMMENT_IDE) || isCssId(id)` will now be resolved to default config. Should it use the "closest" config or the default one?~~
- ~~Should the config file search all the way to the root of the drive? Should it be CWD instead?~~
- ~~Should there be a command to unload all loaded contexts(aka. reload)? It definitely helps with potential loading issues (eg. when a new config …
> feat(vscode): resolve config by file path

- packages/vscode/src/contextLoader.ts
> fix(vscode): setting default presets for creating each context

- packages/vscode/src/annotation.ts
- packages/vscode/src/autocomplete.ts
- packages/vscode/src/contextLoader.ts
support prompt of autocomplete and annotation for css file as before.
cc @QiroNT
> fix(vscode): autocomplete for css

- packages/webpack/src/index.ts
Same question and work with https://github.com/unjs/unplugin/pull/129
> fix: webpack plugin's resolveId preserve the input query

- packages/core/src/extractors/split.ts
- packages/preset-mini/src/variants/default.ts
- packages/preset-mini/src/variants/misc.ts
- test/__snapshots__/preset-mini.test.ts.snap
- test/assets/preset-mini-targets.ts
Closes #1125
It feels like big breaking change removing `>` in extractor, but the tests appears not to change around this removal.
> feat(preset-mini)!: add variable variant

- packages/core/src/generator/index.ts
- packages/core/src/types.ts
- packages/preset-mini/src/utils/variants.ts
- packages/preset-mini/src/variants/dark.ts
- packages/preset-mini/src/variants/directions.ts
- packages/preset-mini/src/variants/pseudo.ts
- packages/preset-wind/src/variants/combinators.ts
- packages/preset-wind/src/variants/dark.ts
- test/__snapshots__/order.test.ts.snap
- test/__snapshots__/preset-mini.test.ts.snap
- test/__snapshots__/variant-handler.test.ts.snap
- test/assets/preset-mini-targets.ts
- test/order.test.ts
- test/selector-no-merge.test.ts
- test/variant-handler.test.ts
Follow up to #1126, this PR update the existing variants to use the introduced variant `handler()`.
Closes #1104 
This PR adds 2 extra properties on the handler. Variants that use selector sectioning (the one that uses `$$`: dark, rtl/ltr and group pseudo) are now moved into `prefix` so it can be modified selectively.
https://github.com/unocss/unocss/blob/91ea249ea583b7403bf3256f1705ae0966ab3360/packages/core/src/types.ts#L193-L204
> feat(core,presets)!: update presets to use the recursive callback

- packages/core/src/generator/index.ts
- packages/preset-mini/src/variants/breakpoints.ts
- packages/preset-mini/src/variants/media.ts
- packages/preset-mini/src/variants/misc.ts
- packages/preset-wind/src/rules/container.ts
- test/__snapshots__/preset-mini.test.ts.snap
- test/assets/preset-mini-targets.ts
This PR adds ` $$ ` control characters for `parent` in variant, later to be interpreted as separator for multiple parent.
In preparation for hover styles as described--at least--in https://github.com/tailwindlabs/tailwindcss/pull/8394, inevitably support for responsive media + hover is going to be needed. We may choose to use another prefix (ex. `fine-hover:x`) to limit breaking change against the existing `hover:x` but at least the support should be available.
> feat(core): support for multiple @ parents (@media, @supports, etc)

- packages/core/src/generator/index.ts
- packages/preset-mini/src/variants/dark.ts
- packages/preset-mini/src/variants/directions.ts
- packages/preset-mini/src/variants/pseudo.ts
- packages/preset-wind/src/variants/dark.ts
- test/__snapshots__/order.test.ts.snap
- test/__snapshots__/preset-mini.test.ts.snap
- test/__snapshots__/variant-handler.test.ts.snap
> fix(core)!: revert variant apply order in #1127

- packages/vscode/package.json
- packages/vscode/src/annotation.ts
- packages/vscode/src/utils.ts
Resolves #993 
Works well on [Vitesse](https://github.com/antfu/vitesse). I haven't tested too much on other frameworks, so it might not be stable. Set the option `"unocss.colorPreview": false` in `setting.json` to disable this feature.
> feat(vscode): add color preview

- packages/core/src/generator/index.ts
- test/__snapshots__/preflights.test.ts.snap
- test/preflights.test.ts
Trying to address https://github.com/unocss/unocss/issues/1186 though I'm not exactly sure I understand the code enough, so I don't know if those two places are sufficient or if I missed something.
Please let me know if there's more to it.
Quoting myself from https://github.com/unocss/unocss/issues/1186 for a little more inline-context
> I think this is really confusing as I'm specifically defining a preflight here, so I'd expect it to be in preflight and therefore ordered before other styles instead of needing to manually "duplicate" my intend.
Closes https://github.com/unocss/unocss/issues/1186
> feat(core)!: default preflights to `preflights` layer

- packages/preset-mini/src/rules/border.ts
- packages/preset-mini/src/rules/typography.ts
- packages/preset-wind/src/rules/animation.ts
- packages/preset-wind/src/rules/behaviors.ts
- packages/preset-wind/src/rules/divide.ts
- packages/preset-wind/src/rules/line-clamp.ts
- test/__snapshots__/autocomplete.test.ts.snap
- test/__snapshots__/preset-mini.test.ts.snap
- test/__snapshots__/preset-wind.test.ts.snap
- test/assets/preset-mini-targets.ts
- test/assets/preset-wind-targets.ts
This PR adds on top of #1170, but instead introduces fix that can be considered breaking change.
- use border style list from in `divide-x` style
- update `font-synthesis` to use static rules with bracket rules for compund values (See https://developer.mozilla.org/en-US/docs/Web/CSS/font-synthesis#syntax)
- fix: support global value for `animate-x`. previously `animate-<global>` would produce `animation-play-state: <global>`
- fix: properly support `list-<style>-<outside|inside>`
- fix: `line-clamp-none` was set to `line-clamp: unset`
- add `h.global` to the related utilites
> feat(preset-mini,preset-wind)!: add more global keywords

- packages/preset-mini/src/variants/pseudo.ts
- test/__snapshots__/order.test.ts.snap
- test/order.test.ts
Breaking because currently this
```html
<div class="parent-hover:dark:parent-focus:bg-yellow-600">
``` 
bunches the `parent`s together and yields:
```css
.dark .parent:hover:focus>.parent-hover\:dark\:parent-focus\:bg-yellow-600{...}
```
This PR aligns the behavior with the distinct version (ex.: group & parent):
```html
<div class="group-hover:dark:parent-focus:bg-yellow-600">
``` 
```css
.group:hover .dark .parent:focus>.group-hover\:dark\:parent-focus\:bg-yellow-600{...}
```
Edit: update examples
> feat(preset-mini)!: add tagged variants' pseudo in order

- examples/next/README.md
- examples/next/next.config.js
Added information on how to disable webpacks caching in nextjs so that HMR works with unocss.
> docs(examples): Next.js: added information on HMR usage

- packages/preset-mini/src/utils/colors.ts
- packages/preset-mini/src/utils/utilities.ts
- packages/preset-mini/src/variants/misc.ts
- test/__snapshots__/preset-mini.test.ts.snap
- test/assets/preset-mini-targets.ts
- test/color.test.ts
- test/utils.test.ts
> fix(preset-mini): parse bracket correctly in variable variant

- packages/core/src/config.ts
- packages/core/src/generator/index.ts
- packages/core/src/types.ts
- packages/preset-icons/src/index.ts
- packages/preset-mini/src/index.ts
- packages/preset-uno/src/index.ts
- packages/preset-wind/src/index.ts
- test/__snapshots__/prefix.test.ts.snap
- test/__snapshots__/preprocess.test.ts.snap
- test/prefix.test.ts
- test/preprocess.test.ts
This PR adds the prefix support in core,
```ts
{
rules: [
[/^p-(\d+)$/, () => '...', { prefix: 'foo-' }]]
]
}
```
would make it match the prefix first and then the body of rules, e.g. `foo-p-1`
it's also available for preset to define the prefix that apply to all nested rules,
```ts
{
name: 'my-preset',
prefix: 'foo-',
rules: [
[/^p-(\d+)$/, () => '...']],
[/^m-(\d+)$/, () => '...']]
]
}
```
> feat(core): utils level prefix

- playground/src/logics/uno.ts
If user provides `transformers` in config, `applyTransformers` got the `transformers` from `uno.config` was a `[]`. So `transformedHTML` need force refresh to apply `transformers`.
> fix(playground): refresh transforms at initial

- packages/vscode/src/utils.ts
Fixes:
- matching wrong colors when using 'dark:' prefix
- color preview not working on valueless attributes when `AttributifyOptions.strict = true`
> fix(vscode): match correct colors

- packages/extractor-pug/src/index.ts
On Windows, the regex will never succeed since the `new line` is `\r\n`.
closes #1150
> fix(extractor-pug): use any whitespace instead LF on regexp

- packages/vite/src/modes/global/build.ts
> fix(vite): repalce css hash in js when generating bundle

- examples/sveltekit/package.json
- examples/sveltekit/src/app.html
- examples/sveltekit/svelte.config.js
- examples/sveltekit/vite.config.js
- packages/vite/README.md
Update SvelteKit stuff to use latest changes where SvelteKit is configured via Vite plugins (from `^1.0.0.next.360` IIRC) 
closes #1236
> docs(vite): update SvelteKit entry and the example

- packages/vite/src/index.ts
- packages/vite/src/modes/per-module.ts
Currently, in "per-module" mode, some class names(e.g. "shadow", "ring") do not work as expected because they lack the "layout: preflights" predefined css vars.
> fix(vite): add default `layer: preflights` css when mode is `per-module`

- packages/preset-mini/src/index.ts
- packages/preset-mini/src/variants/dark.ts
- test/__snapshots__/preset-mini.test.ts.snap
- test/preset-mini.test.ts
> feat(preset-mini): customizing dark mode selector

- packages/shared-integration/src/defaults.ts
As mentioned in the [readme](https://github.com/unocss/unocss#scanning):
> By default UnoCSS will scan for components files like: .jsx, .tsx, .vue, .md, **.html**, .svelte, .astro.
But it wasn't in the array. Feel free to close if this isn't necessary.
It was a bit confusing to me how index.html _was_ included when I was using the [vite plugin](https://github.com/unocss/unocss/blob/163be1b4a6a20020af2305e437405ceb8be99a98/packages/vite/src/transformers.ts#L13), but when I was using the vscode extension, it _wasn't_ included.
> fix(vscode): add html to the default includes

- packages/nuxt/src/index.ts
Fixes #1264 
Starting from `nuxt@3.0.0-rc.5`, Nuxt plugins not using `defineNuxtPlugin` are considered as invalid and will throw a warning (https://github.com/nuxt/framework/pull/5857).
This PR makes `@unocss/nuxt` inner Nuxt plugin valid by simply using `defineNuxtPlugin`.
> fix(nuxt): use defineNuxtPlugin

- packages/nuxt/src/index.ts
This is a workaround that fixes UnoCSS HMR when using `@unocss/nuxt` with `@nuxt/kit@3.0.0-rc.5` 
(Related commit: https://github.com/nuxt/framework/commit/308148977d5d7e29ad3e6e6ecfda54a3d4a56e8a)
> fix(nuxt): use nuxt `vite:extend` hook

- test/vite.test.ts
emptyDir type declarations
```ts
export function emptyDir(path: string): Promise<void>;
export function emptyDir(path: string, callback: (err: Error) => void): void;
```
This will return `string`, so `emptyDir` will return a `Promise<void>`, so it should be add `await` before it
```ts
join(root, 'dist')
```
> fix: add await before fs.emptyDir

- packages/core/src/config.ts
- packages/core/src/utils/object.ts
- test/utils.test.ts
This PR change `mergeDeep` use override logic when `origin` and `patch` both arrays.
I think it isn't a good way to resolve #1340 
Is there a better way to solve it? please guide me
fix #1340
> fix(core)!: overide array on theme merging, revert shallow merge of theme

- packages/runtime/src/index.ts
- packages/runtime/src/utils.ts
- test/runtime.test.ts
This PR uses simple regex to replace only 3 encoded entities: `&`, `<` and `>`
Alternative to #1325
Closes #1323
> feat(runtime): try to decode page's html on default `extractAll` using regex

- packages/vite/src/modes/global/build.ts
- test/fixtures.test.ts
- test/fixtures/vite-lib/index.html
- test/fixtures/vite-lib/lib/main.css
- test/fixtures/vite-lib/lib/main.ts
- test/fixtures/vite-lib/package.json
- test/fixtures/vite-lib/unocss.config.ts
- test/fixtures/vite-lib/vite.config.ts
fix: #1341
I think it is only necessary to handle js files if the format is umd/amd/iife.
> fix(vite): does not found CSS placeholder in the generated chunks

- packages/core/src/utils/variantGroup.ts
- test/variant-group.test.ts
variant group supports :not selector syntax:
```css
[&:not(h1)]:(text-sm text-white)
```
> feat(core): variant group supports bracket selector

- packages/transformer-compile-class/src/index.ts
- test/transformer-compile-class.test.ts
before:
```js
console.log(':uno: flex justify-center bg-red') // uno-x03015
console.log(':uno: flex bg-red justify-center') // uno-6kgt2n
```
now:
```js
console.log(':uno: flex justify-center bg-red') // uno-x8m0ub
console.log(':uno: flex bg-red justify-center') // uno-x8m0ub
```
> perf(transformer-compile-class): generate same class for different sequence of same utilities

- packages/preset-mini/src/variants/breakpoints.ts
- packages/transformer-directives/src/index.ts
- test/transformer-directives.test.ts
https://windicss.org/features/directives.html#screen
> feat(transformer-directives): Implemented @screen directive

- packages/cli/src/index.ts
the parameter `file` in `watcher` `callBack` is relative path, but `configSources` is absolute path array, it always false
> fix(cli): config change not work

- packages/core/src/extractors/split.ts
- packages/inspector/client/components/CodeMirror.vue
- packages/shared-common/src/index.ts
- packages/vscode/src/annotation.ts
- test/pos.test.ts
- Updated extractor regex
- Updated `getMatchedPositions`
- Added and updated tests
Currently, only the classes inside of the variant group are highlighted, not the variant itself (e.g. with `hover:(bg-red-400 h-4)`, `hover:` will still not be highlighted).
> feat(editor): editor highlight for variant groups

- packages/preset-icons/src/core.ts
The `result` of UniversalIconLoader  maybe a promise object. so that the checking  `if (result)` will never be false.
> fix(icons): correctly combine loaders

- examples/vite-react/vite.config.ts
We must put UnoCSS() before React() to make sure that attributes are compiled to classNames.
See https://github.com/unocss/unocss/tree/main/packages/vite#:~:text=preset%2Dattributify%2C-,you%20must%20add%20the%20plugin%20before,-%40vitejs/plugin%2Dreact
> chore(example): fix plugins' order in the react example 

- packages/core/src/generator/index.ts
- packages/core/src/types.ts
- test/__snapshots__/variant-handler.test.ts.snap
- test/variant-handler.test.ts
PR to support #1466
Currently, one variant match are grouped under single `PreparedRule` so its output will be merged. The existing `noMerge` that can break this type is only available in rule, and now added to variant as well. This is to help variants that produce pseudo rules that needs to be separated due to vendor prefixes (at least without some post processing).
> feat(core): add noMerge to variant context

- packages/transformer-attributify-jsx/README.md
- packages/transformer-attributify-jsx/src/index.ts
- test/transformer-attributify-jsx.test.ts
Although the react jsx doesn't support the colon operator, we can try to change the colon operator into a short dash operator  so that we can avoid the limitation of react. And then we can use some more semantic grammars like `hover:op30` instead of `hover-op30`.
> feat(attributify-jsx): support rewriting colon operator

- packages/preset-attributify/src/jsx.ts
- test/dts/jsx.test-d.tsx
Some attributes are not typescript supported in tsx, such as `flex`, `absolute`, `op30`, `fw20`, `ma`, and i think we can give a better typescript support of it.
> feat(preset-attributify): more complete type support for tsx

- packages/inspector/client/components/ReplPlayground.vue
- packages/inspector/client/composables/fetch.ts
- packages/inspector/node/index.ts
Closes: #1530
Excluding safelist:
Including safelist:
---
_P.S. There are no recommended extensions listed in `.vscode`. Moreover, if there's ESLint I suggest adding your eslint config as well._
> feat(inspector): Allow including/excluding safelist in REPL

- README.md
If copy the Preflight example code to your own project directly, and you will receive the following error message.
```
Internal server error: /__uno.css:5:29: Missed semicolon
```
> chore: example code is missing a semicolon

- packages/transformer-attributify-jsx/src/index.ts
- test/transformer-attributify-jsx.test.ts
When I tried to use the UnoCSS in a React project today, I found a bug of the `transformer-attributify-jsx`. The transformer-attributify-jsx will change the attribute to `xxx=""`, such as `text-red=""`, to avoid the limitation of React JSX. But it also changes the className part by mistake. For example, I might write some code snippet like this:
```tsx
<div className={red ? 'text-red' : 'text-green' }></div>
```
But it would be transformed to something like this:
```tsx
<div className={red ? 'text-red=""' : 'text-green=""' }></div>
```
So I can't get the correct result. And this PR is to solve this problem, as it will ignore the className part when transforming jsx.
> fix(transformer-attributify-jsx): ignore the className part

- packages/cli/package.json
- packages/cli/src/index.ts
- pnpm-lock.yaml
- test/__snapshots__/cli.test.ts.snap
- test/cli.test.ts
> feat(cli): support for transformers

- packages/cli/src/cli-start.ts
- packages/core/src/types.ts
- test/cli.test.ts
> feat: support unocss config for cli

- packages/vscode/src/contextLoader.ts
Linked issue: #1644
Linked Commit: #1632 
function `pathe:dirname` will change the slash of path
https://github.com/unjs/pathe/blob/main/test/index.spec.ts#L86
This cause unequal on Windows and could not load config file.
> fix(vscode): windows pathe format

- packages/shared-common/src/index.ts
- test/pos.test.ts
> fix(vscode): remove css-directive transformer to get matched result from source code

- packages/preset-rem-to-px/src/index.ts
- test/preset-rem-to-px.test.ts
无法转换!important修饰的属性
在 [playground](https://uno.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCIAuBTAHpgWiQFsoBCHfI0ywgbQEYAGAJ22IF1zaDHX2O6KLQwlyJdAD5gAenARJAKCA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAsnsJajfYwIIwxTAARgFcYwLAE9KAXzhYoEEHADkw3BADGdOsqShIsarQYwAShhAAVCAAUAHnIVLlAATWbtAek4mAtLRBfGAhfMDtdJAw7A3hMLABDYQAbWOw8QmIyAApkDmNGOgAuOABtKjyuZlYsgEp2VCNK3n4hUXEJWvqKk3MrWztaqgBdJGkapCA&options=N4IgTgpgzgDg9gOygSwG4RALgGYEMA2UEANCAC5i5LZxgC2WehEAvkA) 查看 output css
html
```html
<div class="text-sm !text-sm text-[10rem] !text-[10rem]" text="sm !sm"></div>
```
output
```css
.\!text-\[10rem\]{font-size:10rem !important;}
.\!text-sm,
[text~="\!sm"]{font-size:0.875rem !important;line-height:1.25rem !important;}
.text-\[10rem\]{font-size:160px;}
.text-sm, …
```
> fix(preset-rem-to-px): convert all rem values

- packages/preset-mini/src/_utils/handlers/handlers.ts
- test/handler.test.ts
This PR adds handler types:
- `[raw:x]`: The value will be placed as is, without any alteration. This may not always be viable in extraction but could be useful in manual `generate()` method.
- `[string:x]`: only the underscore bracket logic will be applied and the value will then be single-quoted. `url` and `calc` replacements are not applied
> feat(preset-mini): add handler bracket types

- packages/preset-wind/README.md
- packages/preset-wind/src/variants/default.ts
- packages/preset-wind/src/variants/experimental.ts
- packages/preset-wind/src/variants/index.ts
- test/__snapshots__/autocomplete.test.ts.snap
- test/__snapshots__/preset-wind.test.ts.snap
- test/assets/preset-wind-targets.ts
Thanks to #1681 this PR introduces sticky hover as a standalone variant. The sigil was `@` instead of `&` as in the linked issue.
However, due to its standalone nature, there's no integration with css functions available in pseudo so chaining this variant may require variable variant.
> feat(preset-wind): sticky hover

- packages/preset-icons/README.md
> docs: improve sentence

- packages/preset-mini/src/_variants/negative.ts
- test/__snapshots__/preset-mini.test.ts.snap
- test/__snapshots__/preset-wind.test.ts.snap
- test/assets/preset-mini-targets.ts
- test/preset-mini.test.ts
Globally negate value if within `calc`, `clamp`, `min`, or `max` functions. There are `var` and `env` too but for now the code follows the handler code:
https://github.com/unocss/unocss/blob/76b883f3d412b61be85f35b08ebc5f616abef818/packages/preset-mini/src/_utils/handlers/handlers.ts#L126
To *hint* var/env to be able to be negated, for now use `calc(var())` as in tests.
> feat(preset-mini): negate math function values

- packages/core/src/generator/index.ts
<details>
<summary>thanks</summary>
First of all, I want to thank you for the brilliant framework. While I interested of how it works I started looking into sources. 
</details>
I found that `applyVariants` method could be improved a bit, but it helps to reach 7x speed supremacy over windicss:
* instead of chaining `reduce()` and `reduce()` methods we can simply write `reduceRight()`, as result will be the same (+ original array does not mutate)
* we may use `variantHandlers.slice()` instead of `[...variantHandlers]` as it 2x faster (according to jsbench.me).
I think there are a lot of other possibilities to improve the performance, but I think it's a nice start
> perf(core): improve `applyVariants` method speed

- packages/vscode/src/annotation.ts
- packages/vscode/src/utils.ts
> fix(vscode): skip util contains none color define

- packages/runtime/src/index.ts
> fix(runtime)!: fix config merge

- packages/core/src/generator/index.ts
- test/generate-async.test.ts
PR: #1407
I want to collect the used theme in postprocess and return it in preflights. But preflights will be executed faster.
Add theme variables collected by `postprocess` to preflight
> feat(core)!: generate preflights after utilties

- packages/preset-attributify/src/variant.ts
- packages/preset-mini/src/_rules/static.ts
- packages/preset-mini/src/_utils/handlers/handlers.ts
- test/__snapshots__/preset-attributify.test.ts.snap
- test/__snapshots__/preset-mini.test.ts.snap
- test/assets/preset-mini-targets.ts
- test/handler.test.ts
- test/preset-attributify.test.ts
This PR changes the behavior introduced in #1717
It turns out `[raw:x]` syntax that uses space will be difficult (never?) to get matched anywhere. So the behaviour is updated in this PR, such that:
- `[raw:x]` is removed but may be re-introduced if needed.
- `[string:x]` will produce an *almost* equal value to the original `x`, only replacing unescaped `_` to space.
- `[quoted:x]` is special case that (as of current css spec) would only be useful for `content` property. This is `[string:x]` as above with additional quoting with `"`. This would replace following rule: https://github.com/unocss/unocss/blob/d2b022d313c39aa9c1e309a6167f4be699489fd4/packages/preset-mini/src/_rules/static.ts#L72
- The regular bracket syntax for `content-[x]` is still avaiable but now behaves like regular …
> feat(preset-mini)!: update content-x and change handler type

- packages/core/src/generator/index.ts
- test/__snapshots__/prefix.test.ts.snap
- test/prefix.test.ts
Linked issue: #1796 
The orignal test file is using `presetMini` which does not include the `container` shortcut
-> change to `presetUno`
> fix(core): support shortcut prefix

- packages/shared-common/src/index.ts
- test/pos.test.ts
The string to be tested here is the **source code** and does not need to be "escaped".
> fix(vscode): attributify value starts with number

- packages/core/src/generator/index.ts
- playground/src/auto-imports.d.ts
- test/__snapshots__/prefix.test.ts.snap
- test/prefix.test.ts
> fix(core): slice prefix correctly in expandShortcut

- .tazerc.json
- examples/nuxt2-webpack/.npmrc
- examples/nuxt2-webpack/nuxt.config.ts
- examples/nuxt2-webpack/package.json
- examples/nuxt2-webpack/pages/index.vue
- packages/nuxt/src/index.ts
fix: #1832
> autoimport unocss will generate the code 
>
> ```ts
> import 'uno.css'
> export default defineNuxtPlugin(() => {})
> ```
>
> but `defineNuxtPlugin` is not autoimport in pure nuxt2
> fix(nuxt2): support nuxt2

- packages/core/src/config.ts
- packages/core/src/generator/index.ts
- packages/core/src/types.ts
- packages/core/src/utils/helpers.ts
- packages/core/src/utils/object.ts
- packages/preset-mini/src/_theme/types.ts
- packages/preset-typography/src/index.ts
1. Make `createGenerator` support generic. (will use for test
> The code is supported, but the type is not
1. The `colors`  support `nested`.
2. The `fontSize` support `string | [string, string]`.
> feat: improving some types

- .github/workflows/ci.yml
- .github/workflows/release.yml
https://github.com/nodejs/release#release-schedule
Node.js 18 has been LTS now, and 16 is Maintenance.
> ci: upgrade node to 18

- packages/astro/src/index.ts
This commit also marks the existing `injectReset` & `injectEntry` as deprecated. Users with those options set should have no breaking changes on their existing code, but only receive a warning via the linting tool.
close #1877
> feat(astro): introduce the `injectExtra` option

- packages/core/src/extractors/index.ts
- packages/core/src/extractors/split.ts
- packages/preset-mini/src/_rules/variables.ts
- packages/shared-common/src/index.ts
- test/__snapshots__/preset-mini.test.ts.snap
- test/assets/preset-mini-targets.ts
[UnoCSS Playground](https://uno.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCIAuBTAHpgWgA5c4oBtAggM2oC4ByASQDscAnBgXQuoHs2NBAFswcAJ50ICdgAoqtAJQ9y-QdWwJMAV3bYCSbJkxgWAcySMYEAAwAmBgBoG1mwGYnL2wBZP1gIz%2B3OgAfAgA7G7AAPTgECFQiQBQoJCwiCioDDj4xKS8AoTUImKS6Kwc6CpqRZo6egZGJuaW6K526I5ttm6d3TbefQH%2BVQxhkTFxCVApcenIaNl4hCRwYxFRsZDTibt7ycBwpgDWUHpwGEiY4nDYSAAW2EboUPd61Bj3xgAOltHR7CQwiQADphNhoqYOJC2Nh2CCYCgAPwQVBuEH%2BACcoSAA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owDq2yZF1tAgjDFMAEYCuMYOgCecAL5x0UCCDgByPlggBjKlTkAoDagAekWCgwBDPgBt4aTDnyFgRABQINccpRowqALjgBtZy9dWekZ7AEoSfxcWdw4uXgEhYTD-AF0Ilygzam8-AN85ZT4qGBkAWkzTVDkyJGUIU2hvOUpkOXEU1PS4GAALVBBUbyc8uoaoL0RIgIpQIyhhIamRgi4jYu8AIgBidF2NrryXAE4ABhPNrYBGdAAWI2UAZn2l8Smxf3exUKA&options=N4IgzgLgTglgxhEAuaBXApgGhFdYAOA9gHZgwBu6yAZgIYA2Y6AvkA) …
> feat(preset-mini): support arbitrary properties with quotes

- packages/transformer-directives/src/index.ts
Fixes #1849
In production builds Nuxt's cssnano plugin applied before unocss plugin. Its mergeRules optimization causes problems with at-rules. My previous solution was disabling `mergeRules` by adding the following lines to @unocss/nuxt module. But that's not ideal since it affects minifying:
```ts
if (nuxt.options.postcss.plugins.cssnano) {
const preset = nuxt.options.postcss.plugins.cssnano.preset
nuxt.options.postcss.plugins.cssnano = {
preset: [preset?.[0] || 'default', Object.assign(
preset?.[1] || {}, { mergeRules: false },
)],
}
}
```
> fix(transformer-directives): enforce `pre` by default

- packages/core/src/extractors/index.ts
- packages/core/src/extractors/split.ts
- packages/preset-mini/src/_rules/variables.ts
- packages/shared-common/src/index.ts
- test/assets/preset-mini-targets.ts
Cleaned up arbitrary CSS property implementation to make it more readable.
Filtered out URLs(Code is taken from [tailwindcss repo](https://github.com/tailwindlabs/tailwindcss/blob/458950f5df1b137f3e3ccf329879300c24e5c21a/src/lib/generateRules.js#L395-L409).
> refactor(preset-mini): cleanup arbitrary property implementation

- packages/config/src/index.ts
- packages/nuxt/package.json
- packages/nuxt/src/index.ts
- packages/shared-integration/src/context.ts
- packages/transformer-directives/src/index.ts
- pnpm-lock.yaml
Reverts #1923
Fixes #1929
Fixes #1849 by disabling cssnano's mergeRules optimization if transformer-directive is detected in nuxt module. esbuild already merges the rules
Also fixes an issue where getConfig always returns an empty object. I discovered it while debugging the issue.
https://github.com/unocss/unocss/blob/9c89d93daaf7085b9060060557259f314c23663d/packages/shared-integration/src/context.ts#L92-L95
> fix(transformer-directives,nuxt): revert `enforce: 'pre'`, disable `mergeRules`

- packages/config/src/index.ts
- packages/nuxt/src/index.ts
A regression caused by #1930
Fixes duplicate warning in nuxt module when using external config file.
> fix(nuxt): apply defaults correctly

- packages/shared-integration/src/defaults.ts
transformer-compile-class does not works with classes inside *.phtml and *.php files
this fix might help
> feat: add php and phtml to the default includes (#1939)

- examples/next/components/navbar.tsx
- examples/next/pages/blog/index.tsx
- examples/next/pages/index.tsx
- fixed running the next13 example encounter errors
- [Nextjs Beta Docs](https://beta.nextjs.org/docs/api-reference/components/link#props)
> Good to know: <a> tag attributes can be added to <Link> as props. For example, className or target="_blank". These will be forwarded to the underlying <a> element on render.
Signed-off-by: Jie Peng <im@jiepeng.me>
> chore(next-example): improve link component

- interactive/components/Search.vue
- fix spell checker
- fix search duplicate execution
After performing the search, the `router.replace` operation triggers watch, causing each search to be performed twice.
``` ts
watch(
() => route.query.s,
async () => {
input.value = String(route.query.s || '')
await excuteSearch()
},
)
async function executeSearch() {
...
await router.replace({
path: '/',
query: input.value
? {
s: input.value,
}
: undefined,
})
}
```
> chore(interactive): reduce search execution

- packages/nuxt/src/index.ts
Fixes #2009
I was about to implement #1930 patch for Nuxt 2, but it seems transformer-directives don't work at all in Nuxt 2. So, this PR fixes #2009 by limiting it to Nuxt 3.
> fix(nuxt): don't patch cssnano config for nuxt2

- packages/preset-attributify/src/extractor.ts
- test/__snapshots__/preset-attributify.test.ts.snap
- test/preset-attributify.test.ts
> fix(preset-attributify): apply `prefixedOnly` filter on extractor

- packages/preset-web-fonts/README.md
- packages/preset-web-fonts/src/index.ts
- packages/preset-web-fonts/src/types.ts
Fucked by GFW because of default provider `google`.
So add an option to custom request to fetch web font source to enable something like proxy agent.
> feat(preset-web-fonts): add customFetch option

- packages/preset-mini/src/_theme/types.ts
- packages/preset-wind/src/rules/container.ts
- test/__snapshots__/preset-wind.test.ts.snap
- test/preset-wind.test.ts
> feat(preset-wind): add padding for container rule

- packages/runtime/src/index.ts
For one use case, I have an "un-cloak" attribute added automatically to the html tag dynamically before the body exist.
Plus I find this intuitive to have the attribute on the html tag, the fact that both work seems better to me.
Thanks for your work !
You can try here the following 2 links (to copy paste in URL):
data:text/html,<html un-cloak>
<style>[un-cloak]{display:none}</style>
<script type="module">
import initUnocssRuntime from "https://patch.deno.dev/@unocss/runtime?dev";
initUnocssRuntime();
</script>
<div>will show</div>
</html>
data:text/html,<html un-cloak>
<style>[un-cloak]{display:none}</style>
<script type="module">
import initUnocssRuntime from "https://esm.sh/@unocss/runtime?dev";
initUnocssRuntime();
</script>
<div>will not show</div>
</html>
The patch is available …
> feat: remove un-cloak to html node as well as body

- packages/vite/src/modes/svelte-scoped/index.ts
This PR adds .svelte.md and .svx file extensions to the SvelteScopedPlugin filters so UnoCSS works out of the box for users of mdsvex+UnoCSS who use those file extensions.
At least that's what I think it does, I got an npm error trying to install from my branch in my fork so no idea if this actually works. 😨 
If it does work it should also fix https://github.com/unocss/unocss/issues/1936
> feat: add mdsvex extensions to SvelteScopedPlugin filters fix #1936

- packages/vscode/src/annotation.ts
- packages/vscode/src/autocomplete.ts
- packages/vscode/src/utils.ts
Related issues: #1348 #1767 #1817
The old method of matching colors is **not perfect**. As Fu [commented](https://github.com/unocss/unocss/issues/1348#issuecomment-1207460076): 
> I guess we could infer the color from the generated CSS instead of relying on the theme object.
That's what I've done in this PR
> feat(vscode): better color preview

- packages/vscode/src/autocomplete.ts
Before:
After:
This bug only appears in the attributify mode e.g. `text="xl gray"`
> fix(vscode): resolve the right completion label

- packages/preset-icons/package.json
- pnpm-lock.yaml
Fixes bug in icon loader used by UnoCSS and Unplugin Icons.
> chore: update Iconify Utils

- packages/preset-mini/src/_rules/typography.ts
- packages/preset-mini/src/_utils/utilities.ts
- test/__snapshots__/preset-mini.test.ts.snap
- test/assets/preset-mini-targets.ts
Add `text-x/y` utility that resolves to font-size & line-height for x & y respectively.
> feat(preset-mini): add font-size/leading shorthand

- packages/preset-mini/src/_utils/handlers/regex.ts
- test/handler.test.ts
Reference: https://www.w3.org/TR/css-values-4/#font-relative-lengths
> feat(preset-mini): update css units

- packages/preset-attributify/README.md
Update documentation to match upstream changes in Svelte's language tools: https://github.com/sveltejs/language-tools/blob/master/docs/preprocessors/typescript.md#im-getting-deprecation-warnings-for-sveltejsx--i-want-to-migrate-to-the-new-typings
It seems to be working well like this, if I type it as an interface instead I get errors
> doc(preset-attributify): update docs with svelteHTML instead of svelte.JSX

- packages/preset-mini/src/index.ts
- packages/preset-uno/src/index.ts
- packages/preset-wind/src/index.ts
- test/__snapshots__/preflights.test.ts.snap
- test/preflights.test.ts
> fix(preset-mini): normalize preflights with variablePrefix

- packages/vite/src/modes/global/build.ts
There was a regression introduced in b7a6687d218827f1dc70e7aa61aa67bfbff838d9 where vite projects built using `vite build --watch` will only generate once. Subsequent generations will just leave the placeholder.
My solution here was to add the layers as they're loaded, rather than removing the `clear`.
Re-fixes #963
See #1963 - it's unclear why this reintroduced the issue, I'm not familiar enough with nuxt or astro.
> fix: `vite build --watch` not emitting anything

- packages/vscode/package.json
- packages/vscode/src/index.ts
https://github.com/unocss/unocss/issues/1764
now you can pass array to unocss.root
```json
"unocss.root": ["apps/a", "apps/b"]
```
or just a string as before 
```json
"unocss.root": "apps/c"
```
> feat(vscode): configure multiple subdirs

- packages/core/src/generator/index.ts
- test/__snapshots__/preset-mini.test.ts.snap
- test/preset-mini.test.ts
Fix #2068 
I'd tag this as breaking since the replacement is now global while exported and being used in 2 other places:
https://github.com/unocss/unocss/blob/badcf8666a43bcb640d1a2d1f8f8318b2ec27047/packages/vscode/src/selectionStyle.ts#L54
https://github.com/unocss/unocss/blob/badcf8666a43bcb640d1a2d1f8f8318b2ec27047/packages/transformer-directives/src/apply.ts#L66
> fix(core): replace scope placeholder globally

- packages/preset-attributify/src/extractor.ts
close #2104
This is a breaking change if you are using:
```html
<div opacity="10" fill="red" />
```
They won't be captured by unocss anymore.
You can either prefix them with `un-`
```html
<div un-opacity="10" un-fill="red" />
```
Or use `op` as the shorthand for `opacity`:
```html
<div op="10"/>
```
Or update the config to change it back:
```ts
presetAttributify({
ignoreAttributes: ['placeholder'] // previous default
})
```
> fix(attributify)!: add `fill` and `opacity` to default ignore attrs, close #2104

- packages/preset-mini/src/_rules/variables.ts
- test/assets/preset-mini-targets.ts
> fix(preset-mini): don't generate arbitrary property if it starts with colon

- packages/preset-web-fonts/src/index.ts
The most commonly used web font provider is Google Fonts and they are differentiating the CSS response based on the `User-Agent` header.
If the user agent supports `woff2` format then the CSS response will contain `woff2` font definitions.
`woff2` is using Brotli compression, which is far more efficient than `ttf`, able to use [`unicode-range`](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/unicode-range) (font chunks) and it's supported [>96%](https://caniuse.com/woff2) of browsers.
Currently the `@unocss/preset-web-fonts` is fetching web font CSS using `ohmyfetch` library without setting any user agent, that's why Google Fonts will serve a CSS with `ttf` fonts.
Example injected web font definitions by web-fonts preset:
```css
@font-face {  font-family: 'Fira Code'; …
```
> feat(preset-web-fonts): use woff2 compatible user-agent

- playground/src/components/Editor.vue
https://user-images.githubusercontent.com/35442047/215271430-14fdbbf4-f5fa-471d-84a7-d3284f53eb86.mp4
Currently, the content in the editor is not displaying correctly after being resized. It requires interaction, such as clicking or scrolling, or manual refreshing to display correctly.
> docs(playground): content missing on editor resize

- packages/preset-mini/src/_rules/typography.ts
- test/assets/preset-mini-targets.ts
> fix(preset-mini): fix non-existent `font-size`, still return `line-height`.

- packages/preset-mini/src/_variants/pseudo.ts
- test/__snapshots__/preset-mini.test.ts.snap
- test/__snapshots__/shortcuts.test.ts.snap
- test/preset-mini.test.ts
Closes #2161
preset-mini already handle :active with special `sort` key; might as well be split as separate selector.
> fix(preset-mini): always split :active pseudo

- packages/unocss/preset-wind.d.ts
To fix type definitions when importing `preset-wind` like:
```ts
import PresetWind from "unocss/preset-wind";
```
> fix(unocss): `perset-wind` => `preset-wind` typo fix

- README.md
`unocss-preset-autoprefixer` uses the `lightningcss` to generate css prefixer
> docs: add `unocss-preset-autoprefixer` in readme

- packages/preset-attributify/src/extractor.ts
- test/__snapshots__/preset-attributify.test.ts.snap
- test/preset-attributify.test.ts
Fixes #1584
Fixes #2112
Supersedes #2134
@chu121su12 I tried pasting [your code](https://github.com/unocss/unocss/issues/2067#issuecomment-1396298585) on playground and it was slowing down the editor. Every key store was taking 3-4 seconds on my machine. With this PR it seems instant as it should be. 
I also tested this PR with the provided repro in #2067, and it successfully builds.
> refactor(preset-attributify): improve element extractor

- packages/shared-common/src/index.ts
- test/pos.test.ts
`base`'s `b` is highlighted twice. Also visible in [playground](https://uno.antfu.me/play/?html=DwEwlgbgBARg9gJxAUwQXgEQxrDA%2BIA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCCMMUwARgK4zDoCeZF1tAJIBjAlT6UaMAKpYIcAL5x0UCCDgByNnOFUqGgFAHUAD0iwUGAIZsANvDSYc%2BQsCIAKBAbhwYAC1QQVAAuRG8fOFFbaCpQrwiIlhZQjRZbK2EAaw0ScJ8FXPzCuCg7alCAbQqNYTYqGDUAWlLbVBzESIhoqBTKZA1FAF1B4v4pWLgKvPJJWlkIdwBKYp8x2gYmVg4ubiWVmYEYETFPaZ8qYStW0IBGADoAJn2fYWQsFL9GMFiAeh-qEB3Kh%2BH45aYKZbhEYGCEGIA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwBoQJ84AHJeASwDd9NIBXIkAd2oBMwALTAdgAcARmI981AOY8wAgEwA2AL5A)
> fix(vscode): properly highlight attributify value

- packages/preset-mini/src/_variants/pseudo.ts
- test/__snapshots__/preset-attributify.test.ts.snap
- test/__snapshots__/preset-mini.test.ts.snap
- test/assets/preset-mini-targets.ts
- test/preset-attributify.test.ts
Since `backdrop-x` pseudo variant is by default colon-only to prevent clashes with `backdrop-x` rule, this PR introduces `backdrop-element-x` with (default) support for colon and dashses separator, thus enabling the variant to be used in attributify mode.
The syntax is choosen due the nature of backdrop as pseudo element. The thinking was if some pseudo class were to be introduced with clashing rule name, it would then be added as `<pseudo>-class-x` to accompany `<pseudo>-element-x`
> feat(preset-mini): add backdrop-element-x pseudo for attributify use

- packages/vite/src/modes/global/dev.ts
A misplaced semicolon has been introduced somewhere between 0.49.1 and 0.49.6, which produces invalid `<style>` and breaks whatever selector comes first in the CSS (in my case it breaks a preflight).
This PR moves the semicolon inside `{}` where it probably was supposed to be.
> fix(vite): misplaced semicolon

- packages/nuxt/src/index.ts
Related #2227
Fixes this case:
```vue
<template>
<div class="flex flex-col gap-4">
<div class="test1">
.test1
</div>
<div class="test2">
.test2
</div>
</div>
</template>
<style>
.test1 {
@apply bg-slate-200;
@apply text-center;
}
.test2 {
@apply text-center;
@apply bg-slate-200;
}
</style>
```
> fix(nuxt): disable cssnano `normalizeWhitespace` optimization

- packages/vite/src/modes/global/build.ts
When i specify relative dir for rollupOptions output
```
rollupOptions: {
output: [
{
dir: "dist/es"
}
]
}
```
In one project with only .ts files, it resolved to "dist/es".  However, in vue project, it resolved to absolute path "/home/xxx/project/dist/es".
This fix will handle absolute path postcss-plugin matching
> fix(vite): resolve relative path in rollupOptions

- packages/unocss/build.config.ts
- packages/unocss/package.json
- packages/unocss/src/postcss.ts
- pnpm-lock.yaml
`unocss/postcss` was only exporting an object
unocss/postcss: `{ postcss: true } `
@unocss/postcss `[Function: unocss] { postcss: true }`
> fix(postcss): fix export from `unocss`

- packages/cli/package.json
- packages/cli/src/index.ts
- pnpm-lock.yaml
- test/cli.test.ts
fixed: #2275 
In `@unocss/cli`, the configuration path using `pathe.resolve`, which results is `c:\\xxx\\xxx\\unocss.config.ts` on windows
https://github.com/unocss/unocss/blob/217998afa71bba40a2d38aefb12158643c3776c7/packages/cli/src/index.ts#L2
https://github.com/unocss/unocss/blob/217998afa71bba40a2d38aefb12158643c3776c7/packages/cli/src/index.ts#L76-L83
But In `unconfig`, the configuration path using `path.resolve`, which result does not contain the escape character——`\` on windows
https://github.com/antfu/unconfig/blob/fd0baca5f39b8feb087339dfc6d65918550bdc61/src/fs.ts#L2
https://github.com/antfu/unconfig/blob/fd0baca5f39b8feb087339dfc6d65918550bdc61/src/fs.ts#L49-L53
> fix(cli): config path is different with unconfig path

- packages/postcss/src/apply.ts
- packages/postcss/src/index.ts
- packages/postcss/src/screen.ts
- packages/postcss/src/theme.ts
- packages/postcss/src/types.ts
- fixes an issue that sometimes caused new styles to not appear
- prevents running on unrelated CSS files
- allows customizing `unocss` at-rule and plugin name. this is useful if you want to have separate CSS files and uno configs for different routes, for example, marketing site and dashboard.
> refactor(postcss): perf and stability improvements

- packages/nuxt/src/index.ts
Fixes #2279
In modern browsers there is no difference between `--foo:;` and `--foo: ;`. But on older browsers [this is an issue.](https://github.com/sveltejs/svelte/issues/7288#issuecomment-1046039821)
In Vite, comments will be discarded by esbuild anyway. On Webpack, `transformerDirectives` is only supported with `enforce: pre`, so we will never hit this line.
- Fix cssnano: https://github.com/cssnano/cssnano/tree/master/packages/postcss-discard-comments
- Rerun [postcss-normalize-whitespace](https://github.com/cssnano/cssnano/tree/master/packages/postcss-normalize-whitespace) after `cssnano`. Requires changes on Nuxt repo. We will only add the following code on our nuxt module. Then update [this file](https://github.com/nuxt/nuxt/blob/main/packages/vite/src/css.ts) on Nuxt side. All we …
> fix(nuxt): disable cssnano `discardComments` optimization

- packages/vite/src/modes/svelte-scoped/transform.ts
- test/__snapshots__/svelte-scoped.test.ts.snap
- test/svelte-scoped.test.ts
Fixes #2284
Is transforming node_modules in svelte-scoped mode something we expected?
> fix(vite): svelte-scoped: search attributify candidates only on template

- playground/src/composables/panel.ts
Fixed not open any panel when first open, and use storage cache sizes.
> fix(playground): display the right panel size

- packages/postcss/src/index.ts
For some reason Typescript doesn't pick up the default type when importing like that:
```ts
const unocss = require("@unocss/postcss")
//         ^ any 
```
Typescript inference works right with that but this is undefined:
```ts
const unocss = require("@unocss/postcss").default
```
Fixing that by adding a circular reference to itself. 
Because PostCSS plugins can be provided with the package name, and this will do `require(package-name)` internally.
```ts
plugins: {
'@unocss/postcss': {},
},
```
> fix(postcss): add a `default` reference to itself

- packages/webpack/src/index.ts
Unplugin will encode resolved path since [0.9.0](https://github.com/unjs/unplugin/commit/335f403bfba35bee4e251493824786ae1689a9e7).
> fix(webpack): resolve path from id with decodeURIComponent

- packages/vscode/src/autocomplete.ts
This will allow `unocss` to be used in frameworks like `yew` and [`leptos`](https://github.com/leptos-rs/leptos).
> feat(vscode): support `rust` as a language id

- packages/postcss/src/index.ts
Webpack considers Windows paths with forward slashes as invalid:
https://github.com/webpack/webpack/blob/4ba225225b1348c8776ca5b5fe53468519413bc0/lib/NormalModule.js#L93
> fix(postcss): normalize dependency paths

- packages/astro/src/index.ts
This pull request makes UnoCSS's Astro integration respect Astro's [`srcDir`](https://docs.astro.build/en/reference/configuration-reference/#srcdir) option, instead of hard-coded `src`.
> fix(astro): respect Astro's `srcDir` config

- packages/astro/README.md
I assume my issue in #2325 is a common one, and it's worth a place in the readme.
Help with wording is welcomed.
> docs: add note about Astro `client:only` components

- packages/vite/src/modes/global/dev.ts
Ran into an issue where my dev server processes wouldn't shut down for some time due to an open handle.
I eventually traced it to a timer in UnoCSS which is set when the build starts and then runs for 20 seconds no matter what.
This pull request makes it so the timer is automatically cleared once it's fulfilled its purpose or the build server is closed so it won't keep the Node process alive.
> fix(vite): avoid hanging warning timer

- packages/preset-mini/src/_rules/behaviors.ts
- test/__snapshots__/preset-mini.test.ts.snap
- test/__snapshots__/transformer-directives.test.ts.snap
Vendor prefixed properties should come before the non-prefixed ones in general.
https://css-tricks.com/ordering-css3-properties/
As far as I searched all rules was following that in this repository except this `appearance` rule.
This PR moves `-webkit-appearance` before `appearance`.
> fix(preset-mini): order `-webkit-appearance` before

- docs/presets/icons.md
Filed an issue on VP: https://github.com/vuejs/vitepress/issues/2192
Toggle dark mode from icons.md icon and from VP switcher can result in phantom clicks, VP switcher not reactive to local storage.
This PR also includes icon examples for `Modes Overriding`.
https://streamable.com/36lpf7
> docs: add icons examples on icons.md

- docs/.vitepress/config.ts
On desktop play and interactive docs links work, but on mobile result in 404, added full url to navbar entries
> docs(fix): navbar links not working on mobile

- docs/index.md
Link rich integrations to vite, otherwise page navigation will result in a 404 error.
> docs: link rich integrations to vite

- docs/guide/index.md
The regex shown as an example in the Getting Started page works for integer numbers only while the examples show decimal numbers. This PR updates the example regex to accept decimal numbers.
> docs: regex that accepts decimal numbers

- docs/.vitepress/theme/rainbow.css
It's very distracting, even if it's been turned to over 40 seconds for non-landing pages.
It would be best to completely turn it off instead if the user explicitly requests for reduced motion.
> docs: disable rainbow animation on reduce motion

- packages/eslint-plugin/fixtures/src/+page.svelte
- packages/eslint-plugin/src/constants.ts
- packages/eslint-plugin/src/rules/order.ts
Currently `@unocss/eslint-plugin` only supports React and Vue by visiting `JSXAttribute` and `VAttribute` nodes.
This patch adds support for Svelte by visiting `SvelteAttribute` which comes from [svelte-eslint-parser](https://github.com/ota-meshi/svelte-eslint-parser/blob/main/docs/AST.md#svelteattribute) community package.
While they are the official (and recommended) eslint plugin for Svelte, they uses some hack-ish preprocess/postprocess mechanisms to traverse the code and does not provide any ASTs. Thus it is impossible to use their implementation.
This comes from the difference between React/Vue and Svelte's AST structure. As there are no concrete standard in the eslint AST specification, each framework's AST and how their properties are calculated is _slightly_ different. …
> feat(eslint-plugin): add svelte support

- docs/.vitepress/theme/overrides.css
When window innerWidth is not enough but greater than `768px`, there is the problem in navbar.
|  before  |  after  |
|  ------  |  -----  |
| ![unocss1](https://user-images.githubusercontent.com/30711792/230731193-fff562a1-3582-46c4-982d-869bc3d77024.png) |![unocss2](https://user-images.githubusercontent.com/30711792/230731209-4909d5a1-6668-4352-946e-7a9e9fadab5b.png)|
> docs: fix navbar style

- docs/config/extractors.md
- docs/extractors/pug.md
- docs/integrations/vite.md
- examples/vite-pug/vite.config.ts
- packages/core/src/config.ts
- packages/core/src/extractors/index.ts
- packages/core/src/types.ts
- packages/extractor-pug/README.md
- packages/preset-attributify/src/index.ts
- packages/preset-tagify/src/index.ts
- test/pos.test.ts
This PR introduced `extractorDefault` option and make `extractorSplit` always applied. So when providing `extractors`, it no longer overrides the default, making the usage simpler. It means to use `extractorPug` or `extractorSvelte`, you no longer need to specify `extractorSplit` along side.
To force override the default extractor, users or presets could provide `extractorDefault` option:
```ts
// unocss.config.ts
import { defineConfig } from '@unocss/core'
export default defineConfig({
extractors: [
// your extractors
],
// disable the default extractor
extractorDefault: false,
// override the default extractor with your own
extractorDefault: myExtractor,
})
```
> feat(core)!: always apply default extractor

- interactive/components/details/Rule.vue
`cs.github.com` is being retired
> feat(interactive): migrate `cs.github.com` to `github.com/search`

- playground/src/components/HeaderBar.vue
Currently it links to the playground instead of the interactive docs.
> chore(playground): update interactive docs link

- packages/postcss/src/index.ts
Fixes #2473
In this case, the `.next` folder had a few large `js` files causing the slowdown. IMO ignoring all dot folders by default is fine.
> fix(postcss): ignore dot folders

- packages/cli/package.json
- packages/cli/src/errors.ts
- packages/cli/src/index.ts
- pnpm-lock.yaml
- Updated from default to named export, as changed in [Consola v3](https://github.com/unjs/consola/releases/tag/v3.0.0).
> chore(cli): upgrade consola to v3

- packages/vite/src/modes/svelte-scoped/transform.ts
- test/svelte-scoped.test.ts
Fixes #2504.
Corresponding tests are also added.
Now UnoCSS correctly transforms
```svelte
<div class={clsx(flag && "text-red-500")}>This should be red</div>
```
into
```svelte
<div class={clsx(flag && "uno-3as8ej")}>This should be red</div>
```
in the `svelte-scoped` mode.
> fix(svelte-scoped): handle expressions in class attribute correctly

- docs/extractors/svelte.md
> docs: typo

- docs/.vitepress/config.ts
add activeMatch option in nav config , it can highlight the nav title In the same place
before:
after:
> docs: add nav config activeMatch

- packages/preset-attributify/src/extractor.ts
- test/cases/preset-attributify/case-1/input.html
Closes #2271
If you were using ternaries with attributes, and the rules you have used are generating false positives you don't want, you could:
- Move those ternaries to `class` attribute
- Block false positives with `blocklist` option: https://unocss.dev/guide/extracting#blocklist
> fix(preset-attributify): remove ternary handling

- docs/config/rules.md
While looking at the document, I found that `variants`'s link was broken.
- https://unocss.dev/config/rules#full-controlled-rules
Is it right to mean the following link?
- https://unocss.dev/config/variants
> docs: fix link

- packages/preset-mini/src/_utils/utilities.ts
- test/assets/output/preset-mini-targets.css
- test/assets/preset-mini-targets.ts
- test/color.test.ts
Hello,
This PR fixes the problem described on #2572 where `border-[6px]` was transformed on `border-color` and not `border-width`.
Not sure if what I did is valid, but I added an early return when the value has any number with a unit to the `parseColor` function.
Had to change some tests:
- I don't think that `fill-[1rem]` is a valid class. Source: https://developer.mozilla.org/pt-BR/docs/Web/SVG/Attribute/fill
- `stroke-\[1rem\]` changed to `stroke-width`, which I think is the correct one
This is my first PR for the project, so sorry if my solution is not the best. I'm happy to improve it
> fix(preset-mini): border arbitrary width (#2572)

- packages/extractor-pug/src/index.ts
Allows `doctype: 'html'` and other Pug configurations to be supported by extractor-pug.
> feat(extractor-pug): accept Pug compile options

- packages/preset-mini/src/_utils/utilities.ts
- test/assets/output/preset-mini-non-nested-theme-colors.css
- test/preset-mini.test.ts
this fixes #2600 
and also allows to use colors with hyphens in `theme.colors` as direct key
both are allowed in tailwind ( https://play.tailwindcss.com/jJv3sLB9uE?file=config ) and windicss
> fix(preset-mini): allow to use hyphens and numbers in theme config without nesting

- docs/config/presets.md
The expected type that comes from the [variant](https://github.com/unocss/unocss/blob/main/packages/core/src/types.ts#LL334C5-L334C5) is `Array` not `Object`
> docs: update expected type in variants example

- packages/astro/src/index.ts
- packages/vite/src/modes/global/dev.ts
fix: #2513
Avoid inject styles in non-ssr
> fix(astro): inject duplicate style

- packages/astro/src/index.ts
close: #2646
The real file path should be used here, but I don't know why it works in the unocss example.
I have tested it in the broken repo and that work.
And the build failure was also fixed...
> fix(astro): incorrect path and build failure

- packages/preset-mini/src/_rules/static.ts
- test/assets/output/preset-mini-targets.css
fix #2645
**Description**:
The issue is related to the distinction between content-empty and content-none in the static.ts file. Currently, content-empty sets the content to an empty character (""), whereas content-none should set the none attribute of the content. However, the code incorrectly sets content: '""' for content-none. This pull request fixes this inconsistency.
**Changes Made**:
-  Modified the code in static.ts to correctly set content: 'none' for content-none.
> fix(preset-mini): `content-none` should render `{ content: none }`

- docs/integrations/svelte-scoped.md
- packages/svelte-scoped/src/vite/global.ts
The docs say `server.hooks.js` instead of `hooks.server.js` so fixing that, also updated the error message to be more clear about what the file name should be.
> docs(svelte-scoped): change "server hooks" to "hooks.server.js" in error message and docs

- docs/.vitepress/config.ts
This is a revert of #2449. I fixed the bug in vitepress (https://github.com/vuejs/vitepress/pull/2400).
This will make the navbar links to link to the PR's playground/interactive docs from the netlify preview docs.
> docs: navbar links for PR preview

- packages/preset-attributify/src/autocomplete.ts
- packages/vscode/src/autocomplete.ts
- playground/src/composables/uno.ts
- test/preset-attributify.test.ts
#2643 worked with the playground but wasn't working with the VSCode extension due to the behavior differences with the playground. This PR make it work with VSCode extension.
> fix(vscode): attributify auto complete

- packages/vscode/src/index.ts
- packages/vscode/src/utils.ts
It was not possible to run `unocss.reload` when one of the root failed to load the config.
For example, when two directory exists and `npm i` was ran only in one of them.
> feat(vscode): ignore config load failed root

- packages/preset-wind/src/variants/misc.ts
- test/shortcuts.test.ts
> fix(preset-wind): key naming in shortcuts from starting with space or divide and not working

- docs/integrations/vite.md
Add missing `()` for `extractorSvelte`
> docs: update `extractorSvelte` usage in vite.md

- docs/presets/uno.md
When I read the [Rule](https://unocss.dev/presets/uno#rules) chapter in [preset docs](https://unocss.dev/presets/uno)，I clicked the interactive doc link and got a 404 page, so I do like this.
> docs: fix uno.md about interactive doc link

- packages/svelte-scoped/src/preprocess/transformClasses/index.test.ts
- packages/svelte-scoped/src/preprocess/transformClasses/processClassBody.test.ts
- packages/svelte-scoped/src/preprocess/transformClasses/processExpressions.ts
> fix(svelte-scoped): don't add spaces when class names include expressions as just part of them

- packages/svelte-scoped/src/preprocess/index.ts
- packages/svelte-scoped/src/vite/passPreprocessToSveltePlugin.ts
Fixes #2658 (as much as possible) by respecting the intended combine distinction between dev and prod.
> fix(svelte-scoped): properly pass vite command to UnocssSveltePreprocess

- docs/guide/index.md
- examples/vite-svelte-postcss/src/App.svelte
https://stackblitz.com/edit/unocss-unocss-xlssxe?file=src%2FApp.svelte
as per https://github.com/unocss/unocss/pull/2691#issuecomment-1571752271
> docs(example): fix vite-svelte-postcss example

- bench/run.mjs
- docs/guide/extracting.md
- docs/integrations/astro.md
- docs/integrations/postcss.md
- packages/astro/src/index.ts
- packages/core/src/types.ts
- packages/nuxt/src/options.ts
- packages/postcss/src/index.ts
- packages/shared-integration/src/content.ts
- packages/shared-integration/src/context.ts
- packages/shared-integration/src/defaults.ts
- packages/shared-integration/src/deprecation.ts
- packages/vite/src/modes/global/build.ts
- packages/vite/src/modes/vue-scoped.ts
- packages/webpack/src/index.ts
- test/postcss.test.ts
rework #2503, thanks to @sibbng
close #2503
Breaking changes:
- `extraContent` option is renamed to `content`
- `include` option is moved to `content.pipeline.include`
- `exclude` option is moved to `content.pipeline.exclude`
- `content.plain` is removed to `content.inline`
- inline `content` option in PostCSS plugin is removed in favor of the normalized `content` option in `uno.config.ts`
Features:
- `content.inline` now support providing async functions
- set `content.pipeline` to false can disable pipeline extract completely, close #2652
- improve docs
For more details, please refer to https://unocss.dev/guide/extracting#content-sources
> feat!: normalize extraction `content` sources

- packages/preset-wind/src/rules/animation.ts
- test/__snapshots__/postcss.test.ts.snap
- test/assets/output/preset-wind-targets.css
fix all `animate-iteration-count-*` usage, a wider range match should place before other
> fix(preset-wind): wrong output for animate-iteration-count

- packages/svelte-scoped/src/_preprocess/transformClasses/processExpressions.ts
`class="font-bold {grid ? '' :  'mr-1'}"` would not properly find `mr-1` because after finding the first quote it required to consume at least one character before the matching quote, so it would look at `' : '` as a possible utility class and then wouldn't look at `mr-1`. This solves that as seen in the test result.
> fix(svelte-scoped): handle empty string in expression

- docs/integrations/cli.md
- packages/cli/src/cli-start.ts
- packages/cli/src/index.ts
- packages/cli/src/types.ts
This implementation does not check the [`CliEntryItem`](https://unocss.dev/integrations/cli#configurations). I'm not sure what's the desired behavior if `outFile` in config and `--stdout` in CLI both occur.
close #2765
> feat(cli): add `--stdout`

- docs/guide/extracting.md
- examples/vite-vue3/src/App.vue
- packages/inspector/node/index.ts
- packages/shared-integration/src/constants.ts
- packages/shared-integration/src/context.ts
- packages/shared-integration/src/hash.ts
- packages/shared-integration/src/transformers.ts
- test/fixtures.test.ts
- test/fixtures/vite/src/main.css
- test/fixtures/vite/src/main.ts
close #2761 
This PR change: 
- add `@unocss-skip-start` (A) &  `@unocss-skip-end` (B) magic comments.
- In `extract` or `transform` step, will ignore some code that between A and B.
> feat(shared-integration): add skip magic comment

- packages/autocomplete/src/create.ts
- test/autocomplete-fuzzy.test.ts
**Through second search, we can have better ordering**
> perf(autocomplete): better order with fuzzy search.

- docs/guide/extracting.md
> chore(docs): typo

- docs/guide/index.md
There's no anchor to a community section in the [official presets page](https://unocss.dev/presets/) and no community section in that page. There is a dedicated [community presets page](https://unocss.dev/presets/community) in documentation. This PR simply update the link to this page instead of the going to the official presets page.
> docs: fix link to community presets

- packages/vite/src/devtool.ts
🐞 When serving an app with `vite` under a subdirectory (ie `http://localhost/admin/`) and using the unocss devtools feature, it would send the devtool requests to `http://localhost/`. This led to a 404 as the `POST_PATH` which unocss checks for is hardcoded as `/@unocss-devtools-update` and does not take into account a subpath (`/admin/@unocss-devtools-update` !== `/@unocss-devtools-update`)
💅 Prepending the `POST_PATH` with the `base` option from the vite config allows the devtools to send and receive the request to/on the proper path.
> fix(vite): prepend `base` on devtools `POST_PATH`

- packages/preset-web-fonts/src/providers/bunny.ts
This PR adds `display=swap` query to the `bunny` URLs in order to support   `font-display: swap`.
> feat(preset-web-fonts): add font-display: swap support for bunny

- packages/preset-icons/src/core.ts
Please take a look at the image above.
The `uno.config.ts`
``` typescript
import { defineConfig } from "unocss";
import presetIcons from '@unocss/preset-icons'
export default defineConfig({
presets: [
...
presetIcons({
...
}),
],
});
```
When I started the project in the `electron-vite` ([Here](https://github.com/electron-vite)) template repository (Additionally: UnoCSS added), an error occurred!
I don't know what the problem exactly is, but when I ignore to load `undefined loader` it works and has no influence on functions.
> fix(icons): loader does not exist is displayed in case of undefined

- packages/vscode/package.json
Just like `Iconify IntelliSense` or `Code Spell Checker`
> fix(vscode): better languageIds configure

- packages/preset-web-fonts/src/index.ts
- packages/preset-web-fonts/src/providers/bunny.ts
- test/preset-web-fonts.test.ts
Previously, the weights were converted to Number before sorting. This would lead to conversion of string to NaN.
> fix(preset-web-fonts): sort weights as string using localeCompare

- packages/preset-mini/src/_rules/gap.ts
- test/assets/output/preset-mini-targets.css
- test/preset-rem-to-px.test.ts
`grid-gap` was merged with `gap` (which works both with flexbox and grid) a few years back so this PR removes it from the generated CSS. 
`grid-column-gap` (now `column-gap`) and `grid-row-gap` (now `row-gap`) are also removed.
This should fix a few Vite errors that show up when you use flexbox but end up with `grid-gap` in the CSS instead of just `gap`.
As usual I have no idea what I'm doing so it's very possible I may have missed/broken something 😊
> fix(preset-mini): remove grid-gap from generated CSS (deprecated in favor of gap), fix #2642

- packages/reset/tailwind-compat.css
- packages/reset/tailwind.css
Include changes from the original Tailwind reset: https://github.com/tailwindlabs/tailwindcss/pull/10940
TLDR: Prevent font-feature-settings from being overridden by the user agent stylesheet for buttons, inputs, etc.
> feat(reset): sync tailwind resets, adding `font-feature-settings`

- packages/autocomplete/src/utils.ts
- test/utils.test.ts
When the Cartesian product function is passed in an array of length 1, the return value is mistake.
```ts
const a = ['a', 'b', 'c']
cartesian([a])
// we need [['a'],['b'],['c']], not ['a','b','c']
```
This will cause problems with single-length group autocomplete part when fuzzy matching
> fix(autocomplete): cartesian product mistake

- examples/qwik/src/root.tsx
- examples/qwik/src/routes/index.tsx
The current example isn't compatible with Qwik-city, and className is deprecated
-----
<a href="https://stackblitz.com/~/github.com/wmertens/unocss/tree/main/examples/qwik"><img src="https://developer.stackblitz.com/img/review_pr_small.svg" alt="Review PR in StackBlitz Codeflow" align="left" width="103" height="20"></a> _Submitted with [StackBlitz Codeflow](https://stackblitz.com/~/github.com/wmertens/unocss/tree/main/examples/qwik)._
> docs: fix Qwik example

- bench/fixtures/unocss/vite.config.mjs
Use `content.pipeline.include` instead `include` option. The `include` option has been deprecated.
https://github.com/unocss/unocss/blob/93a081200ac88335ec65a20ccb20428230835658/packages/shared-integration/src/deprecation.ts#L11-L12
> chore(bench): instead deprecated `include` option

- package.json
- packages/eslint-plugin/package.json
- packages/eslint-plugin/tsconfig.json
- tsconfig.json
For some reason it seems tsc is using node10 resolution, this PR just excludes eslint-plugin from root typecheck script and includes a new typecheck script in eslint-plugin (that will run from root).
> chore: fix build

- packages/astro/package.json
- packages/unocss/package.json
- pnpm-lock.yaml
Closes #2431.
Currently on `unocss` installs with yarn those warnings are shown:
```
➤ YN0002: │ @unocss/astro@npm:0.54.0 doesn't provide vite (p2c1b4), requested by @unocss/vite
➤ YN0002: │ unocss@npm:0.54.0 [dc3fc] doesn't provide vite (pa8d36), requested by @unocss/vite
```
`@unocss/vite` peer depends on `vite`, but neither `unocss` nor `@unocss/astro` package provide that dependency in any form. Add it as an optional peer dependency to them.
> fix!: add vite as an optional peer dependency to core and astro

- packages/vscode/src/index.ts
I want to be able to load the unocss extension without restarting the whole vscode when installing unocss in a project.
Currently, the `unocss.reload` command is not registered when unocss is not installed in the workspace. 
This is caused by throwing the `➖ No config found in ${cwd}` exception. I rewrote this part of the code to not let the exception be thrown and not affect the original logic.
Additionally, I put registerRoot in the callback of the reload command so that it can check if unocss is installed.
> fix(vscode): reload command

- packages/core/src/utils/countable-set.ts
- test/countable-set.test.ts
Discussed in https://github.com/unocss/unocss/pull/2762#discussion_r1293146766_
Removes duplicated `add()` calls in the child constructor.
> perf(core): imoprove `CountableSet`, add tests

- packages/astro/src/index.ts
fix: #2987 
fix: #2812
re-implement: #2593 
We just align `data-astro-dev-id` with `data-vite-dev-id`
> fix(astro): astro hmr warning and improve performance

- packages/astro/src/index.ts
Fixes: #2987
Here should resolve again with the final path otherwise `vite` plugin transform hooks cannot receive any transform related to `/__uno.css` cause HMR does not work
> fix(astro): astro integration `HMR` not work

- packages/preset-mini/src/_variants/breakpoints.ts
- test/assets/output/preset-mini-targets.css
- test/assets/preset-mini-targets.ts
TailwindCSS uses `max-` instead of `lt-` so it would be nice if we also support that. It helps users coming from TailwindCSS too.
https://tailwindcss.com/docs/responsive-design#targeting-a-breakpoint-range
> feat(preset-mini): Support `max`  breakpoint

- packages/transformer-attributify-jsx/src/index.ts
- test/transformer-attributify-jsx.test.ts
closed #3016
```ts
const id = 1
const str = '<router-link to={`/user/${id}`}/> ..............................................'
const elementRE = /(<\w[\w:\.$-]*\s)((?:'[^>]*?'|"[^>]*?"|`(?:[^>]|[\S])*?`|\{(?:[^>]|[\S])*?\}|[^>]*?)*)/g
for (const i of Array.from(str.matchAll(elementRE)))
console.log(i)
``` 
> It will execute for a few minutes.
```ts
const id = 1
const str = '<router-link to={`/user/${id}`}/> ..............................................'
const elementRE = /(<\w[\w:\.$-]*\s)((?:'[^>]*?'|"[^>]*?"|[\{`]([^>]|[\S])*?[\}`]|[^>]*?)*)/g
for (const i of Array.from(str.matchAll(elementRE)))
console.log(i)
```
> fix(attributify-jsx): support Template Strings

- packages/svelte-scoped/src/_vite/global.ts
Hello! First PR to this repo 😁. Thanks already for all this great tool!
fix #2965
Sveltekit application can't be run if their Vite config contains an SSL plugin (`vite-plugin-mkcert` or `@vitejs/plugin-basic-ssl`)
The `vite dev` command fails shortly with the error:
```
Internal server error: Cannot use 'in' operator to search for 'at' in import * as client_hooks from "/src/hooks.client.ts";
```
Manual test:
1. build the new code: `nr build`
2. `cd example/sveltekit-scoped`
3. manually add to `package.json`, as a dev dependency: `"@vitejs/plugin-basic-ssl": "^1.0.1",`
4. manually add to `vite.config.ts`: `import basicSsl from '@vitejs/plugin-basic-ssl'`  and as the first vite plugin: `basicSsl(),`
5. `pnpm i`
6. `pnpm dev`
7. then browse to https://localhost:5173/ (note the https protocol …
> fix(svelte-scoped): vite dev crash when configured with SSL

- packages/reset/tailwind-compat.css
- packages/reset/tailwind.css
According to my devtools:
'-webkit-text-size-adjust' is not supported by Chrome, Chrome Android, Edge 79+, Firefox, Safari. Add 'text-size-adjust' to support Chrome 54+, Chrome Android 54+, Edge 79+. 
This PR adds the non webkit prefixed property to the reset files.
> fix(reset): '-webkit-text-size-adjust' is not supported issue

- package.json
In pre-commit script, esno from npm cannot be called, use npx call instead
> chore: fix git-hooks

- docs/.vitepress/theme/UnoCSSLayout.vue
- docs/.vitepress/theme/index.ts
- docs/.vitepress/theme/overrides.css
- docs/.vitepress/theme/rainbow.css
- docs/.vitepress/theme/vars.css
- docs/components.d.ts
- docs/package.json
- pnpm-lock.yaml
This PR also includes:
- new radial transition for theme switch
- removed some redundant styles in tabs (code-groups)
- update old `--vp-c-brand` to the new one `--vp-c-brand-1` in all stylesheets
This PR will use the new styles for `::: tip/info/warning/danger`, I don't like them, for example, this is the old warning:
and this is the new one (maybe we can use the old ones, if so ping me, I'll change them, I've changed them in the PWA docs):
> docs: bump to VitePress v1.0.0-rc10

- playground/__play.html
- playground/src/auto-imports.d.ts
- playground/src/components/panel/PanelConfig.vue
- playground/src/components/panel/PanelCustomCss.vue
- playground/src/composables/panel.ts
- playground/src/composables/uno.ts
Related #3065, #3061
Optimized to check whether `transformerDirectives` exists in advance, and give a friendly reminder for it.
See [Playground](https://deploy-preview-3066--unocss.netlify.app/play/?html=DwEwlgbgBAFgtAMwK4BsVQC4FMAeG4DGWAdtgE5QIq5QDOW1B%2BxA9sVlAIZoBcGZnYrTAYwbOABYADFIB8AKChRQkKAFtOCpUpXRseOAFYc6BAHcAjDK7EwG7HABGLJMSJxuGG3c4OCL0jgwYgRgkQ5BHwcQJAFRcQtaLW0lAFVWAGEAZSzFbWAAenAIZJ1iqBYABwBmKUxcfBQAc0ozWrq1C1LtABUYDmDaDEEvcRAsDWIQKABBDBY1MAIobKyoEibgrAA6PJ0iyG7ddQAmSmocKAArJCGwBABPQhJyeoMTkwqaupgWCCwyABeABEVQAHFJgd0dJw9ikoGBCJwyM5iHAUCwmiw4JsMDAkI44Sl9Phgv0yCIidoYGQsAgQTAMBhKrQeAUCrj8Y5tv41AVXCwCLRaPzWELaMCqUphmQmlgMCCAPqOFCCADWkvhUFkhU0cMKxWSBsO8mNJVN5U4jloLBQSGwUGcTIWRigFKajLgdWoCHwdRJz1IAK%2BtVa7WSYwmgmmAHaEUJhqQoHHkGgHlACLd5osAF5W6img4lIA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgD …
> pref(playground): detect transformers to show error

- packages/unocss/package.json
- pnpm-lock.yaml
add vite as devdep in the `unocss` package, otherwise the imported `Plugin` type on line 4:
https://github.com/unocss/unocss/blob/6d760ad804f191a256269a35910bcfb90114e7fe/packages/unocss/src/vite.ts#L4-L19
References the hoisted `vite` package (`shamefully-hoist=true`). The `Plugin` here is different from the `Plugin` from the `return VitePlugin` call. This difference caused a fail in [vite-ecosystem-ci](https://github.com/vitejs/vite-ecosystem-ci/actions/runs/6069325893/job/16463574781#step:8:1157).
> chore(unocss): add vite as devdep

- packages/vscode/src/utils.ts
- test/utils.test.ts
This PR will fix the problem that the `px to rem preview` of the vscode extension does not support important
> fix(vscode): remToPx support important

- docs/.vitepress/content.ts
react example is not present in this repository. but in https://unocss.dev/integrations/#examples it still exist.
> chore: remove invalid link

- docs/package.json
- pnpm-lock.yaml
VitePress rc11 fixes some colors in the local seach: https://github.com/vuejs/vitepress/commit/20f97702680b47eb9675770df4db94a3e3b94ef1#diff-58cdd95c81b6e163b7f99c9e55e08796ffc028c2e34f3c79d2df3dc1640cc423R511
Current unocss.dev search in light mode:
> docs: bump to VitePress v1.0.0-rc11

- examples/sveltekit/package.json
- in examples/sveltekit `@unocss/preset-uno` is referenced in uno.config.ts but it is not declared as dependency
> chore(examples): adds missing dependency to sveltekit example

- examples/sveltekit-scoped/getAllConfigFiles.ts
- examples/sveltekit-scoped/src/shortcuts/logo.ts
- examples/sveltekit-scoped/uno.config.ts
- examples/sveltekit-scoped/vite.config.ts
- packages/svelte-scoped/package.json
- packages/svelte-scoped/src/_preprocess/types.d.ts
- packages/svelte-scoped/src/_vite/config-hmr.ts
- packages/svelte-scoped/src/_vite/createCssTransformerPlugins.ts
- packages/svelte-scoped/src/_vite/index.ts
- packages/svelte-scoped/src/_vite/passPreprocessToSveltePlugin.ts
Closes #2995 by adding a plugin to restart Vite when the config changes or listed dependencies change.
I added example usage. To try out `cd examples/sveltekite-scoped`, install packages and run dev.
> feat(svelte-scoped): add config hmr

- package.json
- pnpm-lock.yaml
This PR simply updates rollup version.
This will fix ecosystem-ci fail that will be caused by https://github.com/vitejs/vite/pull/14238
> chore: update rollup to 3.29.2

- packages/transformer-attributify-jsx/src/index.ts
- test/transformer-attributify-jsx.test.ts
This PR modifies [attributeRE](https://github.com/evanryuu/unocss/blob/main/packages/transformer-attributify-jsx/src/index.ts#L41) to solve transforming error when a class-like HTML element happens to have atomic attributes (not class names).
When the HTML element is like a class name, say `<h1>`, and the tag happens to have atomic attributes such as `text-red`, the transformer will accidentally transform the closing tag in an unexpected way.
Reproduction:
1. [Stackblitz](https://stackblitz.com/edit/vitejs-vite-k49hbr?file=uno.config.ts)
2. [My Github Repo](https://github.com/evanryuu/uno-jsx-repo)
**Code:**
**Error:**
This PR makes the reg will not match the attribute starts with `<` or `</`
> fix(transformer-attributify-jsx): transform error when html element is like a atomic class

- packages/inspector/src/categories.ts
- packages/preset-mini/src/_rules/position.ts
close: #3159 
[mozilla docs](https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content#syntax)
after:
> feat(preset-mini): add justify left & right attrs

- packages/transformer-compile-class/src/index.ts
- test/transformer-compile-class.test.ts
This PR is related to #2866 and will fix the hmr issue for the simple `:uno:` rule.
Currently, the hashed compile class will not trigger `invalidate`, and I personally don't think editing the shared function directly is a good idea. 
Inspired by the `extract` function and [update rule](https://github.com/unocss/unocss/blob/563bc24edd4cf255595970c6ae386a1d602fd9d3/packages/shared-integration/src/context.ts#L88) in createContext method, the easiest and most compatible way to me is to compare the compiled classes and call `invalidate` method just like how the UnoCSS works originally.
> fix(transformer-compile-class): compile class does not update after saving, fix #2866

- docs/guide/presets.md
The presets guide only had docs on how to use presets so I added a link to /config/presets in a Creating presets subheading. (I was looking for it myself)
I'm not sure what the name for the link should be so feel free to change that.
> docs: add link to /config/presets from /guide/presets

- packages/preset-mini/src/_variants/pseudo.ts
- packages/svelte-scoped/src/_preprocess/transformApply/getUtils.test.ts
I added `user-valid` and `user-invalid` pseudo selectors in preset-mini pseudo.ts. No idea if it's supposed to be this easy. Is anything else required?
Tested in playground using
```html
<input required type="email" class="peer w-64 border border-solid user-valid:border-green-600 user-invalid:border-red-600"/>
<span class="w-12 peer-focus:invisible peer-user-invalid:after:content-['❌'] 
peer-user-valid:after:content-['✅']"></span>
```
in Chrome canary.
Fixes https://github.com/unocss/unocss/issues/3180
> feat(preset-mini): add user-valid and user-invalid pseudo selectors

- packages/astro/src/index.ts
close: #2821
Related PR in tailwind: https://github.com/withastro/astro/issues/8044
This issue has been fixed in [vite](https://github.com/vitejs/vite/pull/14465), so we no longer need this code
> fix(astro): remove the code that fixes the css ordering

- docs/integrations/svelte-scoped.md
I've had to refer to this page a few times, and since `hooks.server.js` is not a common file, I always forget where to put it, and have to refer to SvelteKit's docs.
My PR adds a simple change that adds the `src` folder to the code snippet. Alternatively, I suggest linking to SvelteKit docs.
> docs: update `svelte-coped` hooks.server.js location

- test/fixtures/vite-legacy/vite.config.ts
There's a test at https://github.com/unocss/unocss/blob/d0e101d68c9c4492e90053c09030da6690105014/test/fixtures.test.ts#L66-L67 that expects an SVG asset to be emitted. However in Vite 5, SVG assets are also inline-able so this would be inside the CSS file instead.
I updated the Vite config to fix this for now.
> test: fix svg check for vite 5

- packages/vite/src/client.ts
- packages/vite/src/devtool.ts
- packages/vite/src/index.ts
- packages/vite/src/types.ts
> feat(vite): add client fetch mode

- packages/preset-mini/src/_theme/default.ts
- packages/preset-mini/src/_theme/misc.ts
- test/assets/output/preset-mini-targets.css
- test/assets/preset-mini-targets.ts
Due to how tagged pseudo works (`group-x`, etc), it is difficult to weave `@hover` support.
This PR copy one of `media-x` variant default theme (`mouse`) from preset-wind so we can use `media-mouse` variant in preset-mini to add the `@hover` media query without adding the `:hover` pseudo. Note that `media-x` is separate from `group-x`, so to combine you may need to, well, combine the syntax (see test) or use shortcut. I personally think that this combination is better served via shortcut to keep the atomicity of the variant.
Reference: https://github.com/unocss/unocss/blob/5dcc8ceddb7b6acbb06be914b5f1bd3a444c8976/packages/preset-wind/src/theme.ts#L193
This should help #3076 with only preset-mini.
> feat(preset-mini): add default mouse media as alternative to @hover

- packages/svelte-scoped/src/_vite/global.ts
- packages/svelte-scoped/test/fixtures/escaped-unicode.css
- packages/svelte-scoped/test/index.test.ts
> fix(svelte-scoped): escape template literal characters in placeholder replacement

- docs/config/theme.md
- docs/presets/mini.md
- packages/postcss/src/screen.ts
- packages/preset-mini/src/_rules/size.ts
- packages/preset-mini/src/_utils/utilities.ts
- packages/preset-mini/src/_variants/breakpoints.ts
- packages/preset-wind/src/rules/container.ts
- packages/transformer-directives/src/screen.ts
- playground/src/auto-imports.d.ts
- test/preset-mini.test.ts
- test/preset-uno.test.ts
close #2960
In #2960 case, it use breakpoints with a number key as screen point. We use `Object.keys` get all points without correct size sorting.
I can only compare the boundary numbers of points in advance and use an array to maintain regular ordering.
As for points in different units, we can explain them in the documentation and let users align and sort the units themselves.
> fix(preset-mini): use array cache sorted breakpoints

- packages/webpack/src/index.ts
Revert #3256 turn out to be buggy & breaking
> Revert "fix(webpack): escape backslash in css (#3256)"

- packages/preset-mini/src/_utils/mappings.ts
While most example deals with sizes, css' `env()` is more of `var()` not `calc()`
> fix(preset-mini): env may not always output numbers

- packages/cli/src/index.ts
This PR solves the issue: fix https://github.com/unocss/unocss/issues/3262
It does the following:
If both --stdout and --o are used, then watch will display a warning and not proceed.
Either --stdout or -o can be used or not, as the default is to create a uno.css file in the root directory.
-w remains the same.  Can be used or not.
> fix(cli): improve error output

- examples/vue-cli4/vue.config.js
- examples/vue-cli5/vue.config.js
https://github.com/webpack-contrib/mini-css-extract-plugin/blob/master/src/hmr/hotModuleReplacement.js#L150
Since `unocss` generates new css files with `contenthash` when files update and  `mini-css-extract-plugin` updates all css files link with query, we have to remove `contenthash` when running in development mode.
FIX: #2144
> fix: Not using contenthash in development mode has enabled HMR to work properly.

- packages/preset-mini/src/_utils/handlers/handlers.ts
- test/assets/output/preset-mini-targets.css
This PR removes a `num === 0` check in the px handler which returned `0` which broke a bunch of offset-utilities (`ring-offset-0`, `underline-offset-0`). This means it returns `0px` now and these utilities work again.
The `num === 0` check is still there for the rem handler so `inset-0` still gives a `0` result. (I'm not sure why this is better than 0px though)
It's possible there's a better way to fix this, in that case feel free to close this PR.
fixes https://github.com/unocss/unocss/issues/3196
> fix(preset-mini): remove num === 0 in px handler to fix offset utility issues

- packages/preset-mini/src/_rules/grid.ts
- test/assets/output/preset-mini-targets.css
- test/assets/preset-mini-targets.ts
I noticed I made a mistake in https://github.com/unocss/unocss/pull/3284 by writing `grid-template-cols` in the rule instead of `grid-template-columns` 😱
This PR fixes that so the resulting CSS is valid. Would probably be helpful to have some tests for these too but I have no idea where to add them.
> fix(preset-mini): change grid-template-cols to grid-template-columns

- docs/.vitepress/content.ts
- docs/.vitepress/theme/components/ContentExample.vue
- docs/.vitepress/theme/components/ContentExamples.vue
- docs/components.d.ts
- docs/integrations/vite.md
- examples/vite-solid/src/App.tsx
- examples/vite-solid/vite.config.ts
- playground/src/auto-imports.d.ts
This PR includes:
- add ContentExample to allow use it in Vite integration: ContentExamples updated properly
- included missing vite and webpack icons in the content module
- add ContentExample in Vite integration per framework
- add VanillaJS / TypeScript section to Vite integration to include js/ts in the pipeline: link to **Extracting from Build Tools Pipeline**
- updated Solid example, latest version doesn't support `className` and the `count` access was wrong (it is a Solid state, use the function): updated also Vite configuration file, `vite-plugin-solid` needs to be registered after UnoCSS plugin, `shortcuts` not working
- update Solid entry in Vite integrations to change the plugin order
> docs: update Vite integration

- packages/vscode/src/contextLoader.ts
- packages/vscode/src/index.ts
https://github.com/unocss/unocss/commit/64b3461b3d241521d02cb4d1d87a75e4e8aa3451#diff-d56e4c8975b25ab91eed38d6ea0406f9f1668a415cd116d334929ea8d28d1276L21
https://github.com/unocss/unocss/commit/64b3461b3d241521d02cb4d1d87a75e4e8aa3451#diff-d56e4c8975b25ab91eed38d6ea0406f9f1668a415cd116d334929ea8d28d1276R41
It should determine if the configuration file exists before registering functions.
> fix(vscode): avoid register functions without config files

- packages/runtime/src/index.ts
在使用 Web Components 封装的组件中使用时, 应该扫描一个指定的元素, 而不是 body 元素
增加了一个选项, 支持配置扫描的元素
> feat(runtime): custom rootElement config

- packages/inspector/src/analyzer.ts
- packages/preset-mini/src/_rules/behaviors.ts
- packages/preset-mini/src/_rules/border.ts
- packages/preset-mini/src/_rules/color.ts
- packages/preset-mini/src/_rules/decoration.ts
- packages/preset-mini/src/_rules/ring.ts
- packages/preset-mini/src/_rules/shadow.ts
- packages/preset-mini/src/_rules/svg.ts
- packages/preset-mini/src/_rules/typography.ts
- packages/preset-mini/src/_theme/types.ts
- packages/preset-mini/src/_utils/utilities.ts
- packages/preset-wind/src/rules/background.ts
- packages/preset-wind/src/rules/behaviors.ts
- packages/preset-wind/src/rules/divide.ts
- packages/preset-wind/src/rules/filters.ts
- packages/preset-wind/src/rules/placeholder.ts
- packages/preset-wind/src/variants/placeholder.ts
- test/preset-mini.test.ts
Close #3329 
Not all rule get their own theme, but they mostly fall back into a mostly closest property (ex. ring-x: borderColor -> colors). Please let me know if those should be their own color instead (ring-x: ringColor -> colors), or have multiple fallbacks (ring: ringColor -> borderColor -> colors).
Also, netlify is failling on the docs' vitepress. Upgrading should fix the issue
> feat(preset-mini, preset-wind): Use separate theme for some rule colors

- packages/core/src/config.ts
This PR will enable preset to support blocklist
In this way we can use preset to do some style constraints, just like `eslint`
> feat(core): preset support blocklist

- packages/preset-mini/src/_rules/static.ts
- test/assets/output/preset-mini-targets.css
- test/assets/preset-mini-targets.ts
This PR adds the `.text-pretty` utility to UnoCSS, implementing [text-wrap: pretty](https://developer.chrome.com/blog/css-text-wrap-pretty/);. This feature, supported in Chrome from version 117 as per [MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/CSS/text-wrap) and [CanIUse](https://caniuse.com/?search=text-pretty), allows for aesthetically pleasing text wrapping and avoids lingering words.
- New `.text-pretty` class with text-wrap: pretty;.
> feat(preset-mini): add text-pretty css property

- packages/inspector/client/components/ModuleInfo.vue
Before: <img width="1305" alt="image" src="https://github.com/unocss/unocss/assets/42139754/7a9a8f64-7bce-4f67-b61f-9f6c7d42a27b">
After:
> fix(inspector): codemirror matched utilities miss highlight

- packages/vscode/src/index.ts
close: #3426
The original logic is to add all directories with `package.json` to the rootCache, and the outermost ones will also be added. In this way, when matching paths, the matching path of switching sub-repositories will always hit the outermost root path, causing the registration of other sub-repositories to be skipped. Now only the root path where `uno.config` is located is added to the rootCache
> fix(vscode): registerUnocss cache rules

- .github/workflows/ci.yml
Refer to https://github.com/backstage/backstage/issues/21738
> chore(ci): freeze node version to skip ci error

- packages/vscode/src/configuration.ts
- packages/vscode/src/contextLoader.ts
- packages/vscode/src/selectionStyle.ts
A little improvement  (**rem to px preview**) to `vscode selection style`
> feat(vscode): add rem to px preview on selection style

- packages/nuxt/src/index.ts
- packages/nuxt/src/options.ts
- packages/nuxt/src/types.ts
Reverts unocss/unocss#3448
Sorry, cause my lack of some tests, this error appeared.
I will consider another way to implement `injectposition`.
Related #3472 #3468
> fix(nuxt): temporary revert #3448

- docs/presets/attributify.md
In https://unocss.dev/presets/attributify, make the "transformer-attributify-jsx" link point to https://unocss.dev/transformers/attributify-jsx instead of the github source code
> doc(attributify): point transformer-attributify-jsx link to doc page

- packages/core/src/types.ts
Since `plain` has been marked as `deprecated` and replaced by `inline`,  the comment should be updated (which also affects the documentation) to avoid confusion.
https://unocss.dev/config/#content
> docs: update `content` source comment(also docs)

- packages/preset-attributify/src/jsx.ts
Generally `position="absolute"` makes better sense than `pos="absolute"` if user wants to use key-value paired attributify mode.
It's currently forced to key-value pair because of #3471
> fix(attributify): add `position` type for jsx

- packages/preset-mini/src/_variants/breakpoints.ts
- packages/preset-mini/src/_variants/container.ts
- test/assets/output/preset-mini-targets.css
Fixes #2913.
The `@container` queries are not outputted in the same position as before, not sure if that's a problem or not.
Named `@container` queries are moved to the end, because that's what already appeared to happen before this change.
> fix(preset-mini): order custom container variants as given

- packages/webpack/src/index.ts
---
Unplugin will also normalize absolute path since [0.9.0](https://github.com/unjs/unplugin/pull/145/files#diff-2b106437404a793ee5b8f3823344656ce880f698d3d8cb6a7cf785e36fb4bf5cR27) .
ref:
- https://github.com/unocss/unocss/pull/2296
---
- On **Windows** .
- Use [vue-cli5](https://github.com/unocss/unocss/tree/main/examples/vue-cli5) with default [css.extract](https://cli.vuejs.org/config/#css-extract) ( `false` ) .
```diff
- css: {
-   extract: process.env.NODE_ENV === 'development'
-     ? {
-         filename: 'css/[name].css',
-         chunkFilename: 'css/[name].css',
-       }
-     : true,
- },
```
You can see it when debugging:
- The **path** in [updateModules](https://github.com/unocss/unocss/blob/08c1d16484ad506b2e477a04fe0d0bea993e5259/packages/webpack/src/index.ts#L168C15-L168 …
> fix(webpack): HMR not work on Windows

- packages/preset-attributify/src/jsx.ts
Add `size="..."` and `px` / `py` , `mx` \ `my`
> fix(attributify): add some missing types for jsx

- packages/preset-wind/src/index.ts
- packages/preset-wind/src/postprocessors/important.ts
- test/assets/output/preset-wind-important-string.css
- test/preset-wind.test.ts
related: https://github.com/unocss/unocss/pull/3484
fix: https://github.com/unocss/unocss/issues/3474
> fix(preset-wind): handle pseudo selector correctly when using `important` string option

- packages/preset-icons/package.json
- pnpm-lock.yaml
To include new node icon loader helper: `createExternalPackageIconLoader`
> chore: update iconify utils package

- examples/next/shims.d.ts
Hello team of Unocss,
I have taken the trouble to correct a problem regarding the import of the `@unocss/preset-attributify` module, since in the nextjs project that package is not installed, which in my opinion can be confusing... So based on the Un Css documentation you can also use the `preset-attributify` extension from the main `unocss` package.
example: 
*before*:
```ts
import type { AttributifyAttributes } from '@unocss/preset-attributify'
declare module 'react' {
interface HTMLAttributes<T> extends AttributifyAttributes {}
}
```
*after*:
```ts
import type { AttributifyAttributes } from 'unocss/preset-attributify'
declare module 'react' {
interface HTMLAttributes<T> extends AttributifyAttributes {}
}
```
Thanks for your time 🙏
> fix: import of the example with nextjs is corrected

- packages/preset-mini/src/_rules/variables.ts
- packages/preset-mini/src/_variants/default.ts
- packages/preset-mini/src/_variants/misc.ts
- test/assets/output/preset-mini-targets.css
- test/assets/preset-mini-targets.ts
Inspiration comes from https://github.com/unocss/unocss/pull/3204
not limited to [], now can support this
```
'bg-[--css-spacing,theme(spacing.sm)]',
'text-[theme(spacing.sm)]',
'c-[theme(colors.red.500/50%)]',
```
> feat(preset-mini): support for css property with the theme()

- packages/webpack/src/index.ts
1. `optimizeAssets` was deprecated in favour of `processAssets`. thus prefer `processAssets` to `optimizeAssets` if available.
2. rspack only implements `processAssets`
related: https://github.com/web-infra-dev/rspack/issues/4938
> chore(webpack): use processAssets hooks for webpack 5 instead of optimizeAssets as of deprecation

- packages/preset-mini/src/_rules/color.ts
- test/assets/output/preset-mini-targets.css
- test/assets/preset-mini-targets.ts
This PR makes arbitrary gradients in bg-[] work by returning background-image instead of background-color when linear-gradient/conic-gradient/radial-gradient are detected.
fixes unocss#3581
before:
after:
```
<div class="bg-[linear-gradient(45deg,#0072ff,#00d2e8,#04fd8f,#70fd6c)] border-1 h-64 w-64 flex items-center text-center"></div>
<div class="bg-[conic-gradient(red,blue)] border-1 h-64 w-64 flex items-center text-center"></div>
<div class="bg-[radial-gradient(red,blue)] border-1 h-64 w-64 flex items-center text-center"></div>
```
> fix(preset-mini): handle arbitrary gradients correctly

- packages/preset-mini/src/_variants/pseudo.ts
This PR adds a variant `popover-open` to add support for the experimental popover-open pseudo class. This can then be used to have two animations, one that plays when the popover is opened and one that is played when it is closed. (and more)
For transitions to work correctly when using opacity and so on support for @starting-style will have to be added somehow: https://developer.mozilla.org/en-US/docs/Web/CSS/@starting-style
fixes #3605
example:
```
<button popovertarget="my-styled-popover">Open styled Popover</button>
<div class="m-0 top-20 p-4 mx-auto animate-[custom-slide-out_0.4s_ease] 
popover-open:animate-[custom-slide-in_0.4s_ease]
backdrop:bg-blue-900 transition-all" 
popover id="my-styled-popover">Greetings, one and all! (styled popover)</div>
```
custom CSS:
```
@keyframes …
```
> feat(preset-mini): add popover-open pseudo variant

- packages/preset-mini/src/_utils/utilities.ts
- test/color.test.ts
close #3515 
- Fix the issue of inset not working
- Fix incorrectly parsing strings like `#fff 0` as color value
- Support correctly parsing the first part as a color value in the format `shadow="[#000_1px_0_0_0]"`
> fix(preset-mini): fixed shadow inset not working

- docs/config/index.md
- docs/config/layers.md
- packages/core/src/generator/index.ts
- packages/core/src/types.ts
- test/__snapshots__/use-css-layer.test.ts.snap
- test/use-css-layer.test.ts
fix #3583
fix #3384
Allows the internal layers to be output nested inside `@layer layerName {}`
Probably out of scope for this PR but one thing to consider is the interaction with the [layer variant in the mini preset](https://github.com/unocss/unocss/blob/3e1cce549e4ee3f35be53801a0faa8dcfa5496c1/packages/preset-mini/src/_variants/misc.ts#L21-L39).
With the new option enabled, this variant will now be creating sublayers, not root-level layers. Users would need to use the 'uno-layer' variant instead.
> feat(core): add option to output the internal layers as CSS Cascade Layers

- packages/vscode/src/utils.ts
At present, vscode does not seem to support the use of rgb (r g b / a) form. I think it can be temporarily converted to rgba form and give color tips. If vscode supports it later, it will be removed.
> fix(vscode): completion color

- docs/config/rules.md
This PR alters the Rules explanation at the top to make it a bit clearer and adds a note that explains that CSS property syntax (`font-weight` instead of `fontWeight`) is used.
Feel free to edit.
fix #3635
> docs: in Rules add note explaining that CSS property syntax is used, alter Rules explanation

- packages/preset-mini/src/_utils/handlers/handlers.ts
> fix(preset-mini): Cannot read properties of undefined (reading 'split')

- packages/preset-mini/src/_utils/handlers/handlers.ts
- packages/preset-mini/src/_utils/handlers/regex.ts
- test/preset-mini.test.ts
I think we should keep the same with tailwind
> feat(preset-mini): keep unitOnlyRE same with tailwind

- packages/postcss/package.json
Part of https://github.com/unocss/unocss/issues/3675
> fix(postcss): move to ESM first + dual ESM/CJS + missing `@unocss/postcss/esm` subpackage export

- packages/webpack/src/index.ts
fix: #3652 
Repeated calls to the `getCssEscaperForJsContent` function result in multiple escapes of special characters, leading to errors when Webpack invokes the `eval` function.
The incorrect output is:
`.after\\\:content-empty::after{content:\\"\\";}`
And the correct output should be:
`.after\:content-empty::after{content:\"\";}`
> fix(webpack): correctly output CSS string

- packages/postcss/src/esm.ts
Hello, Unocss team, thank you for your work. 
I encountered a `"too many open files"` error when using `@unocss/postcss`. This issue often occurs on Windows systems when too many files are opened simultaneously, leading to build failures.
I noticed that tailwindcss also had this problem and has already been fixed. 
So I submitted a PR to address this issue in the same way as tailwindcss.
[Async PostCSS Plugin on Windows 10 with too many parsed files (~10k) yields a webpack error (EMFILE: too many open files) ](https://github.com/tailwindlabs/tailwindcss/issues/12069)
[Batch reading content files to prevent too many open files error ](https://github.com/tailwindlabs/tailwindcss/pull/12079) 
https://github.com/tailwindlabs/tailwindcss/blob/master/src/lib/expandTailwindAtRules.js#L142
> fix(postcss): too many open files error

- .gitattributes
When submitting PR 3717 after running tests on my local (I know I can fix it using git commands...):
> chore: include `.gitattributes`

- packages/preset-mini/src/_rules/border.ts
Currently we get some arbitrary numbers in autocomplete for `rounded` which disregards what user puts into `borderRadius` in `theme`.
It also does not suggest default values that are set in the default theme:
https://github.com/unocss/unocss/blob/main/packages/preset-mini/src/_theme/misc.ts#L49
https://github.com/unocss/unocss/blob/main/packages/preset-mini/src/_rules/border.ts#L127
With the change from this PR, autocomplete will now suggest proper values, both default and those overridden by the user.
Since this only targets `autocomplete` it's backwards compatible, both `number` and `predefined` values still work, although `autocomplete` will now only suggest the latter.
> fix(preset-mini): use `borderRadius` from theme to autosuggest `rounded` values

- examples/vite-react/package.json
Open the example of `vite-react` on [stackblitz](https://stackblitz.com/edit/unocss-unocss-y7gcng?file=package.json), the project throw an error:
> chore: fix the example of `vite-react`

- packages/preset-mini/src/_variants/children.ts
- packages/preset-mini/src/_variants/default.ts
- packages/preset-mini/src/_variants/index.ts
- test/__snapshots__/autocomplete.test.ts.snap
- test/assets/output/preset-mini-targets.css
- test/assets/preset-mini-targets.ts
Tailwind added [`*:`](https://tailwindcss.com/docs/hover-focus-and-other-states#styling-direct-children) modifier for selecting children since [v3.4](https://tailwindcss.com/blog/tailwindcss-v3-4#style-children-with-the-variant).
```html
<div class="*:text-red-500">
<div>red text</div>
<div>red text</div>
<div>red text</div>
</div>
<div class="*-text-red-500"></div>
```
> feat(preset-mini): add children variant (*-{modifier})

- packages/unocss/astro.d.ts
- packages/unocss/index.d.ts
- packages/unocss/package.json
- packages/unocss/postcss.d.ts
- packages/unocss/preset-attributify.d.ts
- packages/unocss/preset-icons.d.ts
- packages/unocss/preset-mini.d.ts
- packages/unocss/preset-tagify.d.ts
- packages/unocss/preset-typography.d.ts
- packages/unocss/preset-uno.d.ts
- packages/unocss/preset-web-fonts.d.ts
- packages/unocss/preset-wind.d.ts
- packages/unocss/vite.d.ts
- packages/unocss/webpack.d.ts
- scripts/dist-verify.ts
- scripts/postbuild.ts
This PR will revert changes in `.cjs` files, patching `d.ts` and `d.cts` instead.
I need to check a few packages, rn next example working with these changes (postcss).
(Maybe we can patch only postcss packages, there is no way yet to configure `postcss` plugin in Next and Webpack (?) with `.default` suffix: `unocss/postcss` and `@unocss/postcss`)
The `dist-verify.ts` script is wrong (in this PR)...
/cc @kwaa
We also have some problems when using old ESLint: check #3751
> fix(cjs)!: remove `.default` suffix from d.ts and d.cts files

- packages/vite/src/modes/global/build.ts
- packages/vite/src/modes/global/dev.ts
fix #3609 
The reason is that the `@import` statement is wrapped in a layer, causing it not to precede all `CSS` rules.
I have conducted tests locally and have not yet found any issues. If it may cause other problems, I would appreciate your guidance.
> fix(vite): move @import before other rules

- packages/shared-integration/src/layers.ts
close: #3758
This change can fix the string style conflict problem caused by hot update, but the preset-typography style is not loaded for the first time, and the style takes effect only after hot update. It seems to be another bug.
> fix(shared-integration): getCssEscaperForJsContent replace conflict

- docs/integrations/postcss.md
The unocss dependency is necessary to run with PostCSS, but this is not clearly stated in the documentation.
> Include unocss package in postcss installation command

- docs/transformers/attributify-jsx.md
It is possible to import this transformer directly from unocss. It is not needed to install separately.
If this is approved, I can add this tip to the other transformers that are included with unocss as well.
> docs: add install tip

- docs/transformers/compile-class.md
- docs/transformers/directives.md
- docs/transformers/variant-group.md
This PR adds install tips for the transformers that are now included in `unocss`
> docs: add install tips for transformers

- examples/nuxt3-layers/.npmrc
- examples/nuxt3-layers/.stackblitz.mjs
- examples/nuxt3-layers/app.vue
- examples/nuxt3-layers/base/nuxt.config.ts
- examples/nuxt3-layers/base/uno.config.ts
- examples/nuxt3-layers/nuxt.config.ts
- examples/nuxt3-layers/package.json
- examples/nuxt3-layers/ui/nuxt.config.ts
- examples/nuxt3-layers/ui/uno.config.ts
- packages/nuxt/src/index.ts
- packages/nuxt/src/types.ts
Closes #3837 
Automatically merges configs from each layer and generates `/.nuxt/uno.config.mjs` file based on the Nuxt config's `extends` list. Then  the generated config is passed to the Vite/Webpack plugin.
> feat: nuxt layers support

- packages/vite/src/modes/global/build.ts
close: #3822
The root problem is `chokidar`'s `watch` will prevent exiting. In `vitest`. we don't need to `watch` anything 
https://github.com/unocss/unocss/blob/f24c75371366f7b801b84f11e01043bdb3b3f84f/packages/shared-integration/src/content.ts#L43-L61
> fix(vite): using astro integration in vitest causes hangs

- docs/config/layers.md
- test/__snapshots__/use-css-layer.test.ts.snap
- test/use-css-layer.test.ts
close #3864 
- Update the `outputToCssLayers` example
- Add a unit test for change CSS layer names
> docs: update the outputToCssLayers example

- docs/integrations/nuxt.md
- examples/nuxt3-layers/uno.config.ts
- packages/nuxt/src/index.ts
Related https://github.com/unocss/unocss/issues/3837
https://github.com/unocss/unocss/pull/3838 added logic to merge **ALL** `uno.config`s from Nuxt layers and generate `./.nuxt/uno.config.mjs`. 
**Problem:**
Because Eslint, VSCode plugins and other tools rely on `uno.config` file, we need to tell them to look for the new location(`./.nuxt`). While this can be done for Eslint (settings->unocss->configPath), implementing a new option for VSCode, JetBrains etc. will kill DX.
This PR skips the root `uno.config` file when merging configs from Nuxt layers, so user should manually reexport merged config from `./.nuxt/uno.config.mjs` and other tools will work as usual:
```ts
// uno.config.ts
import config from './.nuxt/uno.config.mjs'
export default config
```
> feat(nuxt): skip the root `uno.config` when merging

- playground/src/components/Playground.vue
- playground/src/components/Preview.vue
We need to use the resize from the split panel instead `isResizing` from iframe when disabling iframe pointer events.
closes #3932
> fix(playground): resizing using horizontal resizer

- docs/integrations/nuxt.md
The sample is outdated as the import is now available directly from `unocss` and the signature of function `mergeConfigs` takes an array of configs instead of what the existing example states.
> docs: Fix an example code with nuxt merge config sample

- packages/preset-web-fonts/package.json
This PR adds `typesVersions` to resolve types in node10 (missing in the original PR #3962):
> fix(web-fonts): missing `local` node10 types

- docs/presets/web-fonts.md
See https://unocss.dev/presets/web-fonts#serve-fonts-locally
> docs: fix vitepress md typo. Vitepress use `info` instead of `note`.

- packages/shared-integration/src/defaults.ts
> fix(shared-integration): defaultIdeMatchInclude String literals

- packages/shared-integration/src/context.ts
Related to #3978, but it's hard to check whether this PR can fix it.
`flushTask` can be asynchronously called for multiple times at the same time, and previously, if this happens, the `tasks` array would be spliced twice - which may cause problems of losing styles.
> fix(shared-integration): prevent potential data race in `flushTask`

- docs/.vitepress/theme/components/RainbowAnimationSwitcher.vue
The rainbow animation switcher should be wrapped using ClientOnly, otherwise on page refresh won't be updated when disabled (disable animation and refresh the page in unocss.dev)
> docs: fix rainbow animation switcher

- packages/svelte-scoped/src/_vite/index.ts
This PR fixes an error caused by  `const ready = reloadConfig();` (that called `loadConfig()`) being run before `const loadConfig = createRecoveryConfigLoader();`
https://github.com/unocss/unocss/pull/3953 didn't really solve the main issue in Svelte Scoped because destructuring here:
`const { config, sources } = await loadConfig(process.cwd(), configOrPath)`
won't work when the returned value of loadConfig is undefined. 
I'm also not sure how it's supposed to work in here:
```ts
try {
const config = await loadConfig(cwd, configOrPath, extraConfigSources, defaults)
lastResolved = config
return config
}
catch (e) {
if (lastResolved) {
console.error(e)
return lastResolved
}
throw e
}
```
If `lastResolved` is only set when `loadConfig()` didn't give an error it seems to me like
```ts …
```
> fix(svelte-scoped): make sure createRecoveryConfigLoader() runs before reloadConfig()

- docs/integrations/nuxt.md
This PR adds `unocss` to nuxt integrations docs for less confusion.
> docs(integrations): add unocss to nuxt docs

- packages/svelte-scoped/src/_preprocess/transformApply/getUtils.test.ts
This PR replaces the hard coded utility count value in a Svelte Scoped test with the actual returned utility count from `result`. The utility count isn't what's being tested here and this test fails in any PR that adds utilities. (for example https://github.com/unocss/unocss/pull/3997)
> test(svelte-scoped): replace hard coded utility count value with utility count from the returned result

- alias.ts
- tsconfig.json
There seems to be an error in the configuration of the `@unocss/inspector` path in tsconfig.json. Which result in the error `Could not find a declaration file for module '@unocss/inspector'` occurs in the `index.ts` file located at `unocss/packages/vite/src/`.
> fix(@unocss/inspector): fix Typescript lookup paths error

- packages/preset-mini/src/_rules/position.ts
Add logical support for `float` and `clear`: `float-start`, `float-end`, `clear-start`, and `clear-end`. [Tailwind has added these](https://tailwindcss.com/docs/float).
> feat(preset-mini): support `(float|clear)-(start|end)`

- docs/.vitepress/theme/components/RainbowAnimationSwitcher.vue
Firefox also applying rainbow animation, this PR just removes the style to display the switcher.
> docs: display rainbow switcher in Firefox

- docs/integrations/vscode.md
Testing some repo with icons the extension not working and found this comment from Anthony: https://github.com/unocss/unocss/issues/692#issuecomment-1064426263
> docs(vscode): include `vscode-iconify` extension hint for icons preset

- examples/nuxt3-layers/nuxt.config.ts
I've noticed that the Nuxt Example and the Nuxt Layers Example look different. This PR fixes that.
https://stackblitz.com/github/unocss/unocss/tree/main/examples/nuxt3
https://stackblitz.com/github/unocss/unocss/tree/main/examples/nuxt3-layers
> docs: nuxt-layers example

- docs/config/theme.md
- docs/presets/mini.md
> docs: add descriptions of `breakpoints` and `extendTheme`

- docs/.vitepress/config.ts
- docs/.vitepress/theme/index.ts
- docs/package.json
- pnpm-lock.yaml
This PR add [vitepress-plugin-group-icons](https://github.com/yuyinws/vitepress-plugin-group-icons) to enhance the readability for `code-group`:
> docs: add code group icon

- packages/svelte-scoped/src/_vite/index.ts
The addition in #4071 breaks svelte-scoped since there's a condition to check for the presence of transformers within the config.
Empty arrays are still truthy in JS; this fixes it.
> fix(svelte-scoped): fix error check

- packages/preset-mini/src/_theme/transition.ts
- test/__snapshots__/postcss.test.ts.snap
- test/assets/output/preset-mini-targets.css
- test/assets/output/preset-wind-targets.css
- test/assets/output/transformer-directives-apply-with-important.css
- test/assets/output/transformer-directives-apply.css
- test/cases/preset-attributify/case-2/output.css
This PR removes `outline-color` from `transition-colors` since it causes problems with elements that don't have a normal outline color but use `focus:outline-none` or `focus-visible:outline-none` which then causes an ugly flashing black outline. Some libraries ended up using `focus:outline-color` without (or instead of) setting a base transparent outline color because of the Tailwind documentation.
It is possible that Tailwind changes this behavior and the documentation on 4.0 release, at that point we can figure out if there's a better fix.
fixes #4086
> [!TIP]
> If you want to include `outline-color` as a transition property again you can just add `transition-outline-color` in addition to `transition-colors`.
> fix(preset-mini): remove outline-color transition property from transition-colors

- docs/config/theme.md
Added an example of  being able to set a default value for nested colors as it is not mentioned even in the tailwind theme documentation but it is quite handy.
> docs: Update theme.md

- packages/inspector/client/theme.ts
fix light mode playgorund selection background
Before: 
preview: https://unocss.dev/play/
After:
preview: https://deploy-preview-4107--unocss.netlify.app/play/
> style(play): fix light mode playground selection background 

- packages/extractor-pug/src/index.ts
this is a quick and dirty fix, as [svelte-preprocess](https://github.com/sveltejs/svelte-preprocess/blob/main/docs/preprocessing.md#auto-preprocessing-options) allows setting an arbitray `markupTagName` instead of "template".
todo: should really make option to adjust the `regexVueTemplate`.
> feat(extractor-pug): make extractor-pug work with `svelte`

- docs/config/layers.md
This PR adds some info about creating layers using variants in the `config layers` docs instead of in the preset docs. There seems to be a lot of people who don't realize that `uno-layer:` exists so adding this in the `config layers` docs could help.
> docs(config): layers using variants

- packages/core/src/generator/index.ts
- packages/core/src/types.ts
- packages/core/test/__snapshots__/extended-info.test.ts.snap
- packages/core/test/rule-symbols.test.ts
This PR adds `symbols.layer` which can be used to specify a layer either with an string/function or a regex match. `symbols.layer` does not make it possible to change the order of the layer, for that use `layers:` as before.
```ts
rules: [
[/^color-(.*)$/, function * ([, color], ctx) {
yield {
color,
[ctx.symbols.layer]: color,
}
}],
],
```
`color-red`:
```css
"/* layer: red */
.color-red{color:red;}"
```
fixes #4131
> feat(core): add symbols.layer

- docs/config/rules.md
This PR adds `symbols.layer` in the rules docs to actually explain what it does, I forgot this in the other PR.
> docs(rules): explain symbols.layer in symbols docs

- .github/workflows/pkg.pr.new.yml
Only show templates to avoid long comments.
Reference: https://github.com/stackblitz-labs/pkg.pr.new/pull/172
> ci: use `--only-templates`

- README.md
- docs/.vitepress/config.ts
- docs/.vitepress/contributors.ts
- docs/index.md
This PR:
- Adds links to the tutorial in the README, a CTA link and in the nav in the index. Not too sure if it should be everywhere, feel free to edit. Link to the repo itself in case anyone wants to contribute is https://github.com/henrikvilhelmberglund/unocss-tutorial
- Adds myself to the team member list. 😊
> docs: add tutorial links update contributors

- packages/core/test/extractor.test.ts
- packages/extractor-arbitrary-variants/src/index.ts
Fixes #4105
Changes in #3875 caused some previously uncaptured arbitrary variants to be processed by Uno. In case of #4105 during SSR, Vue encode HTML entities like that:
```tsx
return (_ctx: any,_push: any,_parent: any,_attrs: any) => {
_push(`<div${_ssrRenderAttrs(_attrs)}><h1 class="after:content-[&#39;&#39;] w-[12px]">Bug Reproduction</h1></div>`)
}
```
Uno thinks `after:content-[&#39;&#39;]` is a different candidate than `after:content-['']` and generates another utility class. But it generates invalid code. Uno should have been aware of it's processing a string that has encoded html entity or at least shouldn't have been generating an invalid code. There may be other false positive (but valid) candidates UnoCSS generating in production code. But I don't have an example in my hand …
> fix(extractor-arbitrary-variants): skip extracting encoded html entities

- packages/nuxt/src/index.ts
Fixes #4079
My guess is something have changed about when Nuxt call hooks or it doesn't await async hook functions. I have come to that conclusion because adding `await loadUnoConfig()` right before the `vite:extend` hook call fixes the issue.
> fix(nuxt): resolve config in advance

- packages/postcss/src/esm.ts
Fix UnoCSS HMR not working when use `@unocss/postcss` because postcss dependency is not added correctly.
Related PR: https://github.com/unocss/unocss/pull/4048/files#diff-4693bd37b5c3bdb6333760a51bd95d59c108fe0893e24e1237babd281d8b01e4R138-R146
fix: https://github.com/web-infra-dev/rsbuild/issues/3528
> fix(postcss): postcss dependency should always be added

- packages/preset-wind/src/rules/background.ts
- test/__snapshots__/postcss.test.ts.snap
- test/assets/output/preset-wind-targets.css
- test/cases/preset-attributify/case-2/output.css
based off of this tailwind change https://x.com/adamwathan/status/1846985442148946180. I'm not sure if this should be considered a breaking change. 
in this image, the top is oklch and the bottom is sRGB
Also, this updates the bg-gradient-shape-* class but I can not figure out how to use it to make sure it's working as intended.
> feat(preset-wind): default to oklch for gradients

- packages/svelte-scoped/src/_preprocess/transformClasses/processExpressions.test.ts
- packages/svelte-scoped/src/_preprocess/transformClasses/processExpressions.ts
> fix(svelte-scoped): improve class regex for ternary expressions

- docs/config/rules.md
As `vh` and `dvh` are usually applied to `height` instead, I think the current example using `width` may be a bit weird.
>  docs(example): change a bit the example of CSS fallback

- packages/core/test/extractor.test.ts
- packages/extractor-arbitrary-variants/src/index.ts
- packages/preset-mini/src/index.ts
See #4235 for further details.
This PR aligns the arbitrary variant extractor with the others and makes it callable.
Note the docs already show it as callable, so they do not need to be updated.
> refactor(extactor-attributify)!: make arbitrary variants extractor callable

- packages/preset-icons/src/core.ts
close: #4148 
support  captital letter in className
> fix(preset-icons): support captital letters in className

- packages/preset-icons/src/core.ts
This PR checks if the collection name is valid before load icon SVG data.
With class `i-foo-bar-baz`, presetIcons will try to install icon data order by order in bellow and got 3 errors.
1. `@iconify-json/foo-bar-baz`
2. `@iconify-json/foo-bar`
3. `@iconify-json/foo`
#2531
> fix(preset-icons): validate collection name before load icon svg data

- packages/autocomplete/src/create.ts
- packages/core/src/generator/index.ts
- packages/core/src/types.ts
- packages/core/test/variants.test.ts
- packages/eslint-plugin/src/worker.ts
- test/preset-attributify.test.ts
This PR enables variants to return an array that branching one utility to match multiple rules.
This PR contains breaking change on low level API, as `generator.matchVariants()` now always return an array.
> feat(core)!: allow variants to return multiple results

- docs/presets/community.md
More details on https://www.npmjs.com/package/css-fade 
css-fade has UnoCSS, TailwindCSS, and vanilla CSS exports which is why it doesn't have an unocss- prefix.
> docs: add css-fade preset to community.md

- packages/shared-integration/src/defaults.ts
> fix(shared-integration): defaultIdeMatchInclude regexp stuck in vscode

- docs/presets/icons.md
- packages/preset-icons/src/core.ts
- packages/preset-icons/src/types.ts
- packages/transformer-directives/src/icon.ts
Changes included in https://github.com/unocss/unocss/pull/4278 will prevent using/auto-installing iconify collections not listed in default collections. In that case we need to use `createExternalPackageIconLoader` from `@iconify/utils/lib/loader/external-pkg` or node `fs` loader, check https://github.com/unocss/unocss/discussions/4318#discussioncomment-11499122.
This PR adds `safeCollectionsNames` option to allow use external collections including `auto-install` support: I'll add some hint in the jsdocs since this will work only with `@iconify-json/*` collections (✔️ done).
When there are new `@iconify-json/*` collections missing in the `collections.json` file, the consumer can use this new option until we release a new version with the new iconify collections included in the json file …
> feat(preset-icons,transformer-directives): allow add safe icons collections

- packages/core/src/config.ts
```ts
const a = definePreset({
//  ^ - Preset<object>
name: 'nameA',
})
const b = definePreset(() => ({
//  ^ - PresetFactory<object, undefined>
name: 'nameB',
}))
const c = definePreset(async () => ({
//  ^ - PresetFactoryAwaitable<object, undefined>
name: 'nameC',
}))
```
Related to #4268
> feat(core): add `PresetFactoryAwaitable` type to `definePreset`

- packages/nuxt/src/index.ts
Because srcDir value may be modified
> fix(nuxt): use rootDir instead of srcDir to find the config files under the layer

- packages/vite/src/modes/global/build.ts
- packages/vite/src/modes/global/dev.ts
- packages/vite/src/modes/global/shared.ts
- packages/vite/src/types.ts
This PR adds an option `checkImport` to vite plugin.
Framework like [WXT](https://github.com/wxt-dev/wxt) supports dynamic entrypoints and only partial of them need style.
Using UnoCSS as a vite plugin will get the warning every time run dev and build.
It's kind of annoying.
> feat(vite): add option `checkImport`

- netlify.toml
Since node version 22 is stable now, may be we may try node v22 here.
> chore: bump node v22 for netlify

- scripts/postbuild.ts
Temporal fix until we fix it at unbuild, this PR using the logic in the plugin included in #4397 , but using latest latest unbuild version.
NOTES:
- the current unbuild cjs plugin fixing only some default exports in `d.cts` files (ignoring `d.ts` files)
- the modified `scripts/postbuild.ts` script included in this PR will not fix default cjs exports like `export { default } from '<some-specifier>'` (will work only here since we don't use anywhere this format)
- once fixed at unbuild, we can remove the `scripts/postbuild.ts` script and change the build script to run `script/verify-dist.ts`
closes #4354
closes #4396
supersedes #4397
> fix: default cjs package exports

- .github/workflows/schedule.yml
This PR corrects the npm scripts for [workflow schedule](https://github.com/unocss/unocss/blob/main/.github/workflows/schedule.yml).
https://github.com/unocss/unocss/blob/2c42584eb2ff8396555db49979fa317103d62dfb/.github/workflows/schedule.yml#L30
which should be
https://github.com/unocss/unocss/blob/2c42584eb2ff8396555db49979fa317103d62dfb/package.json#L29
Introduced in https://github.com/unocss/unocss/pull/4364
> ci: fix run npm scripts

- packages-integrations/inspector/client/components/CodeMirror.vue
This PR fixes codemirror search button color in light theme.
light
dark
> fix(inspector): improve codemirror search extension style

- packages-integrations/eslint-plugin/src/rules/blocklist.ts
- packages-integrations/eslint-plugin/src/rules/enforce-class-compile.ts
- packages-integrations/eslint-plugin/src/rules/order-attributify.ts
- packages-integrations/eslint-plugin/src/rules/order.ts
This PR fixes: 
- #4402
- #4333
Type `create` method of type `RuleWithMeta` requires two parameters: `context` and `optionsWithDefault`:
https://github.com/typescript-eslint/typescript-eslint/blob/87d72ba76c055499ea233efb73cdaef1f0d2ac4a/packages/utils/src/eslint-utils/RuleCreator.ts#L22-L39
Which is not compatible with `LooseRuleDefinition` from:
https://github.com/typescript-eslint/typescript-eslint/blob/87d72ba76c055499ea233efb73cdaef1f0d2ac4a/packages/utils/src/ts-eslint/Rule.ts#L719-L728
> fix(eslint-plugin): fix plugin rules type assertion

- packages-integrations/inspector/client/components/Overview.vue
I'm trying to work on a project where each utility is extracted in its own preset. Thus, when using the inspector, the view results in something like:
I'm unable to browse the source and analyzer tabs. Instead of this, the proposed changes will add a fixed height (100px) and set the overflow to auto for the list of presets, resulting in something like:
> fix: fixed height for presets in inspector

- packages-presets/preset-mini/src/_rules/container.ts
- test/assets/output/preset-mini-targets.css
- test/assets/preset-mini-targets.ts
The `@container` rule in `preset-mini` currently supports `container-type` values `normal` and `inline-size`. This PR adds support for the `size` value.
mdn `container-type` document: https://developer.mozilla.org/en-US/docs/Web/CSS/container-type
> feat(preset-mini): add `container-type: size` support for `@container` rule

- .github/workflows/autofix.yml
- .github/workflows/ci.yml
- .github/workflows/pkg.pr.new.yml
Fix corepack issue by using pnpm action to replace corepack enable, also since pnpm v10, pnpm has built-in corepack function, so I personally disabled corepack on my local machine too.
> ci: fix corepack issue

- packages-presets/preset-mini/test/color.test.ts
- packages-presets/rule-utils/src/colors.ts
With the following theme color setup:
```yaml
DEFAULT: 'oklch(62% 0.20 var(--hue))'
50: 'color-mix(in srgb, oklch(95% 0.10 var(--hue) / %alpha) 30%, oklch(100% 0 360))'
100: 'color-mix(in srgb, oklch(95% 0.10 var(--hue) / %alpha) 30%, oklch(100% 0 360 / %alpha))'
```
…, it appears tokens like `text-primary-100/20` yields:
```css
.text-primary-100\/20 {
color: color-mix(
in srgb,
oklch(95% 0.1 var(--hue) / 0.2) 30%,
oklch(100% 0 360 / %alpha) // <-- untouched leftover
);
}
```
…, which is not working correctly.
However, `text-primary-50/20` yields the correct output because primary-50 only have one `%alpha` placeholder: 
```css
.text-primary-50\/20 {
color: color-mix(
in srgb,
oklch(95% 0.1 var(--hue) / 0.2) 30%,
oklch(100% 0 360)
);
}
```
[Test in the …
> fix(rule-utils): replace all alpha placeholder occurrences in colors

- packages-engine/core/src/generator.ts
After generating the result normalized, check whether the css is valid and then add it.
> fix(core): correct time to add active rule

- docs/config/index.md
Reason
https://github.com/unocss/unocss/blob/a4eea88297bd39d1959959c99c4b4eb194bba9e4/packages-engine/core/src/types.ts#L813-L816
> docs: update 'plain' to 'inline' in configuration documentation

- packages-engine/core/src/types.ts
- packages-presets/preset-wind4/src/index.ts
- packages-presets/preset-wind4/src/postprocess/default.ts
- packages-presets/preset-wind4/src/postprocess/important.ts
- packages-presets/preset-wind4/src/postprocess/index.ts
- packages-presets/preset-wind4/src/postprocess/unit.ts
- packages-presets/preset-wind4/src/postprocess/utility.ts
- packages-presets/preset-wind4/src/postprocess/varPrefix.ts
- packages-presets/preset-wind4/src/preflights/theme.ts
- packages-presets/preset-wind4/src/rules/position.ts
- packages-presets/preset-wind4/src/utils/index.ts
- packages-presets/preset-wind4/src/utils/unit-resolver.ts
- test/preset-wind4.test.ts
This PR changes are as follows:
- Added `utilityResolver` option to support users to modify utility with css entry. Currently it works on `postprocessor` and `theme preflight`, you can modify the corresponding `layer name` explicitly
- Removed `processThemeVars`（`beta.7`'s option） and replaced it by `utilityResolver`
close #4509 , close #4531 
related to #4533
> feat(preset-wind4): add `utilityResolver ` option support utility convert

- packages-presets/preset-wind4/src/utils/handlers/index.ts
- packages-presets/preset-wind4/src/utils/handlers/regex.ts
- packages-presets/preset-wind4/src/utils/unit-resolver.ts
The regular expression object gets recreated every time the resolver function is called, which is less efficient than reusing the imported regex from ./handlers.
> perf(preset-wind4): hoist remRE

- packages-presets/preset-wind4/src/rules/shadow.ts
- test/assets/output/preset-wind4-targets.css
I didn't look into the code very carefully yet, but I found this due to an syntax error in the generated css:
And it seems to be an typo?
> fix(preset-wind4): shadow property

- docs/config/extractors.md
```
[pug extractor](https://github.com/unocss/unocss/tree/main/packages-integrations/extractor-pug)
```
is 404.
> docs: fix link to extractor-pug in extractors.md

- docs/config/rules.md
- packages-engine/core/src/generator.ts
- packages-engine/core/src/types.ts
- packages-engine/core/test/__snapshots__/extended-info.test.ts.snap
- packages-presets/preset-wind4/src/index.ts
- packages-presets/preset-wind4/src/preflights/theme.ts
- packages-presets/preset-wind4/src/rules/background.ts
- packages-presets/preset-wind4/src/rules/border.ts
- packages-presets/preset-wind4/src/rules/filters.ts
- packages-presets/preset-wind4/src/rules/ring.ts
- packages-presets/preset-wind4/src/rules/shadow.ts
- packages-presets/preset-wind4/src/rules/static.ts
- packages-presets/preset-wind4/src/rules/table.ts
- packages-presets/preset-wind4/src/rules/touch-actions.ts
- packages-presets/preset-wind4/src/rules/transform.ts
- packages-presets/preset-wind4/src/rules/typography.ts
- packages-presets/preset-wind4/src/utils/utilities.ts
- test/assets/output/preset-wind4-targets.css
- test/preset-wind4.test.ts
WIP, I need to implement a way to make `noMerge` check for exact duplications
This PR introduces `symbols.noMerge`, and converts `defineProperty` from raw rules to CSS object
--- 
Another approach might be that we make it possible to assign layers to raw rules
> feat(preset-wind4): hoist css properties

- packages-integrations/vite/src/modes/chunk-build.ts
- packages-integrations/vite/src/modes/global/build.ts
While I added a patch to make it work in 6.3 (https://github.com/vitejs/vite/pull/19878), I'd like to remove them in Vite 7.
This PR changes the `cssPlugin.transform` / `cssPostPlugin.transform` calls to do it more properly.
The points made are
- the handler might exist as a `handler` property
- the context passed should at least satisfy PluginContext
In Vite 7, I might add `filter` property to the css plugins. To do it more properly, you'll need to check that. But in this case, it should be fine as unocss only calls it for the files selected on unocss side.
refs #4597
> fix(vite): call css plugin transform handlers more properly

- packages-presets/preset-icons/src/core.ts
Deno now supports all of the APIs required for the node loader to work, so this removes the hack added in https://github.com/unocss/unocss/pull/759 so that deno uses the node loader as well. This fixes issues with loading icons in frameworks like https://github.com/slidevjs/slidev when running in deno.
> fix(preset-icons): use node icon loader in deno

- examples/sveltekit-preprocess/package.json
- examples/sveltekit-scoped/package.json
- examples/sveltekit/package.json
- examples/vite-svelte-postcss/package.json
- examples/vite-svelte/package.json
This PR updates the `vite-plugin-svelte` version to a version that works with Svelte 5/Vite 6.
This should make the Svelte examples here https://unocss.dev/integrations/#examples run properly again.
> fix(examples): update outdated vite-plugin-svelte in svelte examples

- docs/config/index.md
- packages-integrations/postcss/src/esm.ts
I think the `content.filesystem` options is like `@source` in [tailwindcss](https://tailwindcss.com/docs/detecting-classes-in-source-files#explicitly-registering-sources)
sometimes we may need to include the packages from `node_modules`, like [@llamaindex/chat-ui](https://www.npmjs.com/package/@llamaindex/chat-ui)
so it'd be better to be able access the node_modules
> feat(postcss): allow content from node_modules

- packages-presets/preset-wind4/src/rules/border.ts
- packages-presets/preset-wind4/src/utils/utilities.ts
- test/assets/output/preset-wind4-targets.css
close #4634
In the `border` rule, when alpha is specified, I think you are using transparent on purpose, so no `alpha` related css variables are generated.
> fix(preset-wind4): optimize border opacity

- packages-presets/preset-wind4/src/theme/font.ts
- test/assets/output/preset-wind4-theme.css
After testing out `presetWind4` on my personal site I noticed that the `leading-none` utility was not working. Appears to just be missing so I added it!
https://tailwindcss.com/docs/line-height
> fix(preset-wind4): add `leading-none` utility

- docs/config/index.md
- docs/guide/extracting.md
- packages-engine/core/src/types.ts
- virtual-shared/integration/src/defaults.ts
I tried using unocss in vue-vine, but unocss does not support `.ts|js` by default, so I hope unocss can support vine.ts by default
Minimum reproduction path [here](https://stackblitz.com/edit/unocss-unocss-59z5bv85?file=uno.config.ts)
> feat(virtual-shared): update defaultPipelineInclude to support vue-vine

- packages-integrations/vscode/src/utils.ts
- packages-integrations/vscode/test/utils.test.ts
This PR is for the VSCode extension, allowing it to display colors inline with the text when they are in oklch.
The only change is to make `cssColorRE` match oklch colors.
Fix #4651
> fix(vscode-ext): display oklch colors inline

- packages-presets/preset-mini/src/_variants/pseudo.ts
- packages-presets/preset-wind4/src/variants/pseudo.ts
- test/assets/output/preset-mini-targets.css
- test/assets/output/preset-wind4-targets.css
- test/assets/preset-mini-targets.ts
close #4647
Enhance `pseudo` variants. In order not to affect subsequent rule parsing and cause incorrect capture strings, only the syntax starting with `pseudo-[xxx]` is supported.
> feat(preset-mini, preset-wind4): enhance `pseudo` syntax

- packages-integrations/vite/src/modes/global/dev.ts
This PR fixes this ecosystem-ci failure: https://github.com/vitejs/vite-ecosystem-ci/actions/runs/15061007152/job/42336016816#step:8:2085
This old interface will be removed in the next major (https://github.com/vitejs/vite/pull/19349) and the type error was happening.
> chore(vite): add ts-ignore to transformIndexHtml old interface

- packages-presets/preset-wind4/src/utils/utilities.ts
- packages-presets/transformer-directives/src/apply.ts
- test/transformer-directives.test.ts
Currently it generates:
```ts
const result = await transform(
`.btn {
--at-apply: border-red-500 text-red-500;
}`,
)
await expect(result)
.toMatchInlineSnapshot(`
".btn {
color: color-mix(
in oklch,
var(--colors-red-500) var(--un-text-opacity),
transparent
);
border-color: color-mix(
in oklch,
var(--colors-red-500) var(--un-border-opacity),
transparent
);
syntax: "<percentage>";
inherits: false;
initial-value: 100%;
syntax: "<percentage>";
inherits: false;
initial-value: 100%;
}
"
`)
```
With the fix, now it looks like:
```ts
const result = await transform(
`.btn {
--at-apply: border-red-500 text-red-500;
}`,
)
await expect(result)
.toMatchInlineSnapshot(`
".btn {
color: color-mix(
in oklch,
var(--colors-red-500) var(--un-text-opacity),
transparent
);
border-color: color-mix(
in oklch, …
```
> fix(directives): `@apply` should respect `noMerge` meta

- packages-presets/preset-wind4/src/postprocess/important.ts
> fix(preset-wind4): skip `properties` layer in important postprocessor

- packages-integrations/inspector/src/index.ts
Hi!
It seems like #4536 was not correct fix for this issue.
```md
➜  Local:   http://localhost:5173/
➜  UnoCSS Inspector: http:/localhost:5173/__unocss/
^ notice the broken protocol
➜  Local:   http://localhost:5173/app
➜  UnoCSS Inspector: http://localhost:5173/app/__unocss/
^ incorrect url, the inspector will be at /__unocss/
➜  Local:   http://localhost:5173/
➜  UnoCSS Inspector: http://localhost:5173/__unocss/
➜  Local:   http://localhost:5173/app
➜  UnoCSS Inspector: http://localhost:5173/__unocss/
```
I think my testing was careful enough, but ping me if I missed anything
> fix: inspector url

- packages-integrations/vite/src/modes/chunk-build.ts
- test/fixtures.test.ts
This PR makes some small changes to make ecosystem-ci pass with rolldown-vite.
> chore: make ecosystem-ci pass with rolldown-vite

- eslint.config.js
- packages-integrations/vscode/package.json
- packages-integrations/vscode/src/annotation.ts
- packages-integrations/vscode/src/configs.ts
Allows to override these four options: `'underline', 'colorPreview', 'remToPxPreview', 'remToPxRatio'` in language specific settings, so that annotations can be disabled in css files.
Before:
After:
> feat(vscode): allows overriding of annotation related settings

- packages-integrations/nuxt/src/index.ts
In the future, this would also allow moving the packages to optional dependencies or something similar, to stop having to install Webpack when using Nuxt.
For now, this allows removing `@unocss/webpack` from being installed without breaking the plugin.
e.g.
```yml
// pnpm-workspace.yaml
overrides:
"@unocss/webpack": "-"
```
> fix(nuxt): Dynamically Import Vite/Webpack Plugins When Needed

- packages-integrations/astro/package.json
- packages-integrations/vite/package.json
- packages-presets/unocss/package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
Add Vite 7 to peer dep
However, we have to drop node 18 first, since Vite did it
> feat: support Vite 7

- packages-presets/preset-wind4/src/variants/default.ts
- packages-presets/preset-wind4/src/variants/inert.ts
- test/assets/output/preset-wind4-targets.css
- test/assets/preset-wind4-targets.ts
[tailwindcss](https://tailwindcss.com/docs/hover-focus-and-other-states#styling-inert-elements)
> feat(preset-wind4): support `inert` variant

- docs/presets/wind4.md
Fixes a typo in the Wind4 preset docs.
> docs: fix typo

- docs/presets/wind4.md
This PR replaces the `[!code focus]` with `[!code ++]` in the docs to make the text easier to read. The blur of the code focus is imo a bit distracting and I think the green highlight of the diff makes it a bit more clear what you need to copy to make something work.
> docs: replace code focus with code ++ to increase legibility

- packages-integrations/svelte-scoped/build.config.ts
- packages-integrations/svelte-scoped/src/_preprocess/index.ts
Before this PR the generator is created differently for both cases. This fixes it and also uses `preset-wind3` instead of the deprecated `preset-uno`.
> fix(svelte-scoped): create uno generator uniformly

- virtual-shared/integration/src/hash.ts
ref: https://github.com/vitejs/vite/pull/18317
> perf: use `crypto.hash` when available

- alias.ts
- packages-engine/autocomplete/build.config.ts
- packages-engine/autocomplete/src/create.ts
- packages-engine/autocomplete/src/parse.ts
- packages-engine/autocomplete/src/types.ts
- packages-engine/autocomplete/test/__snapshots__/autocomplete.test.ts.snap
- packages-engine/autocomplete/test/autocomplete.test.ts
- packages-integrations/nuxt/src/options.ts
- packages-integrations/vscode/package.json
- packages-integrations/vscode/src/autocomplete.ts
- packages-integrations/vscode/src/contextLoader.ts
- packages-presets/preset-icons/build.config.ts
- packages-presets/preset-icons/src/core.ts
- packages-presets/preset-icons/src/index.ts
- packages-presets/transformer-attributify-jsx/build.config.ts
- packages-presets/transformer-attributify-jsx/src/index.ts
- pnpm-lock.yaml
- tsconfig.json
- virtual-shared/integration/src/env.ts
- virtual-shared/integration/src/index.ts
close #3942, close #3946
This PR changes the following:
- [virtual-shared/integration]: Extracts the common env detection mechanism.
- [autocomplete]: When creating an autocomplete instance, all templates are automatically parsed and cached, and errors are collected. Previously, template parsing continued during the suggest phase.
I don't believe there's any performance difference between creating autocomplete and analyzing templates using suggest. The only difference is that suggest filters templates configured with variants as needed, which is negligible given the small number of templates that can be configured with variants.
> fix(vscode, autocomplete): pre-sense template errors

- packages-integrations/eslint-plugin/src/rules/order.ts
This PR disallows extra options properties in `order` rule options of the ESLint plugin.
> fix(eslint): disallow extra properties in rule options

- packages-presets/preset-web-fonts/src/preset.ts
When using an unstable network, the web font preflight will fail, so it's better to handle the error thrown by `getPrelight`.
Which caused `vite` load unocss config fail, and quit unexpectedly.
> fix(preset-web-fonts): handle errors during web fonts preflight fetch

- packages-integrations/runtime/src/presets/preset-wind4.ts
Hello @zyyv. This began with https://github.com/unocss/unocss/discussions/4700 where I identified that preset-wind4 was missing for the UnoCSS browser runtime. 
It has been more than 3 months but the PR never came, so: 
- I built it myself and it works (check https://github.com/zauberzeug/nicegui/pull/4832/files#diff-2ed51cbcd03da58d03558d618586935bc33d0146601f266464b6801cad0090aa)
- I guess maybe we can YOLO it since we have GitHub actions on our back. https://github.com/unocss/unocss/actions
NiceGUI, where I am contributing the most, may in-the-end need UnoCSS due to how Quasar works (ref: https://github.com/zauberzeug/nicegui/issues/5156#issuecomment-3324997082), so I am looking to boost the progress. Thanks!
> feat(runtime): Add preset-wind4 integration to runtime

- packages-integrations/runtime/src/presets/preset-wind3.ts
This PR mirrors https://github.com/unocss/unocss/pull/4933 but for preset-wind3. 
We already have Tailwind V3 preset in browser side but it is still under the old and deprecated name `preset-wind`. I guess we can also speed up the deprication and removal process with this. 
Note: These two PRs are separated since (1) enable selective merging, (2) GitHub website limitations.
> feat(runtime): Add preset-wind3 integration to runtime
